### ISSUE TITLE
generate_exports caused compiler crash with ES6 #ES6 #bug

### ISSUE THREAD

**Issue by rikuayanokozy** [google/closure-compiler#1450] opened 2016-01-27 03:55 UTC
Minimum test case:
```class Test {
    /** @export */
    test() {}
}```

WIll get following error:
```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable goog
  Node(NAME goog): test.js:4:4
    test() {}
  Parent(GETPROP): test.js:4:4
    test() {}

        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:202)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:621)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:316)
        at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:142)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1943)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:700)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:651)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:648)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unexpected variable goog
        ... 21 more

```

http://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Test%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540export%2520*%252F%250A%2520%2520%2520%2520test()%2520%257B%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26GENERATE_EXPORTS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by MatrixFrog** [comment] 2016-01-27 03:58
Duplicate of #1393

**Closed by MatrixFrog** 2016-01-27 03:58 UTC
