### ISSUE TITLE
--property_renaming_report produces wrong mapping for global properties

### ISSUE THREAD

**Issue by AshleyScirra** [google/closure-compiler#3601] opened 2020-05-26 13:38 UTC
Version: v20200517
Command:
`java -jar closure-compiler.jar --js in.js --js_output_file out.js --compilation_level ADVANCED --property_renaming_report report.txt`

in.js:
```js
window.myGlobal = {
	prop: "foo"
}
```

out.js:
```.js
window.a={b:"foo"};
```

I would expect the resulting report to indicate `myGlobal` was renamed to `a`, and `prop` was renamed to `b`. Instead it produces this output:

```
a:a
prop:b
```

It correctly listed the mapping for the object property, but the global property incorrectly puts the same name as the original. It should be `myGlobal:a`.

**Comment by concavelenz** [comment] 2020-06-03 21:56
Property renaming map doesn't have much purpose, if you have type based optimization enabled.  "disambiguate" and "ambiguate" properties passes create a 1:many and a many:1 mappings.   These reports only exist for legacy use case.

If you need to know what a property has been renamed to/from source maps are the correct solution.

**Comment by AshleyScirra** [comment] 2020-06-04 11:52
By "type based optimization" do you mean the `--use_types_for_optimization` flag? I'm not using that.

Since JS is a dynamic language, without type information I assumed Closure Compiler was required to consistently rename the same property to the same short name, regardless of where the property is used, because it can't prove if the property is an alias of another one with the same name. So I thought it had to consistently rename properties according to a 1:1 map. Is this not the case?

**Comment by concavelenz** [comment] 2020-06-04 19:36
--use_types_for_optimization is on by default for ADVANCED mode, you would need to turn it off.

Even without type based optimizations, the compiler can still transform known objects properties when the value is known (property collapsing, method devirtualization) but ignoring those and assuming type based optimizations are disabled, the renaming map is 1:1.

There are two uses for this map, deobfuscation for which source maps are better, and to when used as a hint to minimize the diffs when it is provided as a input to future jobs.  For neither of these, the use of type based optimizations don't interfere.

A third use case folks try to use it for is cross compilation job communication, and for that it should not be used as whether a property can be renamed or whether a particular name is available depends on the compiler inputs and can change over time.

**Comment by AshleyScirra** [comment] 2020-06-05 11:34
> --use_types_for_optimization is on by default for ADVANCED mode, you would need to turn it off.

Oh right, I had no idea. I was looking at [Flags & Options](https://github.com/google/closure-compiler/wiki/Flags-and-Options) and it didn't say anything about that there, so I assumed it was off until enabled. Passing `--use_types_for_optimization false` indeed results in a correct property renaming map with an entry `myGlobal:a`.

The goal here is to make sure we can de-obfuscate crash reports that come through telemetry. For example if an exception is logged to our server that says "Cannot read property 'a' of null", we want to be able to reverse 'a' to the original property name to help diagnose what the problem might be. Our previous minifier had 1:1 name mapping and so could produce a simple lookup map to reverse the renaming. It looks like this is possible with source maps as well, but with more complexity. In particular if it refers back to original source files, this requires lookups in to the full source tree of a specific release version, whereas currently we just save the rename map for each release.

So for us I think a `--property_renaming_report` option with 1:1 renaming is still actively useful for us - but you referred to it as for legacy use cases. Is this option something we can rely on in future?

**Comment by concavelenz** [comment] 2020-06-05 17:18
We have no plan at this point to remove it, we primarily view it as a debugging tool but as you said, without type based optimizations, it works pretty well for the use case you describe.

At this point, I going to close this as "working as intended.

**Closed by concavelenz** 2020-06-05 17:18 UTC
