### ISSUE TITLE
dependency_mode STRICT will not cosider external interfaces

### ISSUE THREAD

**Issue by tSte** [google/closure-compiler#1638] opened 2016-03-11 13:31 UTC
Simply put:
- foo.js -
```js
goog.provide('app');

/** @param {IMyType} arg My Type */
function foo(arg) {
  console.log(arg);
}

window['exp'] = foo;
```

- bar.js -
```js
/** @interface name */
function IMyType() {}
/** @type {string} */
IMyType.prototype.a;
```

Compiled with dependency_mode STRICT results into warning:
```
[14:16:39] gulp-google-closure-compiler: /src2/foo.js:3: WARNING - Bad type annotation. Unknown type IMyType
/** @param {IMyType} arg My Type */
```

What interests me is:
1.) I suppose compiler won't consider those interfaces and might "wrongly" rewrite some properties, right?
2.) Do I have to import all interfaces in single file (e.g. main, so it will just be included) or in each file where the interface is used?
3.) I don't understand quite well dependency mode LOOSE... does it keep all files for compilation process (e.g. it will be slower) or does it keep files in compiled code too (e.g. won't remove dead code)?

**Comment by Dominator008** [comment] 2016-03-11 13:40
1) Yes, `bar.js` is essentially invisible to the compiler under `--dependency_mode=STRICT`.
2) You can `goog.provide` each interface from the files that define them, and `goog.require` in each file that uses a particular interface.
3) `--dependency_mode=LOOSE` will **keep** the files in the compiled code, see https://github.com/google/closure-compiler/wiki/Managing-Dependencies.

**Comment by Dominator008** [comment] 2016-03-11 13:41
Working as intended, closing.

**Closed by Dominator008** 2016-03-11 13:41 UTC

**Comment by ChadKillingsworth** [comment] 2016-03-11 16:09
You must provide dependency information for every source file when using `STRICT`. Dependency information can be any combination of `goog.require` and `goog.provide`, CommonJS `require` and `module.export` with the `--process_common_js_modules` flag or ES6 `import` and `export` statements.

**Comment by tSte** [comment] 2016-03-11 20:05
I am well aware I can do that, but I wasn't sure whether STRICT is just about better compilation speed or not. I understand why you chose this way. However how about larger libraries, that keep interfaces in separate files? LOOSE mode will keep entire code base and will not remove dead code, while STRICT might mess up compilation result. It's little bit lose-lose situation. The worst thing about it is the need to require interface in each file that need to implement it. For my current project GCC produced ~500 bad annotations warnings and each of them can cause error. Perhaps it would be beneficial to introduce new interface flag (path to files with interfaces) instead of importing interfaces (GCC will remove them anyway, right?)

**Comment by ChadKillingsworth** [comment] 2016-03-11 20:11
That's not really feasible. The files are sorted and dropped long before any type information is available. Also, interfaces are not required to be in a file by themselves. The dependency management of the compiler works on the file level.

Once #1476 gets re-applied (now #1628), you can list all your files like this as entry points and they will be kept.

**Comment by Dominator008** [comment] 2016-03-11 20:13
@tSte Is your code compatible with ADVANCED_OPTIMIZATIONS? If so you can get dead code elimination while using `LOOSE` mode.

**Comment by ChadKillingsworth** [comment] 2016-03-11 20:14
@Dominator008 If the included file has side effects, it will never be completely removed.

**Comment by Dominator008** [comment] 2016-03-11 20:15
@ChadKillingsworth That's true though.

**Comment by tSte** [comment] 2016-03-11 20:31
@Dominator008 sure. It would have little sense to use it for me without ADVANCED :)  @ChadKillingsworth can you define "side effect"? Is it something like console.log() or exporting symbols via window['symbol']? Simply put: If a file (module) exports symbol, but there aren't any other modules, that do import from it (it's basicly dead code)... does compiler remove that module or not?

@ChadKillingsworth is there any chance to see #1476 (#1628) in official release any time soon?

**Comment by ChadKillingsworth** [comment] 2016-03-11 20:36
A side effect would be any external side-effect causing method call (like `console.log`) or assignment to an external property (like `window['symbol'] = foo`) that happens in the global scope.

I don't know if those PRs will make it in before the next release or not. It's just a timing thing. They have already been reviewed, but something broke the internal builds at Google and they were rolled back.

**Comment by tSte** [comment] 2016-03-11 20:45
I'll keep my fingers crossed...
