### ISSUE TITLE
Spread operator issues

### ISSUE THREAD

**Issue by elmart** [google/closure-compiler#2082] opened 2016-10-13 16:07 UTC
I use ES6 and generate ES5 output.
I've just updated to v20160911, and some spread operators, that previously translated well, now cause uncaught exceptions, with an error "$jscomp.arrayFromIterable is not a function".
I have tried to get a minimum reproducible sample, but haven't had success up to now.

**Comment by MatrixFrog** [comment] 2016-10-13 17:07
Sounds like maybe we're forgetting to inject the file that contains es6/util/arrayfromiterable.js in some cases. Can you say if it's a spread in a call (`f(...args)`) or in an array (`arr = [...args]`)? That might help to track it down.

**Comment by elmart** [comment] 2016-10-13 17:20
It's a spread in an array.

Apart from that, I've now checked some other previous versions (the one I had before updating was v20160517), with the following results:

- v20160517 - Ok
- v20160619 - Ok
- v20160713 - javascript error "$jscomp.initSymbol is not a function”
- v20160822 - javascript error “$jscomp.arrayFromIterable is not a function”
- v20160911 - javascript error “$jscomp.arrayFromIterable is not a function”

Hope that helps.

**Comment by brad4d** [comment] 2016-10-17 17:45
I'll look into this a bit.
I'm concerned this bug may affect upcoming changes to handling super() constructor calls
when we have to generate a missing subclass constructor.
See #1669

**Comment by brad4d** [comment] 2016-10-17 18:01
@elmart, what compiler options are you using when you see this behavior?
Specifically:
-   Are you specifying `--norewrite_polyfills` or equivalent?
-   What language input mode are you specifying with `--language_in`?

**Comment by brad4d** [comment] 2016-10-17 18:42
I haven't been able to reproduce this, but it won't affect #1669 after all.

**Comment by brad4d** [comment] 2016-10-17 18:47
The methods mentioned in the errors were originally defined in es6_runtime.js,
but were split into separate files between v20160619 and v20160713.
2fe169dde70a8477980f3ca4de178d2f910556b5 

@elmart, can you determine whether the output from the compiler actually contains these methods or not?

**Comment by elmart** [comment] 2016-10-22 19:45
I'm compiling from java code like the following:
```java
        final List<SourceFile> inputs = Arrays.asList(
            SourceFile.fromCode(name.full().toString(), src));
        final CompilerOptions options = new CompilerOptions();
        CompilationLevel.SIMPLE_OPTIMIZATIONS
        //CompilationLevel.ADVANCED_OPTIMIZATIONS
            .setOptionsForCompilationLevel(options);
        options.setLanguageIn(CompilerOptions.LanguageMode.ECMASCRIPT6);
        options.setLanguageOut(CompilerOptions.LanguageMode.ECMASCRIPT5);
        final Compiler compiler = new Compiler();
        final List<SourceFile> externs =
            CommandLineRunner.getBuiltinExterns(options.getEnvironment());
        final Result result = compiler.compile(externs, inputs, options);
```

**Comment by elmart** [comment] 2016-10-23 09:54
And I've checked that the definition of $jscomp.arrayFromIterable() is there (in fact, twice):
```
grep 'arrayFromIterable=' ./lt-site/lt-web/target/ROOT/work/mainPrivate-1150D2BDCE7B1D94E7FA7D2DAA9DD36711AF1BF9/mainPrivate-CA14C63210301CFAE22DDCB09033C138184FD6BC.js
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.iteratorPrototype=function(h){$jscomp.initSymbolIterator();h={next:h};h[$jscomp.global.Symbol.iterator]=function(){return this};return h};$jscomp.makeIterator=function(h){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var d=h[Symbol.iterator];return d?d.call(h):$jscomp.arrayIterator(h)};$jscomp.arrayFromIterator=function(h){for(var d,r=[];!(d=h.next()).done;)r.push(d.value);return r};$jscomp.arrayFromIterable=function(h){return h instanceof Array?h:$jscomp.arrayFromIterator($jscomp.makeIterator(h))};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.makeIterator=function(d){$jscomp.initSymbolIterator();var l=d[Symbol.iterator];return l?l.call(d):$jscomp.arrayIterator(d)};$jscomp.arrayFromIterator=function(d){for(var l,m=[];!(l=d.next()).done;)m.push(l.value);return m};$jscomp.arrayFromIterable=function(d){return d instanceof Array?d:$jscomp.arrayFromIterator($jscomp.makeIterator(d))};
$jscomp.iteratorPrototype=function(f){$jscomp.initSymbolIterator();f={next:f};f[$jscomp.global.Symbol.iterator]=function(){return this};return f};$jscomp.makeIterator=function(f){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var h=f[Symbol.iterator];return h?h.call(f):$jscomp.arrayIterator(f)};$jscomp.arrayFromIterator=function(f){for(var h,k=[];!(h=f.next()).done;)k.push(h.value);return k};$jscomp.arrayFromIterable=function(f){return f instanceof Array?f:$jscomp.arrayFromIterator($jscomp.makeIterator(f))};
```

But nonetheless, I still get the runtime js error: `Uncaught TypeError: $jscomp.arrayFromIterable is not a function`.
This is with version v20160911.

**Comment by elmart** [comment] 2016-10-26 07:27
@brad4d Have you been able to reproduce this?

**Comment by brad4d** [comment] 2016-10-26 16:52
I haven't been able to reproduce this.
Having the definition show up 4 times is suspicious.
Are you compiling all your sources in one go, or in 4 batches and then concatenating them?
Are you wrapping the output in any way, either with the compiler's option for generating a wrapper or separately after compilation?

In Chrome I get the "is not a function" error when `$jscomp` exists but has no `arrayFromIterable` member. The error is different if `$jscomp` is undefined, so at least the code to initialize `$jscomp` itself must have executed.

**Comment by brad4d** [comment] 2016-10-26 17:05
Here's the compilation of a simple bit of code that uses spread.
In the output the definition of $jscomp.arrayFromIterable is a statement at the top lexical level and before any of the original code.

Where does it end up in your case?

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520var_args%250A%2520*%252F%250Afunction%2520foo(...var_args)%2520%257B%250A%2520%2520alert(var_args)%253B%250A%257D%250A%250Aconst%2520a%2520%253D%2520%255B1%252C%25202%252C%25203%255D%253B%250Afoo(...a)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by wa-Nadoo** [comment] 2016-11-03 15:10
[Code sample with issue](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%27use%2520strict%27%253B%250APromise%250A%2520%2520%2520%2520.all(fetch(%27http%253A%252F%252Fftp.byfly.by%252Ftest%252F100kb.txt%27%252C%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520mode%253A%2520%27no-cors%27%250A%2520%2520%2520%2520%257D))%250A%2520%2520%2520%2520.then((%255Bfile%255D)%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.log(%27done!%27)%250A%2520%2520%2520%2520%257D)%253B%250A)

**Comment by brad4d** [comment] 2016-11-18 16:43
Since I've been unable to reproduce this, I'm going to close it.

@elmart 
I believe there must be something unusual about the way your using the compiler that I cannot figure out.
If you can answer my question from my last comment, I'll take another look.

**Closed by brad4d** 2016-11-18 16:43 UTC
Labels: bug, ES6
