### ISSUE TITLE
Closure renames static Promise polyfill functions in advanced mode

### ISSUE THREAD

**Issue by b-strauss** [google/closure-compiler#2483] opened 2017-05-08 14:51 UTC
Compiler used: `closure-compiler-v20170423.jar`
System: Windows 10

Using advanced mode in combination with Promise polyfills breaks certain Promise functions. In my case `Promise.all`, but `Promise.race` is also affected.

compiler command:
`java -jar closure-compiler-v20170423.jar --js="./test.js" --compilation_level="ADVANCED" --language_in="ECMASCRIPT6" --language_out="ECMASCRIPT5" --formatting="pretty_print" --js_output_file="./test.min.js"`

input file (test.js):
```javascript
Promise.all([1, 2, 3])
  .then(
    result => console.log(result),
    error => console.log(error)
  );
```

output file (test.min.js):
```javascript
var h = "function" == typeof Object.defineProperties ? Object.defineProperty : function(a, c, g) {
  a != Array.prototype && a != Object.prototype && (a[c] = g.value);
}, k = "undefined" != typeof window && window === this ? this : "undefined" != typeof global && null != global ? global : this;
function l() {
  l = function() {
  };
  k.Symbol || (k.Symbol = m);
}
var n = 0;
function m(a) {
  return "jscomp_symbol_" + (a || "") + n++;
}
function p() {
  l();
  var a = k.Symbol.iterator;
  a || (a = k.Symbol.iterator = k.Symbol("iterator"));
  "function" != typeof Array.prototype[a] && h(Array.prototype, a, {configurable:!0, writable:!0, value:function() {
    return q(this);
  }});
  p = function() {
  };
}
function q(a) {
  var c = 0;
  return t(function() {
    return c < a.length ? {done:!1, value:a[c++]} : {done:!0};
  });
}
function t(a) {
  p();
  a = {next:a};
  a[k.Symbol.iterator] = function() {
    return this;
  };
  return a;
}
function u(a) {
  p();
  var c = a[Symbol.iterator];
  return c ? c.call(a) : q(a);
}
for (var v = k, w = ["Promise"], x = 0; x < w.length - 1; x++) {
  var y = w[x];
  y in v || (v[y] = {});
  v = v[y];
}
var A = w[w.length - 1], B = v[A], C = function() {
  function a(b) {
    this.b = 0;
    this.h = void 0;
    this.a = [];
    var a = this.f();
    try {
      b(a.resolve, a.reject);
    } catch (e) {
      a.reject(e);
    }
  }
  function c() {
    this.a = null;
  }
  if (B) {
    return B;
  }
  c.prototype.b = function(a) {
    this.a || (this.a = [], this.f());
    this.a.push(a);
  };
  c.prototype.f = function() {
    var a = this;
    this.c(function() {
      a.h();
    });
  };
  var g = k.setTimeout;
  c.prototype.c = function(a) {
    g(a, 0);
  };
  c.prototype.h = function() {
    for (; this.a && this.a.length;) {
      var a = this.a;
      this.a = [];
      for (var d = 0; d < a.length; ++d) {
        var e = a[d];
        delete a[d];
        try {
          e();
        } catch (f) {
          this.g(f);
        }
      }
    }
    this.a = null;
  };
  c.prototype.g = function(a) {
    this.c(function() {
      throw a;
    });
  };
  a.prototype.f = function() {
    function a(a) {
      return function(b) {
        e || (e = !0, a.call(d, b));
      };
    }
    var d = this, e = !1;
    return {resolve:a(this.o), reject:a(this.g)};
  };
  a.prototype.o = function(b) {
    if (b === this) {
      this.g(new TypeError("A Promise cannot resolve to itself"));
    } else {
      if (b instanceof a) {
        this.s(b);
      } else {
        a: {
          switch(typeof b) {
            case "object":
              var d = null != b;
              break a;
            case "function":
              d = !0;
              break a;
            default:
              d = !1;
          }
        }
        d ? this.m(b) : this.i(b);
      }
    }
  };
  a.prototype.m = function(a) {
    var b = void 0;
    try {
      b = a.then;
    } catch (e) {
      this.g(e);
      return;
    }
    "function" == typeof b ? this.u(b, a) : this.i(a);
  };
  a.prototype.g = function(a) {
    this.j(2, a);
  };
  a.prototype.i = function(a) {
    this.j(1, a);
  };
  a.prototype.j = function(a, d) {
    if (0 != this.b) {
      throw Error("Cannot settle(" + a + ", " + d | "): Promise already settled in state" + this.b);
    }
    this.b = a;
    this.h = d;
    this.l();
  };
  a.prototype.l = function() {
    if (this.a) {
      for (var a = this.a, d = 0; d < a.length; ++d) {
        a[d].call(), a[d] = null;
      }
      this.a = null;
    }
  };
  var z = new c;
  a.prototype.s = function(a) {
    var d = this.f();
    a.c(d.resolve, d.reject);
  };
  a.prototype.u = function(a, d) {
    var b = this.f();
    try {
      a.call(d, b.resolve, b.reject);
    } catch (f) {
      b.reject(f);
    }
  };
  a.prototype.then = function(b, d) {
    function e(a, b) {
      return "function" == typeof a ? function(b) {
        try {
          f(a(b));
        } catch (D) {
          c(D);
        }
      } : b;
    }
    var f, c, g = new a(function(a, b) {
      f = a;
      c = b;
    });
    this.c(e(b, f), e(d, c));
    return g;
  };
  a.prototype.catch = function(a) {
    return this.then(void 0, a);
  };
  a.prototype.c = function(a, d) {
    function b() {
      switch(c.b) {
        case 1:
          a(c.h);
          break;
        case 2:
          d(c.h);
          break;
        default:
          throw Error("Unexpected state: " + c.b);
      }
    }
    var c = this;
    this.a ? this.a.push(function() {
      z.b(b);
    }) : z.b(b);
  };
  a.resolve = function(b) {
    return b instanceof a ? b : new a(function(a) {
      a(b);
    });
  };
  a.reject = function(b) {
    return new a(function(a, c) {
      c(b);
    });
  };
  a.b = function(b) {
    return new a(function(d, c) {
      for (var e = u(b), g = e.next(); !g.done; g = e.next()) {
        a.resolve(g.value).c(d, c);
      }
    });
  };
  a.a = function(b) {
    var d = u(b), c = d.next();
    return c.done ? a.resolve([]) : new a(function(b, e) {
      function g(a) {
        return function(c) {
          f[a] = c;
          r--;
          r || b(f);
        };
      }
      var f = [], r = 0;
      do {
        f.push(void 0), r++, a.resolve(c.value).c(g(f.length - 1), e), c = d.next();
      } while (!c.done);
    });
  };
  a.$jscomp$new$AsyncExecutor = function() {
    return new c;
  };
  return a;
}();
C != B && null != C && h(v, A, {configurable:!0, writable:!0, value:C});
Promise.all([1, 2, 3]).then(function(a) {
  return console.log(a);
}, function(a) {
  return console.log(a);
});
```

Notice the functions near the end of the file called `a.b` and `a.a`. These should be `race` and `all`.

They are correctly included in simple mode:

`java -jar closure-compiler-v20170423.jar --js="./test.js" --compilation_level="SIMPLE" --language_in="ECMASCRIPT6" --language_out="ECMASCRIPT5" --formatting="pretty_print" --js_output_file="./test.min.js"`

```javascript
var $jscomp = $jscomp || {};
$jscomp.scope = {};
$jscomp.defineProperty = "function" == typeof Object.defineProperties ? Object.defineProperty : function(a, d, e) {
  a != Array.prototype && a != Object.prototype && (a[d] = e.value);
};
$jscomp.getGlobal = function(a) {
  return "undefined" != typeof window && window === a ? a : "undefined" != typeof global && null != global ? global : a;
};
$jscomp.global = $jscomp.getGlobal(this);
$jscomp.SYMBOL_PREFIX = "jscomp_symbol_";
$jscomp.initSymbol = function() {
  $jscomp.initSymbol = function() {
  };
  $jscomp.global.Symbol || ($jscomp.global.Symbol = $jscomp.Symbol);
};
$jscomp.symbolCounter_ = 0;
$jscomp.Symbol = function(a) {
  return $jscomp.SYMBOL_PREFIX + (a || "") + $jscomp.symbolCounter_++;
};
$jscomp.initSymbolIterator = function() {
  $jscomp.initSymbol();
  var a = $jscomp.global.Symbol.iterator;
  a || (a = $jscomp.global.Symbol.iterator = $jscomp.global.Symbol("iterator"));
  "function" != typeof Array.prototype[a] && $jscomp.defineProperty(Array.prototype, a, {configurable:!0, writable:!0, value:function() {
    return $jscomp.arrayIterator(this);
  }});
  $jscomp.initSymbolIterator = function() {
  };
};
$jscomp.arrayIterator = function(a) {
  var d = 0;
  return $jscomp.iteratorPrototype(function() {
    return d < a.length ? {done:!1, value:a[d++]} : {done:!0};
  });
};
$jscomp.iteratorPrototype = function(a) {
  $jscomp.initSymbolIterator();
  a = {next:a};
  a[$jscomp.global.Symbol.iterator] = function() {
    return this;
  };
  return a;
};
$jscomp.makeIterator = function(a) {
  $jscomp.initSymbolIterator();
  var d = a[Symbol.iterator];
  return d ? d.call(a) : $jscomp.arrayIterator(a);
};
$jscomp.polyfill = function(a, d, e, b) {
  if (d) {
    e = $jscomp.global;
    a = a.split(".");
    for (b = 0; b < a.length - 1; b++) {
      var g = a[b];
      g in e || (e[g] = {});
      e = e[g];
    }
    a = a[a.length - 1];
    b = e[a];
    d = d(b);
    d != b && null != d && $jscomp.defineProperty(e, a, {configurable:!0, writable:!0, value:d});
  }
};
$jscomp.EXPOSE_ASYNC_EXECUTOR = !0;
$jscomp.FORCE_POLYFILL_PROMISE = !1;
$jscomp.polyfill("Promise", function(a) {
  function d() {
    this.batch_ = null;
  }
  if (a && !$jscomp.FORCE_POLYFILL_PROMISE) {
    return a;
  }
  d.prototype.asyncExecute = function(c) {
    null == this.batch_ && (this.batch_ = [], this.asyncExecuteBatch_());
    this.batch_.push(c);
    return this;
  };
  d.prototype.asyncExecuteBatch_ = function() {
    var c = this;
    this.asyncExecuteFunction(function() {
      c.executeBatch_();
    });
  };
  var e = $jscomp.global.setTimeout;
  d.prototype.asyncExecuteFunction = function(c) {
    e(c, 0);
  };
  d.prototype.executeBatch_ = function() {
    for (; this.batch_ && this.batch_.length;) {
      var c = this.batch_;
      this.batch_ = [];
      for (var a = 0; a < c.length; ++a) {
        var b = c[a];
        delete c[a];
        try {
          b();
        } catch (f) {
          this.asyncThrow_(f);
        }
      }
    }
    this.batch_ = null;
  };
  d.prototype.asyncThrow_ = function(c) {
    this.asyncExecuteFunction(function() {
      throw c;
    });
  };
  var b = function(c) {
    this.state_ = 0;
    this.result_ = void 0;
    this.onSettledCallbacks_ = [];
    var a = this.createResolveAndReject_();
    try {
      c(a.resolve, a.reject);
    } catch (h) {
      a.reject(h);
    }
  };
  b.prototype.createResolveAndReject_ = function() {
    function c(c) {
      return function(k) {
        b || (b = !0, c.call(a, k));
      };
    }
    var a = this, b = !1;
    return {resolve:c(this.resolveTo_), reject:c(this.reject_)};
  };
  b.prototype.resolveTo_ = function(c) {
    if (c === this) {
      this.reject_(new TypeError("A Promise cannot resolve to itself"));
    } else {
      if (c instanceof b) {
        this.settleSameAsPromise_(c);
      } else {
        a: {
          switch(typeof c) {
            case "object":
              var a = null != c;
              break a;
            case "function":
              a = !0;
              break a;
            default:
              a = !1;
          }
        }
        a ? this.resolveToNonPromiseObj_(c) : this.fulfill_(c);
      }
    }
  };
  b.prototype.resolveToNonPromiseObj_ = function(c) {
    var a = void 0;
    try {
      a = c.then;
    } catch (h) {
      this.reject_(h);
      return;
    }
    "function" == typeof a ? this.settleSameAsThenable_(a, c) : this.fulfill_(c);
  };
  b.prototype.reject_ = function(a) {
    this.settle_(2, a);
  };
  b.prototype.fulfill_ = function(a) {
    this.settle_(1, a);
  };
  b.prototype.settle_ = function(a, b) {
    if (0 != this.state_) {
      throw Error("Cannot settle(" + a + ", " + b | "): Promise already settled in state" + this.state_);
    }
    this.state_ = a;
    this.result_ = b;
    this.executeOnSettledCallbacks_();
  };
  b.prototype.executeOnSettledCallbacks_ = function() {
    if (null != this.onSettledCallbacks_) {
      for (var a = this.onSettledCallbacks_, b = 0; b < a.length; ++b) {
        a[b].call(), a[b] = null;
      }
      this.onSettledCallbacks_ = null;
    }
  };
  var g = new d;
  b.prototype.settleSameAsPromise_ = function(a) {
    var b = this.createResolveAndReject_();
    a.callWhenSettled_(b.resolve, b.reject);
  };
  b.prototype.settleSameAsThenable_ = function(a, b) {
    var c = this.createResolveAndReject_();
    try {
      a.call(b, c.resolve, c.reject);
    } catch (f) {
      c.reject(f);
    }
  };
  b.prototype.then = function(a, d) {
    function c(a, b) {
      return "function" == typeof a ? function(b) {
        try {
          f(a(b));
        } catch (l) {
          e(l);
        }
      } : b;
    }
    var f, e, k = new b(function(a, b) {
      f = a;
      e = b;
    });
    this.callWhenSettled_(c(a, f), c(d, e));
    return k;
  };
  b.prototype.catch = function(a) {
    return this.then(void 0, a);
  };
  b.prototype.callWhenSettled_ = function(a, b) {
    function c() {
      switch(d.state_) {
        case 1:
          a(d.result_);
          break;
        case 2:
          b(d.result_);
          break;
        default:
          throw Error("Unexpected state: " + d.state_);
      }
    }
    var d = this;
    null == this.onSettledCallbacks_ ? g.asyncExecute(c) : this.onSettledCallbacks_.push(function() {
      g.asyncExecute(c);
    });
  };
  b.resolve = function(a) {
    return a instanceof b ? a : new b(function(b, c) {
      b(a);
    });
  };
  b.reject = function(a) {
    return new b(function(b, c) {
      c(a);
    });
  };
  b.race = function(a) {
    return new b(function(c, d) {
      for (var e = $jscomp.makeIterator(a), h = e.next(); !h.done; h = e.next()) {
        b.resolve(h.value).callWhenSettled_(c, d);
      }
    });
  };
  b.all = function(a) {
    var c = $jscomp.makeIterator(a), d = c.next();
    return d.done ? b.resolve([]) : new b(function(a, e) {
      function h(b) {
        return function(c) {
          f[b] = c;
          g--;
          0 == g && a(f);
        };
      }
      var f = [], g = 0;
      do {
        f.push(void 0), g++, b.resolve(d.value).callWhenSettled_(h(f.length - 1), e), d = c.next();
      } while (!d.done);
    });
  };
  $jscomp.EXPOSE_ASYNC_EXECUTOR && (b.$jscomp$new$AsyncExecutor = function() {
    return new d;
  });
  return b;
}, "es6-impl", "es3");
Promise.all([1, 2, 3]).then(function(a) {
  return console.log(a);
}, function(a) {
  return console.log(a);
});
```

**Comment by shicks** [comment] 2017-05-08 17:24
This might have something to do with how `Promise` is defined in the
polyfill: it's a local variable, so maybe the compiler thinks it's
properties are eligible for renaming? In general, static methods are tricky
since the compiler really wants to collapse and rename them, and I think in
this case it has an especially hard time tracking the fact that it's
called. Certainly if we had a "no rename" annotation that could help here,
but maybe there's a better approach already available.

**Comment by b-strauss** [comment] 2017-05-08 22:41
Do you have an advice on how to work around this issue?

I see a few options:
- use `goog.Promise`
- use simple mode (not really an option)
- use third party Promise polyfill

I think option three might be the better solution until this is fixed.

**Comment by shicks** [comment] 2017-05-09 22:39
@brad4d 

Maybe we should just use quoted properties here?

**Comment by brad4d** [comment] 2017-05-09 22:54
@shicks I fear that would break type checking.
Could we put `@export` on the declarations?

@dimvar Since `PolyfillPromise` is declared to extend `Promise`, shouldn't its static methods be protected?

**Comment by ChadKillingsworth** [comment] 2017-05-09 23:05
@brad4d We don't model static inheritance in our type system. It's becoming a bigger problem each day.

`@export` only works if we add a polyfill and autoinject it for the export functions - we can't have a closure-library dependence. You can however manually export them: `Promise['race'] = Promise.race;` That's a proper export that will work everywhere and not break type checking.

You also might be able to add them with `Object.defineProperties`, but that won't work for ES3.

**Comment by brad4d** [comment] 2017-05-09 23:10
OK, thanks.
I'll do a change to explicitly export as @ChadKillingsworth described.

**Comment by concavelenz** [comment] 2017-05-10 00:46
This isn't really a type system issue.  The issue, if I understand correctly, is collapse properties is aggressive about collapse static properties.  Specifically, it always collapses properties for type annotated constructors even if they otherwise escape.  In general, constructors always escape as they are always available as the "constructor" property, so escape analysis by itself is too loose to be useful.  To do this safely, we would need to do a type based analysis of the possible property references.  Even with that were available we would still need to link the Promise type and internal polyfill declared type: it might be necessary to directly assign to the global "Promise" but this is pure speculations at this point.

**Comment by ChadKillingsworth** [comment] 2017-05-10 00:52
>  Even with that were available we would still need to link the Promise type and internal polyfill declared type

Isn't that a type system issue? Namely that `Promise.race` isn't inheritable?

**Comment by brad4d** [comment] 2017-05-10 21:51
The problem isn't in CollapseProperties.

From the output of this repro, one can see that `DisambiguateProperites` renames `race` and `all`, but not `resolve` and `reject`.

build.sh
```shell
#!/bin/bash
closure-compiler \
  --compilation_level ADVANCED \
  --print_source_after_each_pass \
  --formatting PRETTY_PRINT \
  --js main.js
```
main.js
```js
function f() {
  return Promise.resolve(1);
}
f().then(console.log('done'));
```

We didn't catch this in our internal testing, because it seems we don't have `DisambiguateProperties` enabled for our runtime tests.

**Comment by shicks** [comment] 2017-05-11 01:05
We should probably enable `DisambiguateProperties`, no?​

**Comment by brad4d** [comment] 2017-05-11 15:58
Yes, I think we should.

**Comment by brad4d** [comment] 2017-05-11 16:11
At @MatrixFrog 's suggestion I added this bit of code to the runner and recompiled my repro to find out why DisambiguateProperties did not rename 'reject' and 'resolve'.

```java
ImmutableMap.Builder<String, CheckLevel> builder = ImmutableMap.builder();
builder.put("race", CheckLevel.ERROR);
builder.put("all", CheckLevel.ERROR);
builder.put("reject", CheckLevel.ERROR);
builder.put("resolve", CheckLevel.ERROR);
options.setPropertyInvalidationErrors(builder.build());
```

I got this:

```
 [synthetic:es6/promise] :194: ERROR - Property disambiguator skipping all instances of property resolve because of type {reject: function (*=): ?, resolve: function ((IThenable<TYPE>|TYPE|null|{then: ?})=): ?} node GETPROP 194 [length: 24] [source_file:  [synthetic:es6/promise] ] : function ((IThenable<TYPE>|TYPE|null|{then: ?})=): ?. 
      executor(resolveAndReject.resolve, resolveAndReject.reject);
               ^^^^^^^^^^^^^^^^^^^^^^^^

 [synthetic:es6/promise] :194: ERROR - Property disambiguator skipping all instances of property reject because of type {reject: function (*=): ?, resolve: function ((IThenable<TYPE>|TYPE|null|{then: ?})=): ?} node GETPROP 194 [length: 23] [source_file:  [synthetic:es6/promise] ] : function (*=): ?. 
      executor(resolveAndReject.resolve, resolveAndReject.reject);
                                         ^^^^^^^^^^^^^^^^^^^^^^^
```

Which refers to this definition in our `promise.js` file.
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/js/es6/promise.js#L194

So, it seems we just got lucky with those.

**Comment by brad4d** [comment] 2017-05-11 16:12
I propose to enable DisambiguateProperties in our runtime tests and see what shakes loose.

**Comment by ChadKillingsworth** [comment] 2017-05-11 16:13
I support that plan - especially since type based optimizations are enabled by default externally.

**Comment by brad4d** [comment] 2017-05-19 17:53
runtime_tests with `--disambiguage_properties` failed only for tests in the `runtime_tests/polyfill_tests/promise` subdirectory, so that's good news.

**Comment by brad4d** [comment] 2017-05-19 22:49
Fix for this submitted internally. Should get autoclosed by Monday's github push.
Also enabled `--disambiguage_properties` for `runtime_tests` internally, so we won't have this happen with future polyfills.

**Closed** 2017-05-20 02:04 UTC
