### ISSUE TITLE
Type checker doesn't recognize Object.create

### ISSUE THREAD

**Issue by infusion** [google/closure-compiler#1705] opened 2016-04-05 02:19 UTC
Hi,

when creating an object with `Object.create(Foo.prototype)`, the type checker doesn't recognize it as an instance of `Foo`. Is this a valid behavior?

Thanks

**Comment by Dominator008** [comment] 2016-04-05 02:21
Duplicate of #302.

**Closed by Dominator008** 2016-04-05 02:21 UTC
