### ISSUE TITLE
Cannot import/require module without exports

### ISSUE THREAD

**Issue by cramforce** [google/closure-compiler#1831] opened 2016-06-07 15:34 UTC
There are NPM modules such as https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.max.js that only expose a polyfill and thus have no exports.

Currently it is not possible to import these using ES6 or CommonJS syntax, because both compiler passes do not emit an `goog.provide` if no export is available, which leads to an error at a later stage because the respective `import` does generate a `goog.require`.

This is a regression (although I realize many bugs where fixed on the way :) that was introduced in the last 6 months.

**Comment by ChadKillingsworth** [comment] 2016-06-07 15:40
Actually it should work at head - unless you are trying to do per-file transpilation. I submitted the changes to allow importing a module with no exports.

**Comment by cramforce** [comment] 2016-06-07 15:54
I'm definitely at head. Patching files with a `export function deadCode() {}` fixed it.

**Comment by MatrixFrog** [comment] 2016-06-07 16:15
I think @ChadKillingsworth is referring to https://github.com/google/closure-compiler/commit/96c8e74a08ca798ee69ec0796231f47a2bfecf26 (I also CC'd you on the Google-internal version of that). If it's not working maybe there's some edge case that was missed somehow.

**Comment by ChadKillingsworth** [comment] 2016-06-07 16:29
If you can give me a repo case, I'll be happy to take a look.

**Comment by cramforce** [comment] 2016-06-07 18:46
I have a PR here with a workaround that makes our repo build successfully:
https://github.com/ampproject/amphtml/pull/3478/files

Unfortunately our JSCompiler integration is extremely complex, both in terms of flags, srcs (we use a hack to show different files to JSCompiler than to Babel/browserify for non-prod builds) and we use a [custom command line runner](https://github.com/ampproject/amphtml/blob/master/build-system/runner/src/org/ampproject/AmpCommandLineRunner.java#L48).

The line that failed was very simple, though, and I suspect would also fail in a simple setup: Here is the line https://github.com/ampproject/amphtml/blob/master/src/polyfills.js#L17

**Comment by ChadKillingsworth** [comment] 2016-06-11 19:24
Just tested this at head and it's working as intended for me:

### foo.js
```js
console.log('foo');
```

### test.js
```js
import './foo';
```

### Compile command
I tested this with and without dependency management enabled
```
java -jar target/closure-compiler-1.0-SNAPSHOT.jar -O=ADVANCED -W=VERBOSE 
    --js=foo.js --js=test.js --dependency_mode=STRICT --entry_point=./test 
```

### output
```js
console.log("foo");
```

My first guess is that your custom command-line runner may be influencing behavior here.

We also have test coverage for this case: https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/CommandLineRunnerTest.java#L1768-L1785

**Comment by cramforce** [comment] 2016-06-14 15:44
Could you point me to the code that emits the `goog.provide` for the file without the export. I'll take a look if there are any conditions that we do not meet.

**Comment by MatrixFrog** [comment] 2016-06-14 15:51
https://github.com/google/closure-compiler/blob/e29bcdb897d0271cae41cf64c1c36592ef1b857d/src/com/google/javascript/jscomp/Compiler.java#L1402-1416 (the "true" on line 1415 means "force rewrite" -- that is, rewrite the file as a module even though it contains no `import`s or `export`s)

**Comment by ChadKillingsworth** [comment] 2016-06-14 15:52
One thought that might fail to trigger rewriting, the detection code only works if existing goog.require/provide calls have been reported to the compiler. This should have occurred by module rewriting passes.

The `getKnownProvides` and `getKnownRequires` methods were added specifically because the `getRequires` and `getProvides` methods can trigger a full parse on files that would not otherwise of yet been parsed.

**Comment by ChadKillingsworth** [comment] 2016-11-19 18:41
Since we have no further information - I'm closing this.

**Closed by ChadKillingsworth** 2016-11-19 18:41 UTC
