### ISSUE TITLE
BanUnknownTypedClassPropsReferences crashing

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1958] opened 2016-08-17 18:42 UTC
Latest tip is crashing in this conformance check. 

Non-NTI:
```
null
  Node(GETPROP): Web/Common/Automation/src/automation/defaultautomation/Automation.js:1088:14
/** @export */window.__vo_aut_getAutomationExtensionNames = automation.getAutomationExtensionNames.bind(automation);
  Parent(CALL): Web/Common/Automation/src/automation/defaultautomation/Automation.js:1088:14
/** @export */window.__vo_aut_getAutomationExtensionNames = automation.getAutomationExtensionNames.bind(automation);

	at com.google.javascript.jscomp.ConformanceRules$BanUnknownTypedClassPropsReferences.checkConformance(ConformanceRules.java:1235)
	at com.google.javascript.jscomp.ConformanceRules$AbstractRule.check(ConformanceRules.java:198)
	at com.google.javascript.jscomp.ConformanceRules$CustomRuleProxy.check(ConformanceRules.java:962)
	at com.google.javascript.jscomp.CheckConformance.visit(CheckConformance.java:96)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:646)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
```

The line referred to is:
``` javascript
/** @export */window.__vo_aut_getAutomationExtensionNames = automation.getAutomationExtensionNames.bind(automation);
```

NTI:
```
Namespaces are removed from scopes after finalization
  Node(ASSIGN): Web/Common/Base/visokio/base/Bean.js:1211:0
visokio.base.Bean.__transformUnion = function(jsonValue, jsonConfig, unionTransformers, requiresTypeID) {
  Parent(EXPR_RESULT): Web/Common/Base/visokio/base/Bean.js:1211:0
visokio.base.Bean.__transformUnion = function(jsonValue, jsonConfig, unionTransformers, requiresTypeID) {

	at com.google.common.base.Preconditions.checkState(Preconditions.java:445)
	at com.google.javascript.jscomp.NTIScope.getDeclaration(NTIScope.java:611)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.lookupTypeByName(JSTypeCreatorFromJSDoc.java:454)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getNamedTypeHelper(JSTypeCreatorFromJSDoc.java:442)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeFromCommentHelper(JSTypeCreatorFromJSDoc.java:314)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.fillInFunTypeBuilder(JSTypeCreatorFromJSDoc.java:645)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getFunTypeHelper(JSTypeCreatorFromJSDoc.java:604)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeFromCommentHelper(JSTypeCreatorFromJSDoc.java:359)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getNominalTypeHelper(JSTypeCreatorFromJSDoc.java:560)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.lookupTypeByName(JSTypeCreatorFromJSDoc.java:475)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getNamedTypeHelper(JSTypeCreatorFromJSDoc.java:442)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeFromCommentHelper(JSTypeCreatorFromJSDoc.java:314)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeFromComment(JSTypeCreatorFromJSDoc.java:279)
	at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeOfCommentNode(JSTypeCreatorFromJSDoc.java:243)
	at com.google.javascript.jscomp.GlobalTypeInfo.createTypeFromCommentNode(GlobalTypeInfo.java:2569)
	at com.google.javascript.jscomp.ImplicitNullabilityCheck$2.visit(ImplicitNullabilityCheck.java:121)
	at com.google.javascript.jscomp.NodeUtil.visitPreOrder(NodeUtil.java:3905)
	at com.google.javascript.jscomp.ImplicitNullabilityCheck.visit(ImplicitNullabilityCheck.java:80)
	at com.google.javascript.jscomp.CombinedCompilerPass$CallbackWrapper.visitOrMaybeActivate(CombinedCompilerPass.java:123)
	at com.google.javascript.jscomp.CombinedCompilerPass.visit(CombinedCompilerPass.java:178)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:646)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:718)
```

The line referred to is:
``` javascript
/**
 * @param {*} jsonValue
 * @param {!visokio.base.Bean.JsonConfig} jsonConfig
 * @param {Array<function(?,visokio.base.Bean.JsonConfig):?>} unionTransformers 
 * @param {boolean} requiresTypeID 
 * @return {*}
 * @private
 */
visokio.base.Bean.__transformUnion = function(jsonValue, jsonConfig, unionTransformers, requiresTypeID) {
```
This is a closed-source codebase so all I can give you is above. If I get time I'll try to reproduce it in the debugger, but I don't think I will for a few weeks as I've got a holiday imminent.

I figure this relates to very recent commits by @aravind-pg in this area.

**Comment by brad4d** [comment] 2016-08-17 18:57
I'm seeing similar failures in our nightly build.
I'm looking for the cause now.

**Comment by aravind-pg** [comment] 2016-08-18 00:00
Thanks for the bug report! Fixes for both of these have landed internally and will be pushed by tomorrow.

**Closed** 2016-08-18 17:42 UTC

**Comment by supersteves** [comment] 2016-08-18 22:07
Confirmed. Latest tip is looking pretty good. Thanks!
