### ISSUE TITLE
@type doesn't work like @param

### ISSUE THREAD

**Issue by pauldraper** [google/closure-compiler#907] opened 2015-04-14 21:06 UTC
Perhaps there is a better title.

When type checking is enabled,

```javascript
/** @typedef {{a: (string|undefined), b: (number|undefined)}} */
var Foo;

/** @type {Foo} */
var foo = {};
```

produces

```
JSC_TYPE_MISMATCH: initializing variable
found   : {}
required: {a: (string|undefined), b: (number|undefined)} at line 5 character 10
var foo = {};
          ^
```

However, the following passes type checking:

```javascript
/** @typedef {{a: (string|undefined), b: (number|undefined)}} */
var Foo;

/** @param {Foo} foo */
function f(foo) {
}

f({});
```

**Comment by concavelenz** [comment] 2015-04-15 05:45
There are two kinds of record types in the type system: inferred and declared.   Inferred record types can be coerced into compatible declared record types, declared record types have invariant property types. In the first case the type of the object literal is declared, in the second the type of the object literal is inferred.  

I recently started an experiment to change the relationship of the record types to each other but the changes got out of hand and I've put the work aside.

**Comment by teppeis** [comment] 2015-07-13 10:22
related #126 "Add support for optional fields in record types"

**Comment by dimvar** [comment] 2015-08-06 21:04
Duplicate of #126

**Closed by dimvar** 2015-08-06 21:04 UTC
Labels: duplicate, Types
