### ISSUE TITLE
compiler crash when exception variabled use before def

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#348] opened 2014-04-29 20:29 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#611

**Comment by Dominator008** [comment] 2016-01-24 03:46
Can't reproduce with given code:
```javascript
var f = function(_functionName, _params) {
  var fun = Ab.Cd[_functionName];
  if (!$.isFunction(fun)) {
    console.error('Ab.Cd.' + _functionName + ' is not a function');
    throw e;  // line 988
  }
  try {
    fun.apply(null, _params);
  } catch (e) {
    console.error('Error executing Ab.Cd.' + _functionName + ': ' + e);
    throw e;
  }
};
```, closing.

**Closed by Dominator008** 2016-01-24 03:46 UTC
