### ISSUE TITLE
JSC_JS_MODULE_LOAD_WARNING / moduleLoad suppression is flaky with --js_module_root=project

### ISSUE THREAD

**Issue by vapier** [google/closure-compiler#3580] opened 2020-04-21 22:05 UTC
starting with the 20191027 release (20190929 and older have been fine), using `@suppress {moduleLoad}` has become flaky, and seems to be related to the use of `--js_module_root`.

note: i grok that the use of `--js_module_root` below might not be correct, but it shouldn't affect whether the `@suppress {moduleLoad}` attribute is respected.

here is a reduced testcase:
* package/js/test.js
```js
/**
 * @fileoverview asdf
 *
 * @suppress {moduleLoad}
 */
import {myfunc} from './foo.js';
myfunc();
```
* package/js/foo.js
```js
/**
 * @export
 * @return {number}
 */
export function myfunc() {
  return 1;
}
```

here are the runs showing it having inconsistent behavior:
```sh
$ closure-compiler --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20191027
Built on: 2019-10-30 03:56

$ closure-compiler --checks-only --js_module_root=project project/js/test.js 
js/test.js:6: ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "./foo.js"

1 error(s), 0 warning(s)

$ cd project
$ closure-compiler --checks-only --js_module_root=project js/test.js 
<works fine>
```

**Comment by rishipal** [comment] 2020-04-28 03:57
I don't see any direct changes related to `@suppress {moduleLoad}` since that release version v 20191027.  
Investigating.

To clarify, by inconsistent, did you mean that the failure you see happens only when run from outside the `project` dir, or did you mean the failure is intermittent and not always reproducible even from within the `project` dir?

**Comment by vapier** [comment] 2020-04-28 05:07
by inconsistent i mean whether i see the failure depends on my cwd and nothing else

**Comment by brad4d** [comment] 2020-04-30 17:31
Although I'm not sure of the right fix, I at least have a rough idea what's happening here, and I will try to explain.

1. The error in question is reported by `BrowserModuleResolver`.
2. It uses the form of `JSError.make` that does not provide an AST node for the error, because it doesn't have a Node to use.
3. The logic for finding suppressions is in `SuppressDocWarningsGuard`. It attempts to discover the AST node for the error, then looks for `@suppress` annotations that could suppress it. In this case it doesn't have one, so it attempts to find the script using the sourcename that *is* in the error object.
4. Unfortunately, the source name in the error isn't the the right one. It has had the module root stripped from the beginning of its path, so no AST node can be found, thus no suppression occurs. This is also why the error message doesn't point to the source code that is doing the input.
5. In the case where correct suppression occurs, it is because the JS module root didn't match the path to the file.

**Comment by brad4d** [comment] 2020-04-30 18:34
Correction to the above:

The source name is actually read from the `Node`, so it has the full path, but the lookup using the full path doesn't work. Seems like the map from path to script node is using the modified names.

**Comment by brad4d** [comment] 2020-04-30 19:37
Correction to the correction. :)

The  code path that reports the error does not get the source name from the Node.
Instead it comes from a ModulePath object.

https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/modules/ModuleMapCreator.java#L166

This might be fixed by pulling the correct path from the Node that is available at that point in the code, but I fear that might break something else.

**Comment by brad4d** [comment] 2020-04-30 23:20
I've created an internal change to fix this and sent it for testing and review.

**Closed** 2020-05-04 22:40 UTC
Labels: triage-done
