### ISSUE TITLE
type confusion

### ISSUE THREAD

**Issue by ray007** [google/closure-compiler#2943] opened 2018-05-22 13:12 UTC
I've converted the old js-code here from a bunch of files organized with global variables to common-js modules. While the compilation works fine, I get several warning where the compiler seems to have troubles matching type names.

I.e. my control base class in file `controls.js` has a method `getPage`:
```
/**
 * get page control containing this control
 * @returns {lwebPage}
 */
lwebControl.prototype.getPage = function() {
    if (!this._page) {
        this._page = this.owner.getPage();
    }
    return this._page;
};
```

In another file (`page_n_menu.js`) I have overriden the method in the page class:
```
/** @override */
lwebPage.prototype.getPage = function() {
    return this;
};
```

While this seemed straight forward to me, the compiler thinks differently:
```
loytec/page_n_menu.js:505: WARNING - inconsistent return type
found   : module$loytec$page_n_menu.default.lwebPage
required: (lwebPage|null)
        return this;
               ^^^^
```

It's not only a problem for declared return types, but also with parameter types:
```
loytec/device.js:3367: WARNING - actual parameter 1 of lwebProject$$module$loytec$device does not match formal parameter
found   : module$loytec$device.default.loytecDevice
required: (loytecDevice|null)
                var prj = new lwebProject(this, prjInfo);
                                          ^^^^
```

**Comment by ChadKillingsworth** [comment] 2018-05-22 13:52
This is a duplicate of #2936

**Comment by ray007** [comment] 2018-05-22 14:36
How is this a duplicate?
This is not a problem of null vs. not-null, but matching i.e. `lwebPage` to `module$loytec$page_n_menu.default.lwebPage`.

**Comment by ChadKillingsworth** [comment] 2018-05-22 14:38
Sorry I saw the `null` and it's so common I just stopped there.

Without a complete code sample, this will be difficult. But did you import `loytecDevice`?

`const loytecDevice = require('./loytec/device');`

**Comment by ray007** [comment] 2018-05-22 15:26
No, the `loytecDevice` is defined in this very file `device.js`.

But the `lwebProject` class is defined in its own file, and there I have a ```goog.forwardDeclare('loytecDevice');```
, otherwise I'd have a problem with circular dependency.
And the (reduced) definition of `lwebProject`:
```
/**
 * @constructor
 * @param {loytecDevice} device the device the project was loaded from
 * @param {Object} prjInfo
 */
var lwebProject = function(device, prjInfo) {
	this.device = device;
	this.init();
};
```

Same with the `lwebPage` problem above, which is a subclass of `lwebControl`...

**Comment by ChadKillingsworth** [comment] 2018-05-22 17:50
Forward declares don't help here. The symbol must be defined in the file via an import. For circular dependencies, you can use the following syntax:

```js
/** @type {./path/to/module/index.exportedSymbol} */
const foo;
```

Such an import though will only be valid for type information and it will not help the compiler properly order files or preserve them from being dropped.

**Comment by ray007** [comment] 2018-05-23 11:54
Almost. Replace `@type` with `@typedef` and `const` with `var` and it seems to work:
```Javascript
/** @typedef {./page_n_menu.lwebPage} */
var lwebPage;
```

Should get an entry in the F.A.Q. or wiki...

What is `goog.forwardDeclare()` for if not for this?

**Comment by ChadKillingsworth** [comment] 2018-05-23 12:14
goog.forwardDeclare does allow you to reference a type before it exists. However, it was designed for `goog.require/goog.provide/goog.module` type code. Module rewriting does not recognize that statement.

We've avoided adding the path type annotation to the wiki because it is a less than ideal solution. It's a huge foot gun. If you reference a file only in that way, the compiler will drop the file and your compilation will break.

I'd rather work on supporting circular references properly.

**Closed by ChadKillingsworth** 2018-05-23 12:14 UTC
