### ISSUE TITLE
Unable to control the return type of a generic function

### ISSUE THREAD

**Issue by hills** [google/closure-compiler#3965] opened 2022-06-30 16:50 UTC
I'm finding a position which leaves me without a way to control the return type of a generic function.

I minimised the test case as best I could, to a function and a class.

The compiler is perhaps being very smart, as it infers a value must always be "null" (this is not true in code, but is being inferred by the JSDoc). It then carries this forward into a ?string, seemingly ignoring any of my requests to cast to a wider type.

But in doing so it leaves me unable to use the value without violating later type checks.

If it's not a bug, is there a way I can cast my way out of this?

I did wonder if this is a limitation of generic functions, as if it was a class I would have type control at instantiation. But a function has no such control?

Thanks

```
java -jar closure-compiler-v20220502.jar -O ADVANCED test-tolerant.js
test-tolerant.js:46:10: WARNING - [JSC_TYPE_MISMATCH] initializing variable
found   : MyClass<null>
required: MyClass<(null|string)>
  46| const a = new MyClass(x);
                ^^^^^^^^^^^^^^
[...]
```

```
/**
 * @template Type
 * @param {*} value
 * @param {!function(*)} check
 * @param {Type} fallback
 * @return {Type}
 */

function tolerant(value, check, fallback) {
    if (check(value))
        return value;
    else
        return fallback;
}

/**
 * @template Type
 */

class MyClass {

    /**
     * @param {Type} v
     */

    constructor(v) {
        /** @private {Type} */
        this._value = v;

        console.log(v);
    }
}

const mystery = window['_unknown'];

/*
 * Compiler infers this is always null, so the type of x is not
 * "?string" but "null". Can't fulfil the assignment of a without a
 * warning.
 */

/** @const {?string} */
const x = tolerant(mystery, x => typeof(x) == 'string', null);

/** @const {!MyClass<?string>} */
const a = new MyClass(x);

/*
 * Since it looks like Type is inferred from input parameters (not the
 * return), cast it. Result is same as above.
 */

/** @const {?string} */
const y = tolerant(mystery, x => typeof(x) == 'string', /** ?string */ (null));

/** @const {!MyClass<?string>} */
const b = new MyClass(y);

/*
 * Check type checking is in play at all. Yes it is. This correctly
 * fails to compile the assignment of z, as the return type is
 * "!number"
 */

/** @const {?string} */
const z = tolerant(mystery, x => typeof(x) == 'string', 5);

/** @const {!MyClass<?string>} */
const c = new MyClass(z);
```

**Comment by frost-cy** [comment] 2022-07-01 22:11
The compiler is working as intended. 

The right way to cast it is with `@type`
`const y = tolerant(mystery, x => typeof(x) == 'string', /** @type ?string */ (null));`

**Comment by frost-cy** [comment] 2022-07-01 23:47
Feel free to ak questions in the discussions.

Closing this as it is not a bug.

**Comment by frost-cy** [comment] 2022-07-01 23:48
Feel free to ak questions in the discussions.

Closing this as it is not a bug.

**Closed by frost-cy** 2022-07-01 23:48 UTC

**Comment by hills** [comment] 2022-07-05 16:04
Ok great, just an elementary mistake. Thanks and apologies for the spurious bug report.
