### ISSUE TITLE
Cannot express function types that have additional properties

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#282] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#899

**Comment by Dominator008** [comment] 2016-04-22 00:15
I'd say this is a duplicate of https://github.com/google/closure-compiler/issues/946

**Closed by Dominator008** 2016-04-22 00:15 UTC
Labels: duplicate
