### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#829] opened 2015-02-18 03:59 UTC
I'm reporting this error as requested.

```
0 error(s), 259 warning(s)
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Null declared type@GETPROP 255 [source_file: src/lab/view/test/LabCanvas_test.js]
In scope: testLabCanvas1() with root: FUNCTION  180 [source_file: src/lab/view/test/LabCanvas_test.js]
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
	at com.google.javascript.jscomp.NewTypeInference.getDeclaredTypeOfQname(NewTypeInference.java:3281)
	at com.google.javascript.jscomp.NewTypeInference.getDeclaredTypeOfQname(NewTypeInference.java:3277)
	at com.google.javascript.jscomp.NewTypeInference.analyzeAssignBwd(NewTypeInference.java:2891)
	at com.google.javascript.jscomp.NewTypeInference.analyzeExprBwd(NewTypeInference.java:2720)
	at com.google.javascript.jscomp.NewTypeInference.analyzeFunctionBwd(NewTypeInference.java:653)
	at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:618)
	at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:308)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:845)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:758)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:96)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:701)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException: Null declared type@GETPROP 255 [source_file: src/lab/view/test/LabCanvas_test.js]
	... 20 more
make: *** [build/test/UnitTest_en.js] Error 254
make: *** Deleting file `build/test/UnitTest_en.js'
```

compiler version
```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150126-82-g85da5b6
Built on: 2015/02/11 20:55
```

The following is the compile command showing options.  The shell variables are set earlier in the script.
```
$CLOSURE_COMPILER \
--only_closure_dependencies \
--js=src/ \
--js=$CLOSURE_LIBRARY \
--compilation_level=$comp_level \
--generate_exports \
--jscomp_error=checkTypes \
--jscomp_error=missingProperties \
--jscomp_error=missingProvide \
--jscomp_error=missingRequire \
--jscomp_warning=accessControls \
--jscomp_warning=ambiguousFunctionDecl \
--jscomp_warning=checkVars \
--jscomp_warning=const \
--jscomp_warning=constantProperty \
--jscomp_warning=fileoverviewTags \
--jscomp_warning=invalidCasts \
--jscomp_warning=missingReturn \
--jscomp_warning=newCheckTypes \
--jscomp_warning=strictModuleDepCheck \
--jscomp_warning=suspiciousCode \
--jscomp_warning=typeInvalidation \
--jscomp_warning=undefinedNames \
--jscomp_warning=undefinedVars \
--jscomp_warning=unknownDefines \
--extra_annotation_name=alias \
--warning_level=VERBOSE \
--define=myphysicslab.lab.util.UtilityCore.ADVANCED=$advanced \
--define=goog.DEBUG=$debug \
--define=goog.LOCALE="'$locale'" \
--language_in=ECMASCRIPT5 \
--new_type_inf \
--closure_entry_point=myphysicslab.lab.engine2D.test.RigidBodySim_test \
--closure_entry_point=myphysicslab.lab.engine2D.test.Polygon_test \
--closure_entry_point=myphysicslab.lab.engine2D.test.StraightEdge_test \
--closure_entry_point=myphysicslab.lab.engine2D.test.CircularEdge_test \
--closure_entry_point=myphysicslab.lab.engine2D.test.Vertex_test \
--closure_entry_point=myphysicslab.lab.engine2D.test.UtilEngine_test \
--closure_entry_point=myphysicslab.lab.graph.test.CircularList_test \
--closure_entry_point=myphysicslab.lab.model.test.AbstractSimObject_test \
--closure_entry_point=myphysicslab.lab.model.test.EnergyInfo_test \
--closure_entry_point=myphysicslab.lab.model.test.PhysicsLine_test \
--closure_entry_point=myphysicslab.lab.model.test.PhysicsPath_test \
--closure_entry_point=myphysicslab.lab.model.test.PhysicsPoint_test \
--closure_entry_point=myphysicslab.lab.model.test.PhysicsSpring_test \
--closure_entry_point=myphysicslab.lab.model.test.SimListStandard_test \
--closure_entry_point=myphysicslab.lab.model.test.VarsArrayStandard_test \
--closure_entry_point=myphysicslab.lab.util.test.ConcreteSubject_test \
--closure_entry_point=myphysicslab.lab.util.test.DoubleMath_test \
--closure_entry_point=myphysicslab.lab.util.test.DoubleRect_test \
--closure_entry_point=myphysicslab.lab.util.test.MutableVector_test \
--closure_entry_point=myphysicslab.lab.util.test.ParameterBoolean_test \
--closure_entry_point=myphysicslab.lab.util.test.ParameterDouble_test \
--closure_entry_point=myphysicslab.lab.util.test.ParameterString_test \
--closure_entry_point=myphysicslab.lab.util.test.RandomLCG_test \
--closure_entry_point=myphysicslab.lab.util.test.Terminal_test \
--closure_entry_point=myphysicslab.lab.util.test.TimerClock_test \
--closure_entry_point=myphysicslab.lab.util.test.UniqueNames_test \
--closure_entry_point=myphysicslab.lab.util.test.UtilityCore_test \
--closure_entry_point=myphysicslab.lab.util.test.Vector_test \
--closure_entry_point=myphysicslab.lab.util.test.AffineTransform_test \
--closure_entry_point=myphysicslab.lab.view.test.CoordMap_test \
--closure_entry_point=myphysicslab.lab.view.test.DisplayShape_test \
--closure_entry_point=myphysicslab.lab.view.test.DisplaySpring_test \
--closure_entry_point=myphysicslab.lab.view.test.LabCanvas_test \
--closure_entry_point=myphysicslab.lab.view.test.ScreenRect_test \
--closure_entry_point=myphysicslab.lab.view.test.SimView_test \
--closure_entry_point=myphysicslab.sims.mechanics.test.Spring1_test \
--closure_entry_point=myphysicslab.sims.mechanics.test.DoublePendulum_test \
--closure_entry_point=myphysicslab.sims.roller.test.Roller_test \
> $target
```

**Comment by dimvar** [comment] 2015-05-06 20:24
What's the code to compile to reproduce this? We have changed how we do declarations, so there is a good chance this is fixed now.

**Comment by dimvar** [comment] 2015-05-20 22:22
Closing this because it's impossible to repro as is. If you can provide repro steps, let us know.

**Closed by dimvar** 2015-05-20 22:22 UTC
Labels: bug, NTI, P3

**Comment by myphysicslab** [comment] 2015-05-21 20:01
This is now fixed.  This is a set of unit-tests. The crash happened from turning on the new_type_inf flag.  But after updating to new compiler it no longer crashes.
