### ISSUE TITLE
Compiler crashed on using a catch parameter outside catch block

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#194] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1162

**Comment by Dominator008** [comment] 2016-01-23 16:24
Can't reproduce with given code:
```javascript
try {
} catch (x_15) {
} finally {
}
var a = x_15;
```
, closing.

**Closed by Dominator008** 2016-01-23 16:24 UTC
