### ISSUE TITLE
Destructuring doesn't work with await expression

### ISSUE THREAD

**Issue by b-strauss** [google/closure-compiler#2595] opened 2017-08-02 10:27 UTC
```
JSC_CANNOT_CONVERT: This code cannot be converted from ES6. Undecomposable expression at line 3 character 18
  const [first] = await Promise.all(['first', 'second']);
                  ^
```

This doesn't work ([link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540language_in%2520ECMASCRIPT_2017%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5_STRICT%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aasync%2520function%2520run()%2520%257B%250A%2520%2520const%2520%255Bfirst%255D%2520%253D%2520await%2520Promise.all(%255B'first'%252C%2520'second'%255D)%253B%250A%2520%2520return%2520first%253B%250A%257D%250A%250Arun().then(first%2520%253D%253E%2520console.log(first))%253B)):

```javascript
async function run() {
  const [first] = await Promise.all(['first', 'second']);
  return first;
}

run().then(first => console.log(first));
```

This works ([link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540language_in%2520ECMASCRIPT_2017%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5_STRICT%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aasync%2520function%2520run()%2520%257B%250A%2520%2520const%2520array%2520%253D%2520await%2520Promise.all(%255B'first'%252C%2520'second'%255D)%253B%250A%2520%2520const%2520%255Bfirst%255D%2520%253D%2520array%253B%250A%2520%2520return%2520first%253B%250A%257D%250A%250Arun().then(first%2520%253D%253E%2520console.log(first))%253B)):

```javascript
async function run() {
  const array = await Promise.all(['first', 'second']);
  const [first] = array;
  return first;
}

run().then(first => console.log(first));
```

Probably related: #2330

**Comment by shicks** [comment] 2017-08-10 18:40
Sorry it's taken so long to address this - was sort of hoping somebody else would pick it up.

There are three transpilations happening here: async-await, destructuring, and then finally generators (in that order).  After async-await and destructuring, we end up with:

```js
var a = $jscomp.makeIterator(yield Promise.all(["first", "second"])), first = a.next().value;
```

In order to transpile this, the RHS needs to be decomposed - specifically, I believe the `$jscomp.makeIterator(...)` expression needs to be "moved" to a separate variable that can be called after the yield returns.  According to `ExpressionDecomposer` [1], the condition for this is as follows

> A subexpression is MOVABLE if it can be replaced with a temporary holding its results and moved to immediately before the root of the expression.
> There are three conditions that must be met for this to occur:
> 1. There must be a location to inject a statement for the expression.  For example, this condition can not be met if the expression is a loop condition or CASE condition.
> 2. If the expression can be affected by side-effects, there can not be a side-effect between original location and the expression root.
> 3. If the expression has side-effects, there can not be any other expression that can be affected between the original location and the expression root.

It looks like the issue is maybe (2), though I'm a little shaky on the exact details here.  The expression `$jscomp.makeIterator` *can* be affected by side-effects, and there's no guarantee that there are no side effects while yielding.  To further investigate, I [simplified][2] the expression quite a bit:

```js
/** @const */
var x = x || {};

/** @const */
x.makeIterator = function(arg) { return arg; }

function* f() {
  var a = x.makeIterator(yield);
}
```

This code still fails to transpile with the same error.  (It's worth nothing that `$jscomp.makeIterator` isn't actually declared as `@const` - not sure if this matters, or if the compiler can infer that it is effectively const; either way, I did it with `x.makeIterator` and still got the error, so maybe it's irrelevant).  If I change `makeIterator` to a simple function, rather than a qualified name, then it works fine, presumably because it was the GETPROP that "can be affected by side effects".

I don't understand why the compiler doesn't recognize that this is never reassigned, and therefore is actually not affected.  And I think we still have some significant issues with generator transpilation, since (as far as I can tell) other transpilers seem to be more permissive here - maybe this should be a suppressible warning, rather than an error?  In any case, it seems like a quick fix would be to change how destructuring is rewritten, to save `$jscomp.makeIterator` into a temporary variable in a separate statement (or possible the root of the function) before calling it.  That would at least fix this unfortunate interaction.

[1]: https://github.com/google/closure-compiler/blob/a4cb49131c9db49227f188f9ee25d418f82e3bd3/src/com/google/javascript/jscomp/ExpressionDecomposer.java#L699
[2]: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540const%2520*%252F%250Avar%2520x%2520%253D%2520x%2520%257C%257C%2520%257B%257D%253B%250A%250A%252F**%2520%2540const%2520*%252F%250Ax.makeIterator%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%253B%2520%257D%250A%250Afunction*%2520f()%2520%257B%250A%2520%2520var%2520a%2520%253D%2520x.makeIterator(yield)%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by shicks** [comment] 2017-08-10 18:46
cc @brad4d

**Comment by stevendwood** [comment] 2018-03-31 15:32
Although it complains - if the compiler is embedded and you use setContinueAfterErrors(true) on the CompilerOptions it will generate the code anyway.  I think if you are using a newer version of the compiler than me you can just use setAllowMethodCallDecomposing(true) and it should work I think ?

**Comment by brad4d** [comment] 2018-04-18 04:28
@shicks thanks for the excellent analysis
@stevendwood I believe you are right that doing `setAllowMethodCallDecomposing(true)` will allow this code to compile.
We can probably move toward allowing method decomposition by default.
The only reason we don't do that now is to avoid a bug in old versions of IE where some methods didn't actually have the `apply` method on them. Mainly DOM object methods, I believe.

**Comment by lauraharker** [comment] 2019-04-11 18:33
Method call decomposition is always on as of v20190301, so we can close this.

**Closed by lauraharker** 2019-04-11 18:33 UTC

**Comment by princed** [comment] 2019-07-11 06:37
@lauraharker The [link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540language_in%2520ECMASCRIPT_2017%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5_STRICT%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aasync%2520function%2520run()%2520%257B%250A%2520%2520const%2520%255Bfirst%255D%2520%253D%2520await%2520Promise.all(%255B'first'%252C%2520'second'%255D)%253B%250A%2520%2520return%2520first%253B%250A%257D%250A%250Arun().then(first%2520%253D%253E%2520console.log(first))%253B) in the issue description still produces the following warning in ADVANCED mode:

```
JSC_UNSAFE_NAMESPACE: incomplete alias created for namespace $jscomp, possibly due to await/yield transpilation.
See https://github.com/google/closure-compiler/wiki/FAQ#i-got-an-incomplete-alias-created-for-namespace-error--what-do-i-do for more details. at line 3 character 8
  const [first] = await Promise.all(['first', 'second']);
```

The FAQ by the link in the warning mentions that: 
> Unfortunately, under some circumstances, this generated code runs into the same issue with property flattening described above. If the compiler is unable to replace tmpGoogAsserts.assertString with goog.asserts.assertString, it cannot safely flatten your code.

However it doesn't describe those circumstances exactly. 
So I imagine that in some enviroments this warning can be safely supressed.

Could you please clarify circustances when it's safe or no safe to ignore the warning?

**Comment by lauraharker** [comment] 2019-07-11 17:45
In this particular case it is safe to ignore the warning. In general, you should pay attention to the warning if you are accessing a constructor or class off of an aliased namespace, or aliasing a constructor.

Here's a snippet of the generated code that's triggering the warning ([source](https://closure-compiler-debugger.appspot.com/#input0%3Dasync%2520function%2520run()%2520%257B%250A%2520%2520const%2520%255Bfirst%255D%2520%253D%2520await%2520Promise.all(%255B'first'%252C%2520'second'%255D)%253B%250A%2520%2520return%2520first%253B%250A%257D%250A%250Arun().then(first%2520%253D%253E%2520console.log(first))%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)):

``` js
    if ($jscomp$generator$context.nextAddress == 1) {
      JSCompiler_temp_const = $jscomp;
      JSCompiler_temp_const$jscomp$1 = JSCompiler_temp_const.makeIterator;
      return $jscomp$generator$context.yield(Promise.all(["first", "second"]), 2);
    }
    $jscomp$destructuring$var0 = JSCompiler_temp_const$jscomp$1.call(JSCompiler_temp_const, $jscomp$generator$context.yieldResult);
```

The compiler is warning you that `JSCompiler_temp_const = $jscomp;` may be unsafe.

In this case, it's actually safe. The only usage of `JSCompiler_temp_const` is to access `JSCompiler_temp_const.makeIterator`, and the compiler will not unsafely flatten `$jscomp.makeIterator` because it is not an enum or constructor.

Note: I might have missed a few edge cases since the property flattening logic is generally confusing. I filed https://github.com/google/closure-compiler/issues/3428 to avoid false positives like this one.
