### ISSUE TITLE
Unexpected variable compile time exception

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#328] opened 2014-04-29 20:29 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#707

**Comment by Dominator008** [comment] 2016-01-24 03:54
Can't reproduce with given code:
```javascript
try { } catch (e) { }
res.map(function(r) {
  if (e = r != null ? r.error : void 0) {
  }
});
```
, closing this.

**Closed by Dominator008** 2016-01-24 03:54 UTC
