### ISSUE TITLE
ES6 export .. from leads to an error

### ISSUE THREAD

**Issue by 2beers** [google/closure-compiler#1886] opened 2016-07-10 09:58 UTC
Hello. Initially I thought I created my js code in a way that lead to a circular dependency, so I submitted this issue : https://github.com/google/closure-compiler/issues/1883 
Now I double checked my code and it appears that I didn't, but I think the compiler acts like it is.
Here is a simplified version of my code:
```
// a.js
export class A{
	constructor(){
		console.log("A");
	}
}


// b.js
import {C} from 'c';
export class B{
	constructor(){
		console.log("B");
		new C();
	}
}


// c.js
import {A} from 'ab';
export class C{
	constructor(){
		console.log("C");
		new A();
	}
}


// ab.js
export {A} from 'a';
export {B} from 'b';


// main.js
import {B} from 'b';
new B();
```

produce the following error:

> SEVERE: js/c.js:1: ERROR - required "module$ab" namespace not provided yet
> import {A} from 'ab';

**This is definitely not a circular depency** .

> B ---> C ---> A(from ab)

if I change the `import {A} from 'ab';` to `import {A} from 'a';` it's working

I think this is a common situation. From what I've seen , lots of libraries export multiple modules(different files) from a single file using `export { name1, name2, …, nameN } from …;` syntax

Thanks

**Comment by concavelenz** [comment] 2016-07-11 20:21
B -> C -> AB -> B  is a circular dependency. Did you mean something else?

**Comment by 2beers** [comment] 2016-07-12 00:45
@concavelenz You might be right, depends on your point of view.
For me `import {A} from 'ab';` means I'm only interested in A class from a.js and I think this should be equivalent to `import {A} from 'a';`
`export {B} from 'b';` should be ignored in this case.

Is ES6 import works differently ?

**Comment by ChadKillingsworth** [comment] 2016-07-12 01:40
ES6 imports are statically included. They are not evaluated in a lazy fashion. This is indeed another circular dependency and thus a duplicate of #1883.

**Closed by ChadKillingsworth** 2016-07-12 01:40 UTC
Labels: bug, ES6
