### ISSUE TITLE
Essential code is removed from function body

### ISSUE THREAD

**Issue by dmitrysteblyuk** [google/closure-compiler#2555] opened 2017-06-30 15:47 UTC
So basically this:

```js
const w = typeof window == 'object' ? window : {};
const _FormData = w['FormData'];
function isFormData(d) {
    return d instanceof _FormData;
}
window.isFormData = isFormData;

```
Compiles to this:
```js
window.a=function(){return!1};
```

Compiler options:
```
--compilation_level=ADVANCED_OPTIMIZATIONS
--language_in=ES6
--language_out=ES5

./test.js
--js_output_file=./dist/test.js
--entry_point=./test

```

**Comment by MatrixFrog** [comment] 2017-06-30 16:11
This looks the same as this internal report: b/37975351 which says it was fixed by c3f5e9a5713cdd9af9283e75c309e5d831f1b45e

**Comment by dmitrysteblyuk** [comment] 2017-07-01 06:16
@MatrixFrog I downloaded the most recent version (20170626). The internally reported issue ```const Foo = window['Foo'] || ...``` is fixed alright. Mine's still there.

**Comment by Dominator008** [comment] 2017-07-05 17:08
@dmitrysteblyuk You mean your issue is still there. i.e. the code missing?

**Comment by dmitrysteblyuk** [comment] 2017-07-05 17:31
@Dominator008 sorry for not being explicit. Yes, last time I checked (v20170626) the issue was not fixed.

**Comment by brad4d** [comment] 2017-07-07 21:48
`--print_source_after_each_pass` shows that `smartNamePass` is removing it.

```
// earlyInlineVariables yields:
// ************************************
/** @const @constructor */ var _FormData = (typeof window == "object" ? window : {})["FormData"];
window.isFormData = function isFormData(d) {
  return d instanceof _FormData;
};

// ************************************

// smartNamePass yields:
// ************************************
window.isFormData = function isFormData(d) {
  return false;
};

// ************************************
```

**Comment by brad4d** [comment] 2017-07-10 21:57
Imported and sent for internal review

**Comment by brad4d** [comment] 2017-07-10 22:06
sorry, disregard that last. It was intended for pr #2554

**Comment by lauraharker** [comment] 2018-12-06 01:56
This is fixed, probably by Bradford getting rid of SmartNamePass.

Original repro now compiles to
```
var b=("object"==typeof window?window:{}).FormData;window.a=function(c){return c instanceof b};
```

**Closed by lauraharker** 2018-12-06 01:56 UTC
