### ISSUE TITLE
Argument default value lost when changing scope

### ISSUE THREAD

**Issue by morille** [google/closure-compiler#3664] opened 2020-08-24 08:40 UTC
When an optional argument is annotated to be part of an enum `@param {!MY_ENUM=} myEnumValue`, and has a default value `myFunction(myEnumValue = MY_ENUM.DEFAULT)`, the value of the argument is correctly inferred as `!MY_ENUM` until it is passed to another scope, like an inline function, setTimeout, etc. Then the compiler complains that the value is `!MY_ENUM|undefined`.

Here is the code for reproducing the warning. You may need to re-check the "advanced" radio box before compiling:
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540enum%250A%2520*%252F%250Aconst%2520NUMBERS%2520%253D%2520%257B%250A%2520%2520ZERO%253A%25200%252C%250A%2509ONE%253A%25201%252C%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!NUMBERS%253D%257D%2520number%250A%2520*%252F%250Afunction%2520logNumber(number%2520%253D%2520NUMBERS.ZERO)%2520%257B%250A%2520%2520(()%2520%253D%253E%2520%257B%250A%2520%2520%2520doLogNumber(number)%253B%250A%2520%2520%257D)()%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!NUMBERS%257D%2520number%250A%2520*%252F%250Afunction%2520doLogNumber(number)%250A%257B%250A%2520%2520console.log(number)%253B%250A%257D%250A%250AlogNumber()%253B%250AlogNumber(NUMBERS.ONE)%253B%250A

**Comment by lauraharker** [comment] 2020-08-26 21:52
Duplicate of https://github.com/google/closure-compiler/issues/3327.

**Closed by lauraharker** 2020-08-26 21:52 UTC
