### ISSUE TITLE
[FEATURE] Support spread operator

### ISSUE THREAD

**Issue by dtruffaut** [google/closure-compiler#2777] opened 2018-01-07 23:14 UTC
## Support spread operator

**Code sample**
```
let o = {};
o = { ...o['a'], 'b': 'b' }
```

**Current result**
```
ERROR - Parse error. \'}\' expected\n  // ...\r\n      ^\n\r\n1 error(s), 0 warning(s)\n
```

**Expected result**
```
{b: "b"}
```

**Additional info**
- v20170910
- 'java -d64 -jar "C:\\Program Files\\nodejs\\my_project\\node_modules\\google-closure-compiler\\compiler.jar" --js ......................  --compilation_level ADVANCED --language_in ECMASCRIPT_2017 --language_out ECMASCRIPT_2017 --warning_level VERBOSE

**Comment by ChadKillingsworth** [comment] 2018-01-07 23:15
Duplicate of #2303

**Closed by ChadKillingsworth** 2018-01-07 23:15 UTC
