### ISSUE TITLE
weird warning with object enums in new type inference

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#1257] opened 2015-11-17 17:52 UTC
```
/** @constructor **/ function Foo() {}
/** @enum {Foo} **/
var Fooze = {ONE: new Foo(), TWO: new Foo()}
```

Old type inference accepts this without problems. New type inference complains:
```
input0:2: WARNING - An enum type cannot be a union type
/** @enum {Foo} **/
```

It would be nice if enum declarations automatically assumed non-null (as `@extends` declarations do).

**Comment by nicks** [comment] 2015-11-17 17:52
debugger link:
http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520**%252F%2520function%2520Foo()%2520%257B%257D%250A%252F**%2520%2540enum%2520%257BFoo%257D%2520**%252F%250Avar%2520Fooze%2520%253D%2520%257BONE%253A%2520new%2520Foo()%252C%2520TWO%253A%2520new%2520Foo()%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26MISSING_PROPERTIES%3D1

**Comment by dimvar** [comment] 2015-11-17 17:57
Duplicate of #755

**Closed by dimvar** 2015-11-17 17:57 UTC

**Comment by nicks** [comment] 2015-11-17 18:05
lol

**Comment by dimvar** [comment] 2015-11-17 18:07
you are very consistent ;)
