### ISSUE TITLE
Javascript "for of" bug with "FormData"

### ISSUE THREAD

**Issue by jplevene** [google/closure-compiler#3856] opened 2021-08-31 20:57 UTC
Compiling the following JavaScript code goes really wrong as it doesn't understand what `for (var pair of formdata.entries())` is, even in "Remove whitespace" mode:

```
var formdata = new FormData();

for (var pair of formdata.entries())
{
	console.log(pair[0], pair[1]);
}
```
It really messes up the code and causes JS errors that crash the code and produces this bug ridden monstrosity for "Whitespace":

`var formdata=new FormData;for(var $jscomp$iter$0=$jscomp.makeIterator(formdata.entries()),$jscomp$key$pair=$jscomp$iter$0.next();!$jscomp$key$pair.done;$jscomp$key$pair=$jscomp$iter$0.next()){var pair=$jscomp$key$pair.value;{console.log(pair[0],pair[1])}};`

And even worse for "Simple":

```
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
for(var formdata=new FormData,$jscomp$iter$0=$jscomp.makeIterator(formdata.entries()),$jscomp$key$pair=$jscomp$iter$0.next();!$jscomp$key$pair.done;$jscomp$key$pair=$jscomp$iter$0.next()){var pair=$jscomp$key$pair.value;console.log(pair[0],pair[1])};
```
"Advanced" was also buggy

`function a(){var d=b,e=0;return function(){return e<d.length?{done:!1,value:d[e++]}:{done:!0}}}var c,b=(new FormData).entries(),f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];c=f?f.call(b):{next:a()};for(var g=c.next();!g.done;g=c.next()){var h=g.value;console.log(h[0],h[1])};`

It **should** return "Whitespace" as:

`var formdata=new FormData;for(var pair of formdata.entries()){console.log(pair[0], pair[1])}`

**Comment by lauraharker** [comment] 2021-09-01 18:16
"Whitespace" mode output crashing is a known issue: see https://github.com/google/closure-compiler/issues/2007 and https://github.com/google/closure-compiler/issues/3637. Passing `--language_out=NO_TRANSPILE` should fix this.

For "simple" and "advanced" modes, you may also disable for-of loop transpilation with `--language_out=NO_TRANSPILE` or any other language mode documented in https://github.com/google/closure-compiler/issues/3637. The compiler defaults are set to transpile ES2015+ features like for-of down to ES5.

The transpiled output looks correct to me though. Did you find a bug in the output (i.e. the output code behaves differently than the input)?

**Comment by jplevene** [comment] 2021-09-01 18:30
Yes, the output code crashed, something about $jscomp, I can't remember exactly.

**Comment by lauraharker** [comment] 2021-09-01 20:17
Hmm, I can't reproduce a crash in "simple" or "advanced" mode. Running both snippets of JS from https://github.com/google/closure-compiler/issues/3856#issue-984312347 in the console runs w/o crashing for me.

I agree the "whitespace" output is buggy and can reproduce the "$jscomp" crash there.

**Comment by jplevene** [comment] 2021-09-02 18:14
Sorry, I meant just the Whitespace code crashed.

**Comment by lauraharker** [comment] 2021-09-03 17:42
I see, in that case I'll close this bug as a duplicate of https://github.com/google/closure-compiler/issues/2007. Please file a new issue if you run into issues with "simple"/"advanced" mode.

**Comment by blickly** [comment] 2021-11-03 00:22
The whitespace issue seems to be a duplciate of #2007 (where the default transpilation generates references to transpilation helper code that is not included).  The workaround is to run with `--language_out=NO_TRANSPILE` or `--language_out=ECMASCRIPT_NEXT`.  In fact, we might consider changing the default language out to one of those, as it may be a bit surprising that the default behavior is to transpile down to ES5.

@jplevene. was there a separate issue with `SIMPLE`/`ADVANCED`? The output code appears to execute correctly in those modes...

**Closed** 2021-11-05 20:07 UTC
