### ISSUE TITLE
No type checking on await expression values

### ISSUE THREAD

**Issue by jplaisted** [google/closure-compiler#2540] opened 2017-06-19 20:29 UTC
There is no type checking on the implicit results of an await expression. To me this seems different than issue #2191.

```
/** @param {string} arg */
function strFn(arg) {}

async function asyncFn() {
  const v = await Promise.resolve(5);
  strFn(v); // Ignored
}

function callbackFn() {
  Promise.resolve(5).then(strFn); // WARNING
}
```

[Debug link](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language%2520ECMASCRIPT8%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%2520%2540param%2520%257Bstring%257D%2520arg%2520*%252F%250Afunction%2520strFn(arg)%2520%257B%257D%250A%250Aasync%2520function%2520asyncFn()%2520%257B%250A%2520%2520const%2520v%2520%253D%2520await%2520Promise.resolve(5)%253B%250A%2520%2520strFn(v)%253B%2520%252F%252F%2520no%2520error%250A%257D%250A%250Afunction%2520callbackFn()%2520%257B%250A%2520%2520Promise.resolve(5).then(strFn)%253B%2520%252F%252F%2520error%250A%257D%250A%250A)

I assume type checking is done post-transpilation in which case there needs to be casts within each generator switch statement. There is no type safety on the argument to the generator is the fundamental issue here.

[Debug link to the above example with casting.](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language%2520ECMASCRIPT8%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520Required%2520to%2520get%2520async%2520transpile%2520definitions%250Aasync%2520function%2520foo()%2520%257B%257D%250A%250A%252F**%2520%2540param%2520%257Bstring%257D%2520arg%2520*%252F%250Afunction%2520strFn(arg)%2520%257B%250A%257D%250Afunction%2520asyncFn()%2520%257B%250A%2520%2520function%2520%2524jscomp%2524async%2524generator()%2520%257B%250A%2520%2520%2520%2520var%2520%2524jscomp%2524generator%2524state%2520%253D%25200%253B%250A%2520%2520%2520%2520var%2520v%253B%250A%2520%2520%2520%2520var%2520%2524jscomp%2524generator%2524next%2524arg0%253B%250A%2520%2520%2520%2520function%2520%2524jscomp%2524generator%2524impl(%2524jscomp%2524generator%2524next%2524arg%252C%2520%2524jscomp%2524generator%2524throw%2524arg)%2520%257B%250A%2520%2520%2520%2520%2520%2520while%2520(1)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520switch(%2524jscomp%2524generator%2524state)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520case%25200%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2524jscomp%2524generator%2524state%2520%253D%25201%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520%257Bvalue%253APromise.resolve(5)%252C%2520done%253Afalse%257D%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520case%25201%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520if%2520(!(%2524jscomp%2524generator%2524throw%2524arg%2520!%253D%253D%2520undefined))%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2524jscomp%2524generator%2524state%2520%253D%25202%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520break%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2524jscomp%2524generator%2524state%2520%253D%2520-1%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520throw%2520%2524jscomp%2524generator%2524throw%2524arg%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520case%25202%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2524jscomp%2524generator%2524next%2524arg0%2520%253D%2520%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%2520(%2524jscomp%2524generator%2524next%2524arg)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520v%2520%253D%2520%2524jscomp%2524generator%2524next%2524arg0%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520strFn(v)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2524jscomp%2524generator%2524state%2520%253D%2520-1%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520default%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520%257Bvalue%253Aundefined%252C%2520done%253Atrue%257D%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520var%2520iterator%2520%253D%2520%257Bnext%253Afunction(arg)%2520%257B%250A%2520%2520%2520%2520%2520%2520return%2520%2524jscomp%2524generator%2524impl(arg%252C%2520undefined)%253B%250A%2520%2520%2520%2520%257D%252C%2520%2522throw%2522%253Afunction(arg)%2520%257B%250A%2520%2520%2520%2520%2520%2520return%2520%2524jscomp%2524generator%2524impl(undefined%252C%2520arg)%253B%250A%2520%2520%2520%2520%257D%252C%2520%2522return%2522%253Afunction(arg)%2520%257B%250A%2520%2520%2520%2520%2520%2520throw%2520Error(%2522Not%2520yet%2520implemented%2522)%253B%250A%2520%2520%2520%2520%257D%257D%253B%250A%2520%2520%2520%2520%2524jscomp.initSymbolIterator()%253B%250A%2520%2520%2520%2520iterator%255BSymbol.iterator%255D%2520%253D%2520function()%2520%257B%250A%2520%2520%2520%2520%2520%2520return%2520this%253B%250A%2520%2520%2520%2520%257D%253B%250A%2520%2520%2520%2520return%2520iterator%253B%250A%2520%2520%257D%250A%2520%2520return%2520%2524jscomp.executeAsyncGenerator(%2524jscomp%2524async%2524generator())%253B%250A%257D%250A%253B%250A)

**Comment by shicks** [comment] 2017-06-19 23:13
@jplaisted Would you be up for digging through the async rewrite pass to see if you can insert those cast nodes where appropriate?

@brad4d Can you point John in the right direction?

**Comment by jplaisted** [comment] 2017-06-20 01:55
I'd be more than happy to tackle this one!

**Comment by brad4d** [comment] 2017-06-20 15:48
Async functions are built on top of generator functions, and the core of the problem is going to be in how they are transpiled.

https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/Es6RewriteGenerators.java

I am aware of a handful of bugs with this pass, most of them related to type information. I want to spend some time really figuring out how it works and where it needs fixing, but I've been busy with higher priority things.

@jplaisted if you'd like to dig into that pass and improve the typing with a pull request or two, I will be absolutely delighted to shepherd them in.

**Comment by jplaisted** [comment] 2017-06-21 17:08
Updating title to reflect this is an actually an issue with generators. Example in OP can be rewritten:

```
/** @param {string} arg */
function strFn(arg) {}

function *asyncFn() {
  const v = yield 5;
  strFn(v); // Ignored
}
```

**Comment by jplaisted** [comment] 2017-07-10 21:01
We discussed this and it isn't a trivial task in the rewrite async / generators since type checking is done post transpilation. Difficult to get the type of the expression both pre- and post- transpiltation as a result.

**Comment by chrismiddleton** [comment] 2018-11-20 03:05
I'm not sure if this is the same issue, but when I test with the current compiler, there is no type checking on await expressions. Example here:

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540return%2520%257BPromise%253CString%253E!%257D%250A**%252F%250Aasync%2520function%2520hello()%2520%257B%250A%2520%2520return%2520Promise.resolve(2)%253B%250A%257D%250A%250Aasync%2520function%2520run%2520()%2520%257B%250A%2520%2520var%2520result%2520%253D%2520await%2520hello()%253B%250A%2520%2520alert(result.slice(0%252C%25205))%253B%250A%257D%250A%250Aasync%2520function%2520run2%2520()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250A%2520%2520var%2520result2%2520%253D%2520await%2520hello()%253B%250A%2520%2520alert(result2.slice(0%252C%25205))%253B%250A%257D%250A%250Arun()%253B%250Arun2()%253B%250A

I think it would be a good idea to put a big warning about the lack of type-checking for async/await, since this feature has been missing for so long so as to qualify as a bug that everyone should know about.

I was on a project that used async/await and this lack of type checking was not obvious to us, and we had a few cases where bugs that made it to the end-user were caused by this lack of type checking.

I'd almost rather have not used async/await at all or at least *known* that the type-checking was absent, because you write code differently when you think the compiler is checking for you. When you refactor code and you fix all the type errors, you think that you've fixed it, when in reality, you haven't, due to this lack of type checking await. Whereas if I knew that it wasn't type-checking from the start, I either wouldn't have used async/await, or I would have written the code / done the refactors differently to ensure there weren't problems.

**Comment by brad4d** [comment] 2018-11-20 22:17
Just pulled the trigger today on a change that moves async function transpilation after type checking.
The change will be pushed to GitHub tomorrow.

With this change type checking within async functions and on await statements should be just the same as in ordinary functions.

So, I'm closing this issue.
Please open a new issue for specific type checking problems if you find they are still happening after that change is pushed.

**Closed by brad4d** 2018-11-20 22:17 UTC
