### ISSUE TITLE
Request for @readonly

### ISSUE THREAD

**Issue by si-robertson** [google/closure-compiler#851] opened 2015-02-25 01:22 UTC
Being able to mark properties as `readonly` would be very useful. I'm having to [mark readonly properties as `const`](https://github.com/si-robertson/exgen/commit/864e61b21be84d29789a1ba99602728a53d83182) at the moment and that doesn't make much sense.

**Comment by ChadKillingsworth** [comment] 2015-02-25 01:59
Duplicate of #139 

See @concavelenz comment at https://code.google.com/p/closure-compiler/issues/detail?id=1273#c4 for how to do this. We just never went back through the externs.

**Closed by ChadKillingsworth** 2015-02-25 01:59 UTC
