### ISSUE TITLE
Incorrect array item comparison with zero in ADVANCED_OPTIMIZATION mode

### ISSUE THREAD

**Issue by alexey-malov** [google/closure-compiler#2136] opened 2016-11-09 12:29 UTC
When using ADVANCED_OPTIMIZATIONS flag, the comparison with zero is compiled into wrong code.

```js
function lastItemIsZero(array) {
    return array[array.length - 1] == 0;
}

// both two following lines are required to reproduce the issue.
console.log(lastItemIsZero([])); // true with ADVANCED_OPTIMIZATIONS flag, false - without
console.log(lastItemIsZero([0])); // always true
```

This issue causes error in moveTo method of goog.graphics.Path class (from google closure library):
```js
/**
 * Adds a point to the path by moving to the specified point. Repeated moveTo
 * commands are collapsed into a single moveTo.
 *
 * @param {number} x X coordinate of destination point.
 * @param {number} y Y coordinate of destination point.
 * @return {!goog.graphics.Path} The path itself.
 */
goog.graphics.Path.prototype.moveTo = function(x, y) {
  if (goog.array.peek(this.segments_) == goog.graphics.Path.Segment.MOVETO) {
    this.arguments_.length -= 2;
  } else {
    this.segments_.push(goog.graphics.Path.Segment.MOVETO);
    this.count_.push(1);
  }
  this.arguments_.push(x, y);
  this.currentPoint_ = this.closePoint_ = [x, y];
  return this;
};
```
When `this.segments_` is an empty array, the if condition is true instead of false.

**Comment by ChadKillingsworth** [comment] 2016-11-09 13:04
I'm not able to recreate the issue either with the web service or on the command line.

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520lastItemIsZero(array)%2520%257B%250A%2520%2520%2520%2520return%2520array%255Barray.length%2520-%25201%255D%2520%253D%253D%25200%253B%250A%257D%250A%250A%252F%252F%2520both%2520two%2520following%2520lines%2520are%2520required%2520to%2520reproduce%2520the%2520issue.%250Aconsole.log(lastItemIsZero(%255B%255D))%253B%2520%252F%252F%2520true%2520with%2520ADVANCED_OPTIMIZATIONS%2520flag%252C%2520false%2520-%2520without%250Aconsole.log(lastItemIsZero(%255B0%255D))%253B%2520%252F%252F%2520always%2520true%250A

**Comment by ikabirov** [comment] 2016-11-10 07:06
updated code:
```
/**
 * @param {!Array<number>} array
 * @returns {boolean}
 */
function lastItemIsZero(array) {
	return array[array.length - 1] == 0;
}

// both two following lines are required to reproduce the issue.
console.log(lastItemIsZero([])); // true with ADVANCED_OPTIMIZATIONS flag, false - without
console.log(lastItemIsZero([0])); // always true
```
for reproducing you also must add --jscomp_error=constantProperty

my command line arguments
`java -client -jar closure-compiler-v20161024.jar --js main.js --compilation_level=ADVANCED_OPTIMIZATIONS --jscomp_error=constantProperty --formatting=PRETTY_PRINT`

output code:
```
function a(b) {
  return !b[b.length - 1];
}
console.log(a([]));
console.log(a([0]));
```

**Comment by concavelenz** [comment] 2016-11-10 16:29
That is a type based optimization. Reading outsides the bounds of the array is invalid. If you want preserve the existing behavior, disable type based optimizations or declare the array as Array<number|undefined>

**Comment by ikabirov** [comment] 2016-11-25 07:22
Same problem when using `--warning_level=VERBOSE`, but only with command line

`java -client -jar closure-compiler-v20161024.jar --js main.js --compilation_level=ADVANCED_OPTIMIZATIONS --warning_level=VERBOSE`
returns `function a(b){return!b[b.length-1]}console.log(a([]));console.log(a([0]));`

But it's OK when i use online compiler http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520lastItemIsZero(array)%2520%257B%250A%2520%2520%2520%2520return%2520array%255Barray.length%2520-%25201%255D%2520%253D%253D%25200%253B%250A%257D%250A%250A%252F%252F%2520both%2520two%2520following%2520lines%2520are%2520required%2520to%2520reproduce%2520the%2520issue.%250Aconsole.log(lastItemIsZero(%255B%255D))%253B%2520%252F%252F%2520true%2520with%2520ADVANCED_OPTIMIZATIONS%2520flag%252C%2520false%2520-%2520without%250Aconsole.log(lastItemIsZero(%255B0%255D))%253B%2520%252F%252F%2520always%2520true%250A

returns `function a(b){return 0==b[b.length-1]}console.log(a([]));console.log(a([0]));`

**Comment by Dominator008** [comment] 2016-11-25 08:54
@ikabirov `--use_types_for_optimizations=false` can turn this off.

**Comment by ChadKillingsworth** [comment] 2016-11-25 12:36
@concavelenz posted the work around. Closing as it is by design.

**Closed by ChadKillingsworth** 2016-11-25 12:36 UTC
