### ISSUE TITLE
@record is not supported for class instances when using NTI 

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2500] opened 2017-05-17 10:08 UTC
```
/** @constructor */
function Foo() {};
Foo.prototype.num = function() {}

/** @record */
function PNum() {};
PNum.prototype.num = function() {};

var /** !PNum */ x = new Foo;  // warning
// WARNING - The right side in the assignment is not a subtype of the left side.
// Expected : PNum
// Found    : Foo
// More details:
// 	Incompatible types for property num.
// 	Expected : function(this:PNum):?
// 	Found    : function(this:Foo):?
// var /** !PNum */ x = new Foo;  // OK with structural interfaces
// ^^^^^^^

var /** !PNum */ y = { num: function() {} }; // OK
```

**Comment by shicks** [comment] 2017-05-17 16:32
Duplicate of #2497

**Closed by shicks** 2017-05-17 16:32 UTC
