### ISSUE TITLE
Incorrect assumption about default params?

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2368] opened 2017-03-13 15:09 UTC
I have a pattern from Redux reducers, where you have a first arg with a default parameter value, and a second arg without a default.
``` javascript
/**
 * @param {number} x
 * @param {number} y
 */
function a(x=1,y) {};
```
The method is always called (by Redux) with two args. The first arg may be passed undefined, in which case JS should use the default parameter value, as per [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Default_parameters).

Yet Closure Compiler infers that default parameters means the argument (and all to the right) can be dropped, i.e. var args:
```
input0:5: WARNING - optional arguments must be at the end
```

I can work around this easily, but I think this is a wrong assumption.

[Debugger](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520x%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520y%250A%2520*%252F%250Afunction%2520a(x%253D1%252Cy)%2520%257B%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1)

**Comment by MatrixFrog** [comment] 2017-03-13 18:04
This assumption predates ES6; we've applied it to optional parameters for years, if I'm not mistaken.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257Bnumber%253D%257D%2520opt_x%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520y%250A%2520*%252F%250Afunction%2520a(opt_x%252C%2520y)%2520%257B%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by MatrixFrog** [comment] 2017-03-13 18:05
It's in the `functionParams` group so it should be suppressible with `@suppress {functionParams}`

**Comment by ChadKillingsworth** [comment] 2017-03-13 18:06
@MatrixFrog We have the option to transpile them NOT to be optional though.

```js
/**
 * @param {number} x
 * @param {number} y
 */
function a(x,y) {
  if (x === undefined) {
    x = 1;
  }
}
```

**Comment by ChadKillingsworth** [comment] 2017-03-13 18:06
Also this is a duplicate of #2314

**Comment by MatrixFrog** [comment] 2017-03-13 18:08
Closing as duplicate then.

**Closed by MatrixFrog** 2017-03-13 18:08 UTC
