### ISSUE TITLE
@define should be usable in goog.modules

### ISSUE THREAD

**Issue by mitchellwills** [google/closure-compiler#2872] opened 2018-04-01 18:57 UTC
Currently @define cannot be used to annotate variables that are not provided into the global scope (they work with goog.provide and goog.module.declareLegacyNamespace, but not with a plain goog.module).

Ideally I could write the following code and use the flag `a.b.c.MY_FLAG`. Today there isn't even a compilation error with this code, it just says the flag doesn't exist if you try to use it.
```
goog.module('a.b.c');
/** @define {boolean} */
const MY_FLAG = false;
```

**Comment by ChadKillingsworth** [comment] 2018-04-01 19:36
This is really a duplicate of #1601

**Closed** 2018-04-01 19:36 UTC
