### ISSUE TITLE
support for @abstract JSDoc tag

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#104] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://blickly.github.io/closure-compiler-issues/#1080

**Comment by michaelhogg** [comment] 2015-05-28 14:09
+1 for implementing compile-time errors for the `@abstract` tag, similar to Java:

* error: `MyAbstractClass` is abstract; cannot be instantiated
* error: `MyClass` is not abstract and does not override abstract method `myAbstractMethod()` in `MyAbstractClass`

Related to #385 and #484.

**Comment by sidbyrd** [comment] 2016-08-24 00:40
Abstract methods may need some attention, too:

```
/**
 * @constructor
 * @abstract
 */
function AbstractClass() {}

// currently triggers "WARNING - Missing return statement" but shouldn't.
/**
 * @return {string}
 * @abstract
 */
AbstractClass.prototype.abstractMethodThatReturnsSomething = function() {};

/**
 * @constructor
 * @extends{AbstractClass}
 */
function ConcreteClass() {
	// Currently no warning for invoking abstract method
	console.log(this.abstractMethodThatReturnsSomething());
}

// Currently no warning for missing ConcreteClass.abstractMethodThatReturnsSomething()
```

**Comment by Dominator008** [comment] 2016-08-24 01:07
This has been implemented internally at Google but not submitted yet due to a bug in another project. Stay tuned :)

**Comment by myphysicslab** [comment] 2016-09-19 22:19
FYI after adding @abstract tags I'm now effectively blocked from using NTI.  I get a bunch of errors on abstract methods like this:

```
src/lab/engine2D/AbstractEdge.js:128: ERROR - Missing return statement. Function expected to 
return number.
AbstractEdge.prototype.distanceToPoint = function(p_body) {};
                                         ^
```

where the code is

```javascript
/** @inheritDoc @abstract */
AbstractEdge.prototype.distanceToPoint = function(p_body) {};
```

I suspect these errors stop the compilation process and I'm not seeing the more useful errors that NTI would otherwise show.

**Comment by dimvar** [comment] 2016-09-19 23:15
Expect to see this in the next month or two. I wish I could say in the next couple weeks, but it's not on the very top of my list right now. So, unless @Dominator008 contributes the fix sooner, expect this to happen around mid Q4.

**Comment by supersteves** [comment] 2016-11-24 08:25
This appears to be the umbrella task for `@abstract` support. 

I saw some commits fly by - most recently "[NTI] Finish support for abstract classes and methods." https://github.com/google/closure-compiler/commit/1ab5aca57367be9f99673be7fd9cf649812e1e21 - and gave it a try. 

Status seems to be that abstract classes now work well, but abstract methods cannot be used if the method has a return value, since you either get 

* an NTI complaint `JSC_NTI_MISSING_RETURN_STATEMENT` **Missing return statement. Function expected to return string.** (if empty); the equivalent doesn't occur under NTI
* or `JSC_MISPLACED_ANNOTATION` **Misplaced `@abstract` annotation. function with a non-empty body cannot be abstract** (if you put the classic approach of `throw goog.abstractMethod()`); both OTI+NTI.

**Comment by dimvar** [comment] 2016-11-28 17:42
Oops, the "missing return" warning is a bug in NTI. I'll fix. Thanks.

**Comment by Dominator008** [comment] 2016-11-29 05:59
Closed by https://github.com/google/closure-compiler/commit/4a885d88fe6307738d78b1f67d1e2724ac8da173.

**Closed by Dominator008** 2016-11-29 05:59 UTC
Labels: enhancement, NTI, Types, Work In Progress

**Comment by myphysicslab** [comment] 2016-12-06 21:15
This is still not working for me with NTI. I just pulled the current compiler code, did `mvn clean` and rebuilt the compiler, `git log` returns commit 65b4c86ea041684c7585b016a90e0eb4e5974292
(and I confirmed that the code from 4a885d8 is in my source code here).

Here is one of the errors, after adding the `--new_type_inf` flag

    src/lab/model/AbstractMassObject.js:182: ERROR - Missing return statement. Function expected to return number.
    AbstractMassObject.prototype.getBottomBody = function() {};
                                                 ^^^^^^^^^^^^^

Here is code from constructor:

    /** Abstract class which implements most of the
    {@link myphysicslab.lab.model.MassObject MassObject} methods.

    * @param {string=} opt_name name of this SimObject (optional)
    * @param {string=} opt_localName localized name of this SimObject (optional)
    * @constructor
    * @abstract
    * @struct
    * @extends {AbstractSimObject}
    * @implements {myphysicslab.lab.model.MassObject}
    */
    myphysicslab.lab.model.AbstractMassObject = function(opt_name, opt_localName) {

and the method getting the error:

    /** @inheritDoc @abstract */
    AbstractMassObject.prototype.getBottomBody = function() {};

Maybe it's because I'm using `@inheritDoc` ?

**Comment by dimvar** [comment] 2016-12-09 00:09
Does it work if you remove inheritDoc?

**Comment by myphysicslab** [comment] 2016-12-09 00:28
Same result without inheritDoc.  I changed the method to this:

    /** Returns vertical coordinate of bottom-most point of this body, in body coordinates
    @return {number} vertical coordinate of bottom-most point of this body, in body
        coordinates
    @abstract
    */
    AbstractMassObject.prototype.getBottomBody = function() {};

And still get the same error:

    src/lab/model/AbstractMassObject.js:184: ERROR - Missing return statement. Function expected to return number.
    AbstractMassObject.prototype.getBottomBody = function() {};
                                                 ^^^^^^^^^^^^^

Perhaps the "implements interface" is involved? Here is some code from the interface that is implemented, in case that helps:

    /**
    * @interface
    * @extends {myphysicslab.lab.model.SimObject}
    */
    myphysicslab.lab.model.MassObject = function() {};
    var MassObject = myphysicslab.lab.model.MassObject;

    /** Returns vertical coordinate of bottom-most point of this body, in body coordinates
    @return {number} vertical coordinate of bottom-most point of this body, in body
        coordinates
    */
    MassObject.prototype.getBottomBody;

There are a couple more interfaces above that in the chain. But they don't have any method named `getBottomBody`.

    /**
    * @interface
    * @extends {myphysicslab.lab.util.Printable}
    */
    myphysicslab.lab.model.SimObject = function() {};
    var SimObject = myphysicslab.lab.model.SimObject;

    /**
    * @interface
    */
    myphysicslab.lab.util.Printable = function() {};

**Comment by dimvar** [comment] 2016-12-12 06:45
OK, I [reproduced it](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Afunction%2520Foo()%2520%257B%257D%250A%250A%252F**%2520%2540return%2520%257Bnumber%257D%2520*%252F%250AFoo.prototype.prop%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540constructor%2520%2540abstract%2520%2540implements%2520%257BFoo%257D%2520*%252F%250Afunction%2520Bar()%2520%257B%257D%250A%250A%252F**%2520%2540abstract%2520*%252F%250ABar.prototype.prop%2520%253D%2520function()%2520%257B%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1) and I'll submit a fix.

I'm keeping this closed because `@abstract` is supported in NTI. If you find more bugs after the fix lands, please file new issues.
