### ISSUE TITLE
Return type not inferred for Array.prototype.reduce (NTI+old)

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1197] opened 2015-10-07 17:15 UTC
Here I'd expect the compiler to know that the return type was ```{number}```:
``` javascript
function func(/** Array<number> */ a) {

  return a.reduce(
    (prev, row) => Math.max(prev, row[1]),
    0
  );

}

let test = func([1,2,3]);

console.log(test);
```

Current version externs for Array.prototype.reduce:
``` javascript
/**
 * Apply a function simultaneously against two values of the array (from
 * left-to-right) as to reduce it to a single value.
 *
 * @param {?function(?, T, number, !Array<T>) : R} callback
 * @param {*=} opt_initialValue
 * @return {R}
 * @this {{length: number}|Array<T>|string}
 * @template T,R
 * @see http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce
 */
Array.prototype.reduce = function(callback, opt_initialValue) {};
```

But it's unknown:
```
...
CALL 12 [source_file: input0] : ?
    GETPROP 12 [source_file: input0] : function (this:Console, ...*): ?
        NAME console 12 [source_file: input0] : Console
        STRING log 12 [source_file: input0] : string
    NAME test 12 [source_file: input0] : ?
```

https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520func(%252F**%2520Array%253Cnumber%253E%2520*%252F%2520a)%2520%257B%250A%250A%2520%2520return%2520a.reduce(%250A%2520%2520%2520%2520(prev%252C%2520row)%2520%253D%253E%2520Math.max(prev%252C%2520row%255B1%255D)%252C%250A%2520%2520%2520%25200%250A%2520%2520)%253B%250A%250A%257D%250A%250Alet%2520test%2520%253D%2520func(%255B1%252C2%252C3%255D)%253B%250A%250Aconsole.log(test)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

I've seen a number of similar cases today (e.g. https://github.com/google/closure-compiler/issues/1194#issuecomment-146224619), and in my (soon-to-expire) experimental quest for 100% typing I've worked around these by adding type annotations to the passed function.

**Comment by concavelenz** [comment] 2015-10-13 02:56
Strangely, this works: 
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540const%2520*%252F%2520var%2520ns%2520%253D%2520%257B%257D%253B%250A%252F**%2520%2540return%2520%257Bnumber%257D%2520*%252F%250Avar%2520g%2520%253D%2520function%2520(a%252Cb)%2520%257B%2520return%2520x%257D%253B%250A%250Afunction%2520func(%252F**%2520!Array%253Cnumber%253E%2520*%252F%2520a)%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bnull%257D%2520*%252F%2520var%2520x%2520%253D%2520null%253B%250A%2520%2520%2520%2520x%2520%253D%2520a.reduce(function(prev%252C%2520row)%2520%257B%2520return%2520g(1%252C2)%253B%2520%257D%252C%25200)%253B%250A%257D%250A%250Alet%2520test%2520%253D%2520func(%255B1%252C2%252C3%255D)%253B%250A%250Aconsole.log(test)%253B%26input1%26conformanceConfig%26externs%3D%250A%250A%252F**%250A%2520*%2520Apply%2520a%2520function%2520simultaneously%2520against%2520two%2520values%2520of%2520the%2520array%2520(from%250A%2520*%2520left-to-right)%2520as%2520to%2520reduce%2520it%2520to%2520a%2520single%2520value.%250A%2520*%250A%2520*%2520%2540param%2520%257B%253Ffunction(%253F%252C%2520T%252C%2520number%252C%2520!Array%253CT%253E)%2520%253A%2520R%257D%2520callback%250A%2520*%2520%2540param%2520%257B*%253D%257D%2520opt_initialValue%250A%2520*%2520%2540return%2520%257BR%257D%250A%2520*%2520%2540this%2520%257B%257Blength%253A%2520number%257D%257CArray%253CT%253E%257Cstring%257D%250A%2520*%2520%2540template%2520T%252CR%250A%2520*%252F%250AArray.prototype.reduce2%2520%253D%2520function(callback%252C%2520opt_initialValue)%2520%257B%257D%253B%250A%250Avar%2520x%250A%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by supersteves** [comment] 2016-01-20 06:12
Not sure what I was writing in the original debugger link. Here's a better example (NTI):
https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520func(%252F**%2520Array%253Cnumber%253E%2520*%252F%2520a)%2520%257B%250A%250A%2520%2520return%2520a.reduce(%250A%2520%2520%2520%2520(previousValue%252C%2520currentValue)%2520%253D%253E%2520%250A%2520%2520%2520%2520%2520%2520%2520%2520Math.max(previousValue%252C%2520currentValue)%252C%250A%2520%2520%2520%25200%250A%2520%2520)%253B%250A%250A%257D%250A%250Alet%2520test%2520%253D%2520func(%255B1%252C2%252C3%255D)%253B%250A%250Aconsole.log(test)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

Still the function result is unknown type, but should be number.

Here's a MUCH simpler example. The return type of this function in NTI is unknown:
``` function f() {return 42;} ```

https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f()%2520%257Breturn%252042%253B%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by dimvar** [comment] 2016-01-20 07:16
In the last example NTI infers the return type correctly.

https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f()%2520%257Breturn%252042%253B%257D%250Avar%2520%252F**%2520string%2520*%252F%2520s%2520%253D%2520f()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by supersteves** [comment] 2016-01-20 09:13
OK, I take back the "MUCH simpler example".  
(The AST dump in the debugger shows "?" as the return type for the function. Presumably this is wrong?)

I've narrowed down the original problem with Array.reduce much further. Here's a succinct example:
### Extern
``` javascript
/**
 * @param {function(?, T) : R} callback
 * @param {*} initial
 * @return {R}
 * @template T,R
 */
var reduce = function(callback, initial) {};
```
### Code
``` javascript
var /** string */ s = reduce((p, c) => Math.max(p, c), 0);
```
Should infer number result, doesn't. Compiles successfully, but should not.

https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%252F**%2520string%2520*%252F%2520s%2520%253D%2520reduce((p%252Cc)%253D%253EMath.max(p%252Cc)%252C%25200)%253B%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540param%2520%257Bfunction(%253F%252C%2520T)%2520%253A%2520R%257D%2520callback%250A%2520*%2520%2540param%2520%257B*%257D%2520initial%250A%2520*%2520%2540return%2520%257BR%257D%250A%2520*%2520%2540template%2520T%252CR%250A%2520*%252F%250Avar%2520reduce%2520%253D%2520function(callback%252C%2520initial)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

**Comment by dimvar** [comment] 2016-01-20 17:05
Great, thanks for the small example, that was much easier to debug. So, the problem isn't bad inference by NTI, it's that Math.max has a bad signature, that doesn't allow us to infer that its arguments are numbers.
https://github.com/google/closure-compiler/blob/master/externs/es3.js#L997

If instead there was some other operation that uses numbers, NTI would find the type error with reduce.
https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(p%252Cc)%2520%257B%250A%2520%2520return%2520p%2520-%2520c%253B%250A%257D%250A%250Avar%2520%252F**%2520string%2520*%252F%2520s%2520%253D%2520reduce(f%252C%25200)%253B%250A%250Avar%2520%252F**%2520null%2520*%252F%2520n%2520%253D%2520f%253B%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540param%2520%257Bfunction(%253F%252C%2520T)%2520%253A%2520R%257D%2520callback%250A%2520*%2520%2540param%2520%257B*%257D%2520initial%250A%2520*%2520%2540return%2520%257BR%257D%250A%2520*%2520%2540template%2520T%252CR%250A%2520*%252F%250Avar%2520reduce%2520%253D%2520function(callback%252C%2520initial)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

Also, a useful trick when you're debugging these things: If you want to know the type of something, you can usually assign it to null, and then see the type in the error message.

**Closed** 2016-01-20 17:05 UTC

**Comment by supersteves** [comment] 2016-01-20 17:20
What's bad about the signature of Math.max?

This correctly fails:
https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%252F**%2520string%2520*%252F%2520s%2520%253D%2520reduce((p%252Cc)%253D%253Emax2(p%252Cc)%252C%25200)%253B%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540param%2520%257Bfunction(%253F%252C%2520T)%2520%253A%2520R%257D%2520callback%250A%2520*%2520%2540param%2520%257B*%257D%2520initial%250A%2520*%2520%2540return%2520%257BR%257D%250A%2520*%2520%2540template%2520T%252CR%250A%2520*%252F%250Avar%2520reduce%2520%253D%2520function(callback%252C%2520initial)%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520var_args%250A%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520*%252F%250Avar%2520max2%2520%253D%2520function(var_args)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

This doesn't:
https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%252F**%2520string%2520*%252F%2520s%2520%253D%2520reduce((p%252Cc)%253D%253EMath.max2(p%252Cc)%252C%25200)%253B%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540param%2520%257Bfunction(%253F%252C%2520T)%2520%253A%2520R%257D%2520callback%250A%2520*%2520%2540param%2520%257B*%257D%2520initial%250A%2520*%2520%2540return%2520%257BR%257D%250A%2520*%2520%2540template%2520T%252CR%250A%2520*%252F%250Avar%2520reduce%2520%253D%2520function(callback%252C%2520initial)%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520var_args%250A%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520*%252F%250AMath.max2%2520%253D%2520function(var_args)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

**Comment by dimvar** [comment] 2016-01-20 17:48
Oh, you're right, I was looking at the argument types being `*` and I missed that the return type is `number`. So, the reason is a bug that has been fixed at commit 822853505a1da753f170a61b14defc501138c188, but it looks like the debugger hasn't been updated.

**Comment by supersteves** [comment] 2016-01-20 18:02
Great. Does the debugger expose the github revision? I can only see some numeric ID.

**Comment by MatrixFrog** [comment] 2016-01-20 18:07
The number after the @ should roughly correspond to a github revision via the "MOE_MIGRATED_REVID" in the commit message. So for example d3c669a598134e08d22ab6263b3c9b442e86bc17 is equivalent to `@112496453` so the current debugger was built after that commit.

**Comment by dimvar** [comment] 2016-01-20 18:14
FYI, I updated the debugger and now your Math.max2 example works as expected.

**Comment by supersteves** [comment] 2016-01-20 18:20
Confirmed, as are all examples above. Thanks.

Do you have unit coverage for this case? If not - should you / a contributor add them when issues like this are filed and subsequently fixed?

**Comment by dimvar** [comment] 2016-01-20 18:25
We add unit tests every time we fix a bug, so we should be OK.
