### ISSUE TITLE
Infinite loop in compilation

### ISSUE THREAD

**Issue by evmar** [google/closure-compiler#3067] opened 2018-09-05 21:14 UTC
I reduced a problem from some lodash externs to the following program, which goes into an infinite loop when I compile it.

I have not been able reduce this further -- somehow all the pieces here are necessary.  In particular note that "unique" is used in two different types, and also the wacky use of templates.

```js
var _ = {};
/**
 * @record
 * @template T
 */
_.Wrapper = function() {};
/**
 * @record
 * @template T
 */
_.ArrayWrapper = function() {};
/**
 * @return {!_.ArrayWrapper<T>}
 */
_.Wrapper.prototype.unique = function() {};
/**
 * @return {!_.ArrayWrapper}
 */
_.ArrayWrapper.prototype.unique = function() {};
/**
 * @return {!_.ArrayWrapper<!Array<T>>}
 */
_.ArrayWrapper.prototype.unzip = function() {};
/**
 * @return {!_.Wrapper<number>|!_.Wrapper<boolean>|!_.ArrayWrapper<T>}
 */
_.WrapperBase.prototype.plant = function(value) {};
```

**Comment by lauraharker** [comment] 2018-09-06 17:14
This appears to be happening sometime during type inference/typechecking.

Putting these [externs in the debugger](https://closure-compiler-debugger.appspot.com/#input0%26input1%26conformanceConfig%26externs%3Dvar%2520_%2520%253D%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540template%2520T%250A%2520*%252F%250A_.Wrapper%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540template%2520T%250A%2520*%252F%250A_.ArrayWrapper%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540return%2520%257B!_.ArrayWrapper%253CT%253E%257D%250A%2520*%252F%250A_.Wrapper.prototype.unique%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540return%2520%257B!_.ArrayWrapper%257D%250A%2520*%252F%250A_.ArrayWrapper.prototype.unique%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540return%2520%257B!_.ArrayWrapper%253C!Array%253CT%253E%253E%257D%250A%2520*%252F%250A_.ArrayWrapper.prototype.unzip%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540return%2520%257B!_.Wrapper%253Cnumber%253E%257C!_.Wrapper%253Cboolean%253E%257C!_.ArrayWrapper%253CT%253E%257D%250A%2520*%252F%250A_.WrapperBase.prototype.plant%2520%253D%2520function(value)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue) caused an infinite loop iff CHECK_TYPES was enabled with the stack trace
```
<continued from previous message>
	at com.google.javascript.rhino.jstype.JSType.hashCode(JSType.java:799)
	at com.google.common.collect.ImmutableList.hashCode(ImmutableList.java:669)
	at java.util.Arrays.hashCode(Arrays.java:4146)
	at java.util.Objects.hash(Objects.java:128)
	at com.google.javascript.rhino.jstype.TemplatizedType.recursionUnsafeHashCode(TemplatizedType.java:134)
	at com.google.javascript.rhino.jstype.JSType.hashCode(JSType.java:799)
	at com.google.common.collect.ImmutableList.hashCode(ImmutableList.java:669)
	at java.util.Arrays.hashCode(Arrays.java:4146)
	at java.util.Objects.hash(Objects.java:128)
	at com.google.javascript.rhino.jstype.TemplatizedType.recursionUnsafeHashCode(TemplatizedType.java:134)
	at com.google.javascript.rhino.jstype.JSType.hashCode(JSType.java:799)
	at com.google.common.collect.ImmutableList.hashCode(ImmutableList.java:669)
        [ ... etc]
```

@nreid260 I believe you know the most about JSType hash codes, could you take a look?

**Comment by nreid260** [comment] 2018-09-21 19:02
The stack trace from the compiler is a red-herring; the `hashCode` calls only look like infinite recursion. The real recursive loop is further down and is occurs in structural subtype checking. The `hashCode` looks this way because, as explained below, an infinite sequence of template specializations was being generated and hashed (i.e. `!_.ArrayWrapper<!Array<T>>`, !_.ArrayWrapper<!Array<!Array<T>>>`, !_.ArrayWrapper<!Array<!Array<!Array<T>>>>`, ...). The subtype check was checking each of these new specializations for compatibility.

The issue is that, when building the union type for the last declaration, the raw-type `Wrapper` was leaking out. This is because in many situations a raw-type is interchangeable with a template specialization on `?`.

The issue with the raw-type was that it was (and I'm not sure about the why) being treated as a template type. That is, when we looked at its properties we were dynamically generating their type as specializations of the raw-type properties with the template values subbed in. Unfortunately, when there are no values (as in a raw-type), and the property type is recursive, the substitution results in another reference to the original template parameter (e.g. `Array<T>` => `Array<Array<T>>`). Then the substitution happens again.

Here's an even simpler reproduction case that I've annotated with the relevant trigger conditions.
`
// We need two templated structural types that might match (i.e. `RecordA` and
// `RecordB`).
/**
 * @record",
 * @template PARAM_A
 */
var RecordA = function() {};

/**
 * @record
 * @template PARAM_B
 */
var RecordB = function() {};

// Then we need to give them both a property that:
//  - could match
//  - templates on one of the two types (Notice they can be mixed and matched since they
//    might be structurally equal)
//  - is a nested template (i.e. `Array<X>`) (This is going to explode the recursion)
//  - uses each type's template parameter (So there's a variable to recur on)
/** @type {!RecordA<PARAM_A>} */
RecordA.prototype.prop;

/** @type {!RecordB<PARAM_B>} */
RecordB.prototype.prop;

// Finally, we need to create a union that:
//  - generates a raw-type for one of the structural template types (i.e. `RecordA')
//    (`RecordA<number>` and `RecordA<boolean>` will be smooshed into a raw-type)
//  - attempts a structural match on that raw-type against the other record type
// For some reason this also needs to be a property of a forward referenced type.
/** @type {(!RecordA<number>|!RecordA<boolean>)|!RecordB<string>} */
Union.anything;
`

**Comment by nreid260** [comment] 2018-09-26 23:04
This should be fixed in the next release.

**Closed by nreid260** 2018-09-26 23:04 UTC

**Comment by mprobst** [comment] 2018-09-27 07:45
Nice!
