### ISSUE TITLE
Fails to parse shorthand methods with a string literal name

### ISSUE THREAD

**Issue by jschaf** [google/closure-compiler#2058] opened 2016-10-04 07:15 UTC
The compiler fails on shorthand method definitions that use a string literal name.  Since the method name is a [property](http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions), it can be an  [string literal](http://www.ecma-international.org/ecma-262/6.0/#sec-object-initializer).

See [compilation error](https://closure-compiler.appspot.com/home#code%3Dvar%2520a%2520%253D%2520%257B%250A%2520%2520'Program%253Aexit'(node)%2520%257B%250A%2520%2520%2520%2520%2520return%2520node%253B%2520%250A%2520%2520%257D%250A%257D%250A%250A).

```js
var a = {
  'Program:exit'(node) {
     return node; 
  }
}
```

Error Output:
```
JSC_PARSE_ERROR: Parse error. '[' expected at line 2 character 2
  'Program:exit'(node) {
  ^
```

**Comment by brad4d** [comment] 2016-10-04 15:54
I believe you can workaround this with `['Program:exit'](node) {`.

**Comment by jschaf** [comment] 2016-10-04 18:44
Yep, that workaround works for me.

**Comment by Dominator008** [comment] 2016-10-04 22:32
Duplicate of #2044

**Closed by Dominator008** 2016-10-04 22:32 UTC
Labels: duplicate
