### ISSUE TITLE
Transpiling '[...array]' should turn empty slots in the array into undefined

### ISSUE THREAD

**Issue by duonglaiquang** [google/closure-compiler#4183] opened 2024-07-29 03:24 UTC
- [According to the specs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays), empty slots inside `array` need to be transformed to `undefined` when spread using the
`[…array]` syntax

- Closure compiler currently does not do this and produces similary empty slots in the result. This has particulary adverse effects on code that use `.forEach()` on the result since `.forEach()` does not iterate over empty slots

- The following screenshot shows the result of transpiling ECMAScript 2015 `[...array]` into ES5 using the `@language_out ECMASCRIPT5` flag:

<img width="1512" alt="Screenshot 2024-07-29 at 10 51 51" src="https://github.com/user-attachments/assets/77d3940d-baf8-4013-bd3b-2b380dc6545c">

- Here are some examples comparing the output between the original code and transpiled code using Chrome

    ```javascript
    // original code output:
    [...Array(1)] // [undefined]
    [...[1,undefined,,null]] // [1,undefined,undefined,null]

    // Closure compiler transpiled code output:
    [...Array(1)] // [empty]
    [...[1,undefined,,null]] // [1,undefined,empty,null]
    ```

**Comment by brad4d** [comment] 2024-08-06 00:08
This is a duplicate of https://github.com/google/closure-compiler/issues/3294

**Closed** 2024-08-06 00:09 UTC
