### ISSUE TITLE
Initialize variable declared in catch to the right type

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#862] opened 2015-03-02 05:54 UTC
Using new type inference, I get this error:
```
src/lab/util/Terminal.js:344: WARNING - Cannot access property stack of non-object type
 undefined.
    window.console.log(ex+' '+ex.stack);
                              ^
```
for the following code:
```javascript
  try {
    // code omitted...
  } catch (ex) {
    window.console.log(ex+' '+ex.stack);
  }
```
My attempts to cast the variable `ex` to an Error or some other type are unsuccessful.  In the externs file `es3.js` Error is defined to have a stack property:
```
/** @type {string} */
Error.prototype.stack;
```

**Comment by dimvar** [comment] 2015-05-06 20:33
I'm assuming this is a duplicate of #856

**Comment by myphysicslab** [comment] 2015-05-22 00:34
While #856 seems to be fixed, this is still happening.  Reopen?

Same warning:
```
src/lab/util/Terminal.js:348: WARNING - Cannot access property stack of non-object type undefined.
    window.console.log(ex+' '+ex.stack);
                              ^
```

Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150505-58-g39bb337
Built on: 2015/05/21 12:45

**Comment by dimvar** [comment] 2015-05-22 06:32
Oops, I was too fast to mark this as dup. Clearly ex isn't declared in the externs :)

**Comment by dimvar** [comment] 2015-05-22 21:45
I cannot reproduce this.

Is by any chance some other variable called ex in the same function scope as the catch block? If so, that is the issue; we don't currently introduce a new scope for catch variables.

**Comment by myphysicslab** [comment] 2015-05-23 00:28
There is not another `ex` variable.  Here is a small method which reproduces the error for me:

```javascript
/**
* @return {undefined}
*/
UtilityCore.testCatch = function() {
  try {
    window.console.log('this is bound to fail!');
    throw new Error('certain failure');
  } catch (ex) {
    window.console.log('// '+ex);
    window.console.log(ex+' '+ex.stack);
  }
};
```

error message with NTI:
```
src/lab/util/UtilityCore.js:765: WARNING - Cannot access property stack of non-object type undefined.
    window.console.log(ex+' '+ex.stack);
                              ^
```

Output in console window in Safari:
```
[Log] this is bound to fail! (ChainApp_en.js, line 165)
[Log] // Error: certain failure (ChainApp_en.js, line 165)
[Log] Error: certain failure testCatch@file:///Users/erikn/Documents/Programming/jssimlab/build/sims/engine2D/ChainApp_en.js:165:116 (ChainApp_en.js, line 165)
ChainApp@file:///Users/erikn/Documents/Programming/jssimlab/build/sims/engine2D/ChainApp_en.js:1474:323
global code@file:///Users/erikn/Documents/Programming/jssimlab/build/sims/engine2D/ChainApp_en.html:135:48
```

**Comment by dimvar** [comment] 2015-05-25 06:07
I was using bad tests when trying to repro this. Confirmed the bug now. Will fix.

**Closed** 2015-05-27 17:11 UTC
Labels: NTI, P1

**Comment by myphysicslab** [comment] 2015-05-28 18:40
confirmed fixed in Version: v20150505-71-g192067b
