### ISSUE TITLE
File-based module naming scheme breaks type-checker for node module resolution

### ISSUE THREAD

**Issue by traviskaufman** [google/closure-compiler#2386] opened 2017-03-23 19:15 UTC
## Steps to reproduce

1. In an empty directory run the following commands:

```sh
mkdir -p a b/node_modules c/node_modules
touch a/index.js b/index.js c/index.js
(cd a && npm init -y) && (cd b && npm init -y) && (cd c && npm init -y)
```

2. Put the following in `a/index.js`:

```js
/** @interface */
class A {
  /** @return {string} */
  getString() {}
}

module.exports = A;
```

3. Put the following in `b/index.js`:

```js
const A = require('a');

module.exports = class B {
  /**
   * @param {!A} a
   * @return {string}
   */
  getStringFromA(a) {
    return `String from a called from B: ${a.getString()}`;
  }
};
```

4. Put the following in `c/index.js`:

```js
const A = require('a');
const B = require('b');

/** @implements {A} */
class C {
  getString() {
    return 'result of calling getString() from class C, which implements A';
  }
}

/**
 * @param {!B} b
 * @param {!A} a
 */
function thisWillNotWork(b, a) {
  console.log(b.getStringFromA(a));
}

/**
 * @param {!A} a
 */
function thisWillWork(a) {
  console.log(a.getString());
}

const b = new B();
const c = new C();

thisWillNotWork(b, c);
thisWillWork(c);
```

5. Run the following commands:

```sh
cp -rf a b/node_modules && cp -rf a c/node_modules && cp -rf b c/node_modules
```

Your directory should now have the following structure:

```
.
├── a
│   ├── index.js
│   └── package.json
├── b
│   ├── index.js
│   ├── node_modules
│   │   └── a
│   │       ├── index.js
│   │       └── package.json
│   └── package.json
└── c
    ├── index.js
    ├── node_modules
    │   ├── a
    │   │   ├── index.js
    │   │   └── package.json
    │   └── b
    │       ├── index.js
    │       ├── node_modules
    │       │   └── a
    │       │       ├── index.js
    │       │       └── package.json
    │       └── package.json
    └── package.json
```

6. Run the `c/index.js` script to ensure everything is working properly:

```sh
node c/index.js
# String from a called from B: result of calling getString() from class C, which implements A
# result of calling getString() from class C, which implements A
```

7. Run the following command and observe the output:

```sh
java -jar /path/to/compiler.jar \
  --js $(find . -type f -name '*.js') \
  --js $(find . -type f -name 'package.json') \
  --compilation_level ADVANCED \
  --module_resolution NODE \
  --process_common_js_modules \
  --checks_only
```

## Expected result

The code compiles without error (see [this equivalent appspot script with no imports](https://goo.gl/DKCr1h))

## Actual Result

```
./c/index.js:16: WARNING - actual parameter 1 of module$c$node_modules$b$index.prototype.getStringFromA does not match formal parameter
found   : module$c$node_modules$a$index
required: module$c$node_modules$b$node_modules$a$index
  console.log(b.getStringFromA(a));
                               ^

0 error(s), 1 warning(s), 100.0% typed
```

## Additional Info

I suspect this is happening because _closure is naming modules based on their file path_, which _will not work_ for NodeJS code. [The way in which NPM installs dependencies](https://docs.npmjs.com/how-npm-works/npm3) means there may very well be the same module that's referenced in two different locations. Closure seems to fail to take this into account when naming modules using node's module resolution algorithm. Because of this, closure treats the two equivalent modules differently, thus a false positive is given. 

Note also that this directly impacts a project we're working on - https://github.com/material-components/material-components-web. We symlink all of our dependencies in `packages/` together using [lernaJS](https://lernajs.io/) (note that we follow symlinks when passing our `--js` flags), but because they are in "different locations", their modules are named differently, and thus we need to create a lot of extra effort around rewriting all of our imports to be relative to one another, which is less-than-optimal :) 

### Possible Solution: Name modules based on package.json info

A reliable way to uniquely identify a module in node is to _combine its name and its version_. By doing so, you can almost guarantee that you will never have a collision between two separate modules. Perhaps the way the modules are named could be changed to reflect this - or some other - strategy when `--module_resolution NODE` is given? 

Finally, FWIW here is how Typescript resolves its modules when `--module-resolution node` is given as a flag: https://www.typescriptlang.org/docs/handbook/module-resolution.html#node

**Comment by ChadKillingsworth** [comment] 2017-03-23 21:13
@traviskaufman We do account for the node_module structure not being flat: https://github.com/google/closure-compiler/blob/35e1e1b102eea96f8a3aa23adf1763a1e6f9acbe/test/com/google/javascript/jscomp/deps/ModuleLoaderTest.java#L186-L191

I'll try to dig into this soon though to see what's going on.

**Comment by ChadKillingsworth** [comment] 2017-03-23 21:14
> there may very well be the same module that's referenced in two different locations.

More info: in this case they should be treated as two distinct modules. They could be significantly different versions.

**Comment by traviskaufman** [comment] 2017-03-23 21:20
> in this case they should be treated as two distinct modules

In some cases, yes. But in other cases - like the concrete one I mentioned above - you'll have the same module (with the same version) in two different locations. I feel like it makes sense to assign the same module name if the referenced node module has the same `name` and `version` fields specified in its `package.json`.

**Comment by ChadKillingsworth** [comment] 2017-03-23 21:42
If you suppress the type checking warnings and bundle the code, does it execute correctly?

**Comment by ChadKillingsworth** [comment] 2017-03-23 21:51
Also - try changing `@interface` to `@record` - and then don't use `@implements`. That uses structural type checking similar to typescript.

**Comment by traviskaufman** [comment] 2017-03-23 22:12
> If you suppress the type checking warnings and bundle the code, does it execute correctly?

Yep! Works if I add a `--jscomp_off checkTypes` flag. However, I don't feel comfortable adding this flag as it takes away most of the benefit of using closure in the first place.

> Also - try changing @interface to @record - and then don't use @implements. That uses structural type checking similar to typescript.

For this example this would work, but for our real world use-case we use references to abstract classes, which would not work:

```sh
java -jar node_modules/google-closure-compiler/compiler.jar \
  --compilation_level ADVANCED \
  --js <ELIDED_FOR_BREVITY> \
  --language_out ECMASCRIPT5_STRICT \
  --dependency_mode STRICT \
  --entry_point packages/mdc-icon-toggle/index \
  --jscomp_off accessControls \
  --module_resolution NODE \
  --checks_only

packages/mdc-icon-toggle/index.js:66: WARNING - actual parameter 1 of MDCRipple$$module$packages$mdc_icon_toggle$node_modules$$material$ripple$index.createAdapter does not match formal parameter
found   : MDCIconToggle$$module$packages$mdc_icon_toggle$index
required: MDCComponent$$module$packages$mdc_icon_toggle$node_modules$$material$ripple$node_modules$$material$base$component
    const adapter = /** @type {!MDCRippleAdapter} */ (Object.assign(MDCRipple.createAdapter(this), {
                                                                                            ^^^^

0 error(s), 1 warning(s), 90.9% typed
```

**Comment by ChadKillingsworth** [comment] 2017-03-23 23:00
So at this point, you want the compiler to infer that two distinct modules are in fact the same type. I personally don't know how to accomplish this.

If it were my code, I would solve this with pre-compilation build steps to normalize the module tree. Or I would convert most of the types to `@records` and use structural type checking.

In any regards, I'm closing this issue as the original reported behavior is working as designed/intended.

**Closed by ChadKillingsworth** 2017-03-23 23:00 UTC

**Comment by traviskaufman** [comment] 2017-03-24 16:32
The modules aren't distinct. They're exactly the same. Closure compiler incorrectly treats them as distinct because the heuristics closure uses to infer module identity is based solely on that module's path within the filesystem. On the surface it just looks like it's inspecting both module names, seeing that they're not equivalent strings, and throwing a false positive. So yes, I _do_ want the compiler to infer that two ~distinct~ of the exact same module are in fact the same type, regardless of their location on the filesystem 😄 

It seems here that you are asking me to introduce non-trivial build infrastructure rules, as well as re-architect my code, in order to work around a compiler. I can't see how this behavior can be intended, as it essentially means that the closure compiler implements the node module resolution algorithm without making the type system aware of the semantics with which node identifies modules. When I use other typed JS variants - such as Flow or Typescript - I don't have to do this. 

Either way, we'll probably just work around it by not using the node module resolution algorithm. I do recommend, however, that you document this behavior, as it was quite surprising to me - as an end user of the compiler - when I encountered it. Thanks!

**Comment by ChadKillingsworth** [comment] 2017-03-24 17:35
This isn't a compiler limitation per se - it's now node modules work. Even two modules in separate folders with the same package.json name and version can be completely different (you can't assume they were all installed from npm).

Have you tried yarn's flat mode?
