### ISSUE TITLE
Regression: crash in ConvertToDottedProperties pass (likely due to default value in obj destructuring)

### ISSUE THREAD

**Issue by domoritz** [google/closure-compiler#3901] opened 2021-12-30 23:39 UTC
Clone https://github.com/domoritz/arrow/tree/dom/closure-bug, go into `js`, run `yarn` and `yarn build -t es2015`.

The error does not happen with 20210601.0.0 or 20211006.0.0. 

```
$ cross-env NODE_NO_WARNINGS=1 gulp build -t es2015
[18:36:18] Using gulpfile ~/Code/arrow/js/gulpfile.js
[18:36:18] Starting 'build'...
[18:36:18] Starting 'build:es2015:cjs'...
[18:36:18] Starting 'build:es2015:esm'...
[18:36:18] Starting 'build:es2015:cls'...
[18:36:18] Starting 'build:es2015:umd'...
[18:36:18] Starting 'clean:es2015:cjs'...
[18:36:18] Starting 'clean:es2015:esm'...
[18:36:18] Starting 'clean:es2015:cls'...
[18:36:18] Starting 'build:es2015:cls'...
[18:36:18] Starting 'clean:es2015:cls'...
[18:36:18] Finished 'clean:es2015:cjs' after 83 ms
[18:36:18] Starting 'compile:es2015:cjs'...
[18:36:18] Finished 'clean:es2015:esm' after 89 ms
[18:36:18] Starting 'compile:es2015:esm'...
[18:36:18] Finished 'clean:es2015:cls' after 93 ms
[18:36:18] Starting 'compile:es2015:cls'...
[18:36:18] Finished 'clean:es2015:cls' after 92 ms
[18:36:18] Starting 'compile:es2015:cls'...
[18:36:37] Finished 'compile:es2015:cls' after 18 s
[18:36:37] Starting 'package:es2015:cls'...
[18:36:37] Finished 'compile:es2015:cls' after 18 s
[18:36:37] Starting 'package:es2015:cls'...
[18:36:37] Finished 'package:es2015:cls' after 37 ms
[18:36:37] Finished 'build:es2015:cls' after 18 s
[18:36:37] Finished 'package:es2015:cls' after 36 ms
[18:36:37] Finished 'build:es2015:cls' after 18 s
[18:36:37] Starting 'clean:es2015:umd'...
[18:36:37] Finished 'clean:es2015:umd' after 37 ms
[18:36:37] Starting 'compile:es2015:umd'...
[18:36:38] Finished 'compile:es2015:esm' after 20 s
[18:36:38] Starting 'package:es2015:esm'...
[18:36:38] Finished 'package:es2015:esm' after 8.82 ms
[18:36:38] Finished 'build:es2015:esm' after 20 s
[18:36:38] Finished 'compile:es2015:cjs' after 20 s
[18:36:38] Starting 'package:es2015:cjs'...
[18:36:38] Finished 'package:es2015:cjs' after 5.34 ms
[18:36:38] Finished 'build:es2015:cjs' after 20 s
[18:36:48] 'compile:es2015:umd' errored after 11 s
[18:36:48] Error: gulp-google-closure-compiler: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(COMPUTED_PROP): targets/es2015/cls/data.js:156:28
    const { ['type']: type, ['offset']: offset = 0, ['length']: length = 0, } = props;
  Parent(OBJECT_PATTERN): targets/es2015/cls/data.js:156:10
    const { ['type']: type, ['offset']: offset = 0, ['length']: length = 0, } = props;

	at com.google.javascript.jscomp.Compiler.throwInternalError(Compiler.java:2898)
	at com.google.javascript.jscomp.NodeTraversal.throwUnexpectedException(NodeTraversal.java:442)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:462)
	at com.google.javascript.jscomp.NodeTraversal.access$200(NodeTraversal.java:38)
	at com.google.javascript.jscomp.NodeTraversal$Builder.traverse(NodeTraversal.java:398)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:468)
	at com.google.javascript.jscomp.ConvertToDottedProperties.process(ConvertToDottedProperties.java:39)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.performTranspilationAndOptimizations(Compiler.java:2582)
	at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$5(Compiler.java:947)
	at com.google.javascript.jscomp.CompilerExecutor.lambda$runInCompilerThread$0(CompilerExecutor.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
	at com.google.javascript.rhino.IR.stringKey(IR.java:682)
	at com.google.javascript.jscomp.ConvertToDottedProperties.visit(ConvertToDottedProperties.java:80)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:856)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:895)
	at com.google.javascript.jscomp.NodeTraversal.handleFunction(NodeTraversal.java:760)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:803)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:984)
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:748)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:800)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:847)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:459)
	... 15 more


CustomError: gulp-google-closure-compiler: Compilation errors occurred
    at CompilationStream._compilationComplete (/Users/dominik/Code/arrow/js/node_modules/google-closure-compiler/lib/gulp/index.js:238:28)
    at /Users/dominik/Code/arrow/js/node_modules/google-closure-compiler/lib/gulp/index.js:208:14

    at formatError (/Users/dominik/Code/arrow/js/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/Users/dominik/Code/arrow/js/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:402:35)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/Users/dominik/Code/arrow/js/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/dominik/Code/arrow/js/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/dominik/Code/arrow/js/node_modules/once/once.js:25:25)
    at f (/Users/dominik/Code/arrow/js/node_modules/once/once.js:25:25)
    at tryCatch (/Users/dominik/Code/arrow/js/node_modules/async-done/index.js:24:15)
    at done (/Users/dominik/Code/arrow/js/node_modules/async-done/index.js:40:12)
[18:36:48] 'build:es2015:umd' errored after 30 s
[18:36:48] 'build' errored after 30 s
error Command failed with exit code 1.
```

**Comment by frigus02** [comment] 2022-01-03 09:57
Thanks for the repro steps. I can easily reproduce the issue. It seems to be related to default values:

```
function foo(props) {
  // This has the above error
  const { ['type']: type, ['offset']: offset, ['length']: length = 0, } = props;
  // This works
  const { ['type']: type, ['offset']: offset, ['length']: length, } = props;
}
```

My guess is that this error was introduced with https://github.com/google/closure-compiler/commit/404ccd8cfe2541bbbe880c31d390f79ab8b7fc1c

**Comment by frigus02** [comment] 2022-01-07 08:46
This has been fixed in https://github.com/google/closure-compiler/commit/4a97027a0d3feed208424449e596d50b74237c90. Unfortunately it just missed the v20220104 release. But it will be included in the one next month.

**Closed by frigus02** 2022-01-07 08:46 UTC
Labels: bug
