### ISSUE TITLE
Allow accessing symbols using [] in classes / @structs.

### ISSUE THREAD

**Issue by pavelfeldman** [google/closure-compiler#2112] opened 2016-10-28 18:25 UTC
Unless I annotate my ES6 class as @unrestricted, I get a warning when I access symbol on this class externally.

class LibraryClass {
}

... client scope ...

const lib = new LibrabryClass();
lib[mysymbol] = "my metadata";

**Comment by jleyba** [comment] 2016-10-29 14:44
This is a duplicate of #1737

**Closed** 2016-10-29 15:37 UTC
