### ISSUE TITLE
Closure Compiler incompatible with TypeScript method decorators

### ISSUE THREAD

**Issue by btraut** [google/closure-compiler#2065] opened 2016-10-06 05:53 UTC
It appears that the use of [method decorators from TypeScript](https://www.typescriptlang.org/docs/handbook/decorators.html) fall flat on their face when run through Closure Compiler due to the use of function names being passed as strings.

I have an `AuthStoreImpl` class that declares a `getUser` method that has an `@autoSubscribe` decorator. TypeScript compiles this by adding this after the class definition:

```ts
__decorate([
       resub_1.autoSubscribe
], AuthStoreImpl.prototype, "getUser", null);
```

Obviously I can use `@nocompile` to prevent any file that uses a decorator to remain untouched, but that kind of defeats the purpose. What I would really love to do is to add an annotation to the `getUser` method to prevent renaming of just that method, but I was disappointed to read that [there's no plans to allow this granularity](https://github.com/google/closure-compiler/issues/2013).

If I may ask, what's the reason behind the decision to not allow inline annotations on specific symbols? It seems this would empower users to work around a lot of issues with Closure Compiler being to aggressive, especially when those users don't have complete control over their code (as is the case with code compiled by TypeScript).

**Comment by Dominator008** [comment] 2016-10-06 07:48
Can you provide more detail on how Closure Compiler failed on the TypeScript output?

**Comment by btraut** [comment] 2016-10-06 08:23
Sorry, should've provided this initially.

The issue here is that Closure Compiler renamed my `getUser()` method to `d()` or something of the sort, but because it doesn't modify strings, it left TypeScript's decorator to reference "getUser". Deep inside the `__decorate` stack trace, it tries to find the "getUser" function and no such function exists.

**Comment by ChadKillingsworth** [comment] 2016-10-06 09:57
Closure-compiler can rename string references safely now with `goog.reflect.objectProperty`:

```js
__decorate([
       resub_1.autoSubscribe
], AuthStoreImpl.prototype,
goog.reflect.objectProperty("getUser", AuthStoreImpl.prototype),
null);
```

That should safely compile.

**Comment by MatrixFrog** [comment] 2016-10-06 17:01
@mprobst probably knows of a good way to handle this.

**Comment by mprobst** [comment] 2016-10-06 23:04
@evmar is the expert. We're maintaining a tool called tsickle (http://github.com/angular/tsickle) that rewrites TypeScript output to be Closure compatible (including type annotations, actually). I'm not sure if we have something to fix this renaming issue with method decorators specifically, but it shouldn't be too hard to fix, I guess?

Alternatively, you could also ask the MS folks to change their emit to avoid quoting the method, e.g.

```
AuthStoreImpl.prototype.getUser = __decorate([
       resub_1.autoSubscribe
], AuthStoreImpl.prototype.getUser, null);
```

**Comment by btraut** [comment] 2016-10-06 23:12
I would love if the decorator didn't use strings, and I'll likely also reach out to the TS team as well.

As for using `goog.reflect`, I don't control TypeScript's output, so I have no opportunity to implement that solution. If tsickle could do that, it'd be great. I suppose I'd have to reach out to those folks to support decorators then?

**Comment by mprobst** [comment] 2016-10-06 23:22
@btraut please do file an issue against tsickle. Depending on the response from MS, this is something we should do.

**Comment by btraut** [comment] 2016-10-06 23:22
Posted over on the TS issues as well:
https://github.com/Microsoft/TypeScript/issues/11435

**Comment by rbuckton** [comment] 2016-10-06 23:23
@btraut One option available to you out of the box is to write a custom `__decorate` helper that calls `goog.reflect` and use that one instead.

**Comment by btraut** [comment] 2016-10-06 23:24
Sounds like the function name, "getUser" in my case eventually gets passed into `Object.defineProperty`, and must be a string as such.

**Comment by mprobst** [comment] 2016-10-06 23:24
@rbuckton the problem is that `goog.reflect.objectProperty` must take a string literal as its first input, it's a compiler intrinsic.

**Comment by rbuckton** [comment] 2016-10-06 23:25
Ah, I see.

**Comment by ChadKillingsworth** [comment] 2016-10-06 23:56
I'm going to close this issue as it doesn't appear to be anything the compiler itself can handle.

**Closed by ChadKillingsworth** 2016-10-06 23:56 UTC

**Comment by btraut** [comment] 2016-10-06 23:57
Thanks for the help, @ChadKillingsworth.
