### ISSUE TITLE
Compiler error, couple weeks ago there was no error

### ISSUE THREAD

**Issue by yupitomets** [google/closure-compiler#2355] opened 2017-03-06 23:46 UTC
JSC_PARSE_ERROR: Parse error. ')' expected at line 305 character 18 in flow.js
        async(ec, this)

Here is the code

var ec = function () { this.fire('complete'); };
        async(ec, this);

**Comment by anmonteiro** [comment] 2017-03-06 23:47
This is a duplicate of #2336

**Closed** 2017-03-07 00:46 UTC
