### ISSUE TITLE
Compiler crash on label when a specific function is defined earlier

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#190] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1172

**Comment by Dominator008** [comment] 2016-04-21 23:47
Cannot reproduce, closing.

**Closed by Dominator008** 2016-04-21 23:47 UTC
