### ISSUE TITLE
better support for `goog.module`

### ISSUE THREAD

**Issue by bobzhang** [google/closure-compiler#1620] opened 2016-03-09 02:51 UTC
```js
goog.module('foo.a')

exports.foo = function(x,y){
    return x + y;
}

function bar (x,y){
    return x * x * y;
}

exports.bar = bar;
```
```js
goog.module('hello.c')

var foo_a = goog.require('foo.a')

console.log(foo_a.foo(1,2),foo_a.bar(3,4))

```
in simple mode,

```js
var foo = {a:{}};
$jscomp.scope.bar = function(a, b) {
  return a * a * b;
};
foo.a.foo = function(a, b) {
  return a + b;
};
foo.a.bar = $jscomp.scope.bar;
hello.c = {};
console.log(foo.a.foo(1, 2), $jscomp.scope.bar(3, 4));
```

is it possible to compile `bar` the same as  `foo`? we would like to write `exports.bar = bar `.
I understand in the same file, it is a little tricky, but when it used in external file, should it be `foo_a.bar` instead of `$jscomp.scope.bar`?
Thanks!

**Comment by MatrixFrog** [comment] 2016-03-09 16:38
There are some changes coming, hopefully within the next week or so, that will make the the goog.module processing do its thing directly, rather than going through goog.scope. So the $jscomp.scope stuff will disappear. Stay tuned.

**Comment by bobzhang** [comment] 2016-03-10 19:33
@MatrixFrog thanks for looking, I think `goog.module` has a unique feature, it is the only one which is path insensitive

**Comment by bobzhang** [comment] 2016-03-10 19:57
when trying to use `goog.module` I also found some errors where I can not find documentation.

```sh
jscomp/stdlib/filename.js:146: ERROR - The alias temp_dir_name is assigned a value more than once.
  temp_dir_name = Caml_sys.caml_sys_getenv("TMPDIR");
  ^

jscomp/stdlib/filename.js:150: ERROR - The alias temp_dir_name is assigned a value more than once.
    temp_dir_name = "/tmp";
    ^

jscomp/stdlib/filename.js:153: ERROR - The body of a goog.scope function cannot use throw.
    throw exn;

```

**Comment by bobzhang** [comment] 2016-03-10 20:06
entry point seems not support goog.module either:

```
ocamlscript>/opt/bb/bin/java -jar ./node_modules/google-closure-compiler/compiler.jar --warning_level QUIET --compilation_level SIMPLE --js jscomp/runtime/*.js jscomp/stdlib/*.js jscomp/test/go\
ogle_closure_test.js --entry_point goog:buckle.test.test_google_closure --js_output_file xx.js                                                                                                    
ERROR - required entry point "buckle.test.test_google_closure" never provided                  

```
file jscomp/test/google_closure_test.js
```
goog.module("buckle.test.test_google_closure");    
```

**Comment by Dominator008** [comment] 2016-03-31 20:06
@bobzhang Now that https://github.com/google/closure-compiler/commit/cc05a011a002c52857335d9a72f826a96e3caf3a has landed, can you try your use cases again?

**Comment by bobzhang** [comment] 2016-04-02 10:35
hi @Dominator008 , thanks for your work. it works now with a couple of issues.

I got an error for some code:

```ocaml
test/test_closure.js:34: ERROR - The body of a goog.module cannot use throw.
  throw [
  ^
```
The error message is nicer, however, I would expect `goog.module` behaves the same as es6 module except it is path insensitive, is there any way to disable it ?

```
runtime/caml_io.js:2: WARNING - use strict is unnecessary in goog.module files.
'use strict';
^
```
`'use strict'` may be superflous, but should it be a warning explicitly turned on, is quite annoying to see so many warnings in my existing code, thanks!

**Comment by Dominator008** [comment] 2016-04-02 11:07
@bobzhang It wasn't my work, it was @stalcup's :+1: 
1. To eliminate the `The body of a goog.module cannot use throw.` message, you can wrap the throw in a function.
2. I'm not sure if that check is being too nitpicking, but we should at least add it to a DiagnosticGroup so people can suppress it. @blickly Can you clarify the necessity? Thanks.

**Comment by bobzhang** [comment] 2016-04-02 11:17
@Dominator008 thanks for quick response, note that the `throw` is inside a `try catch` body, the code is generated which requires more work to tweak the generator, is it possible to treat it as a warning instead of an error

**Comment by Dominator008** [comment] 2016-04-02 11:21
@bobzhang Currently it's not possible. We need to add it to a DiagnosticGroup so that people can make it a warning or suppress it. Stay tuned :)

**Comment by bobzhang** [comment] 2016-04-02 11:29
thanks, definitely no rush! 
I did not see the ERROR adds any safety to the module system, since as long as you allow function application in the toplevel (not just function definitions), anything can happen (including throwing exceptions)

**Comment by bobzhang** [comment] 2016-04-08 17:41
hi, is there any on going plan to lift restrictions on 

> test/test_closure.js:34: ERROR - The body of a goog.module cannot use throw.

**Comment by Dominator008** [comment] 2016-04-08 17:56
@bobzhang Per discussion within the team, we are a little hesitant on making `The body of a goog.module cannot use throw` suppressible.

@blickly Can you explain more? Thanks.

**Comment by bobzhang** [comment] 2016-04-08 18:52
I am interested in the reason underlying, if you allow

```js
(function(){ throw 'x'}())
```
how can it be different from 

```js
throw 'x'
```

**Comment by dimvar** [comment] 2016-04-08 18:58
The difference between these two is that you are explicitly going out of your way to throw, so you are telling the compiler "I know what I'm doing". What we are trying to prevent is to accidentally using throw at the top level without realizing the consequences (that if you bundle, it stops loading of all subsequent modules, not just the one that throws).

**Comment by blickly** [comment] 2016-04-08 19:00
Throwing during initialization of a single goog.module means that in the following modules will all be uninitialized as well, even if they have nothing to do with the throwing module.

For those that understand that tradeoff and have judged that they still want to throw, we don't prevent them from throwing in an IIFE (example 1).

For those who don't want the exceptional behavior in their module to really prevent all other modules from being initialized, hopefully giving an error for throw (example 2) will help them to correct course.

**Closed by blickly** 2016-04-08 19:00 UTC

**Comment by bobzhang** [comment] 2016-04-08 20:23
> For those that understand that tradeoff and have judged that they still want to throw, we don't prevent them from throwing in an IIFE (example 1).
I agree, it would be really nice to have a flag for powerful users to allow this, since the js code is generated, not written by human being

preventing `throw` in the syntax level (unless you do sophiscated flow analysis) really does not add any safety, any side effect in the toplevel can throw

**Comment by dimvar** [comment] 2016-04-08 20:33
> preventing throw in the syntax level (unless you do sophiscated flow analysis) really does not add any safety, any side effect in the toplevel can throw.

The check eliminates one kind of error, not all kinds. To give another example, if a type checker catches some but not all errors, would you say that it does not add any safety?

**Comment by bobzhang** [comment] 2016-04-08 20:46
I agree, just wish gcc can have some flags to give user some flexibility to make it usable in difference scenarios, my 2 cents

**Comment by bobzhang** [comment] 2016-04-08 20:58
To be more specific about my use case, I am working on a compiler(https://github.com/bloomberg/bucklescript)  which compiles OCaml code into Javascript, currently it supports different module systems (amd, commonjs), I wish to support goog module system as well, OCaml itself has a sound type system, so we mostly want to use Closure compiler as a bundle tool, safety check is nice but it's not our major interest.

Google module system has its added value compared to amd, commonjs, or es6, since it is not path sensitive, adding a flag would more flexible :-)

**Comment by Dominator008** [comment] 2016-04-08 21:05
@bobzhang The problem is that once people know such a suppression exists they tend to overuse it.
I'm not feeling too strong about this though. If you don't mind using a custom-built compiler, [this](https://github.com/google/closure-compiler/blob/587c05ee3db3dc373b10f19908aa9b0d9f2605ab/src/com/google/javascript/jscomp/ClosureRewriteModule.java#L1135) is the line you'd want to remove.

**Comment by bobzhang** [comment] 2016-04-08 21:18
hi @Dominator008 , it's perfectly fine to have flags prefixed with `--internal-xxx`. 
Thanks for the link, is the line to suppress warnings about `use strict;`? Currently the blocking issue is `disallowing throw in toplevel`, I guess allowing throw requires much less work than my side,and it generates consistent code for different module system

**Comment by Dominator008** [comment] 2016-04-08 21:22
@bobzhang That line is reporting the error about throwing in modules. If you remove that then the Compiler won't give the error.

**Comment by bobzhang** [comment] 2016-04-08 21:36
hi @Dominator008 , thanks for the info. It's fine for me to have a customize build, but we want other people who use our compiler to use Closure compiler as well, the added effort is much higher in that case

**Comment by bobzhang** [comment] 2016-04-09 00:13
I have no plan to make a fork, the maintainance cost is just so high. I really wish closure developers can make it a little flexible for more use cases

**Comment by Dominator008** [comment] 2016-04-09 00:28
@bobzhang How many files do you have that `throw`s in the top-level? If it's a small set of files, then check out the `--warnings_whitelist_file` flag, which helps suppressing particular warnings.

**Comment by bobzhang** [comment] 2016-04-09 00:37
Thanks, I will give it a try. But here it's not a warning, it's an error, I am fine with warnings, closure refuse to bundle when it found the error. Take typescript compiler for example, it still emit js file even if it finds a type error.
Currently, in our ocaml standard libraries, I only found one file, but I would expect users would have some too.

**Comment by bobzhang** [comment] 2016-04-10 19:31
Another argument to disable this check by default is that it means more difference from es6 module, and any difference from es6 module (besides the `google.require` vs `import`) needs to be documented. for example, I am not sure if there are more checks which will break my valid es6 code

**Comment by Dominator008** [comment] 2016-04-15 20:26
@bobzhang Have you tried the `--warnings_whitelist_file` flag for your use case?
