### ISSUE TITLE
Templates breaking record type structural equality

### ISSUE THREAD

**Issue by balasanjay** [google/closure-compiler#1703] opened 2016-04-02 00:37 UTC
[Somewhat minimal repro on closure-compiler.appspot.com](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language_in%2520ES6_STRICT%250A%252F%252F%2520%2540language_out%2520ES5_STRICT%250A%252F%252F%2520%2540use_closure_library%2520true%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540constructor%2520%2540struct%2520%2540final%250A%2520*%2520%2540template%2520T%250A%2520*%252F%250Afunction%2520f()%2520%257B%250A%257D%250A%252F**%250A%2520*%2520%2540param%2520%257BT%257D%2520p%250A%2520*%252F%250Af.prototype.g%2520%253D%2520function(p)%2520%257B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257BT%257D%2520data%250A%2520*%2520%2540return%2520%257B!f%253CT%253E%257D%250A%2520*%2520%2540template%2520T%250A%2520*%252F%250Afunction%2520h(data)%2520%257B%250A%2520%2520return%2520new%2520f()%253B%250A%257D%250A%250A%250Avar%2520x%2520%253D%2520h(%257Bincident%253A%2520'hello'%257D)%253B%250Ax.g(%257Bincident%253A%2520'hello'%257D))

> JSC_TYPE_MISMATCH: actual parameter 1 of f.prototype.g does not match formal parameter
> found   : {incident: string}
> required: {incident: string} at line 24 character 4
> x.g({incident: 'hello'})

**Comment by dimvar** [comment] 2016-04-04 06:41
Duplicate of #1302. This is fixed in the new type inference, if you want to try it out: https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)

**Closed by dimvar** 2016-04-04 06:41 UTC
