### ISSUE TITLE
Feature - prevent compiler from bloating core module

### ISSUE THREAD

**Issue by dmitrysteblyuk** [google/closure-compiler#2546] opened 2017-06-26 12:38 UTC
If I have several sub modules with one dependency (say core.js), then it is impossible for them to have duplicate code. All the code they share is automatically moved to core.js. But the problem is that this shared code is not shared by all the modules and is not used on the home page. As a result core.js which is supposed to be light weighted gets bloated.

P.S. Worth mentioning compiler also throws Duplicate input if submodules have the same input. But even after I created copies to avoid this error this shared code still went to core.js

**Comment by nicks** [comment] 2017-06-26 14:34
The easy way to do this is to create an empty "common-async" module in between core and everything else, so that the compiler has a place to move the common code.

**Comment by brad4d** [comment] 2017-06-26 17:40
@dmitrysteblyuk 
There isn't enough information in your description for me to reproduce the problem.
I can tell you that the compiler only moves code down the module dependency tree and never up.

I'm closing this as "cannot reproduce," but feel free to reopen it with at more detailed demonstration of the problem.

**Comment by ChadKillingsworth** [comment] 2017-06-26 17:50
@nicks suggestion is the usual way to fix this. It's either a module tree like:

```
core.js
  |
homepage
  |        \
subpage       subpage 2
```

or

```
homepage
  |
core.js
  |         \
subpage       subpage 2
```

I believe it's possible to define a compiler output module with zero files - just a sink for the compiler to move code into.

**Comment by dmitrysteblyuk** [comment] 2017-06-26 18:46
So in my case I have modules structure like this:
core:278
common:0:core
create-group.module:42:common
group.module:65:common
user.module:51:core

Where create-group.module and group.module share some code that is not in core (and I don't want it there).

In output manifest I have:
{core}
320 files

{common:core}
common$fillFile

{create-group.module:common}
4 files

{group.module:common}
32 files

{user.module:core}
10 files

As an outcome common module got skipped entirely and shared code from create-group.module and group.module got moved to core.js

**Comment by brad4d** [comment] 2017-06-26 19:48
@dmitrysteblyuk 
I am as close as possible to 100% certain that there is no way the compiler would ever move code up the dependency tree, but it sounds like you're saying that has happened here. Do I misunderstand you? If this is happening, it is very serious.

In your example, where did the code that moved to core come from (i.e. which module contains the file that originally contained that code)? 

I still need something more concrete to investigate any further. I need actual example files and module definitions, so that I can actually execute the compiler on them and see the results you describe.

**Comment by ChadKillingsworth** [comment] 2017-06-26 19:49
@brad4d It DOES move code like this - cross module code motion. This is by design. Just need a little more control over where it moves it.

**Comment by dmitrysteblyuk** [comment] 2017-06-26 21:10
Ok, I think I got it. Common module should not be empty but should contain all the files which are used in both my sub modules but not in core.js:

./core.js
./core-dependency.js
--module=core:2
./ab-dependency.js
--module=common:1:core
./a-sub-module.js
--module=a-sub:1:common
./b-sub-module.js
--module=b-sub:1:common
./c-sub-module.js
--module=c-sub:1:core

Then after compilation I can just concatenate compiled common.js with each of the sub modules.

**Comment by nicks** [comment] 2017-06-26 21:21
Yep! you got it. But instead of duplicating common.js a bunch of times, you typically have a Module Loader that knows when it's necessary load common.js and loads it exactly once (see Closure Library's goog.module for an example)

**Comment by ChadKillingsworth** [comment] 2017-06-26 21:50
I'm closing this again - I believe everything is working as intended. While it would be nice to support code duplication in cases where the compiler can't move the code, that's not a priority for anyone right now.

**Comment by brad4d** [comment] 2017-06-26 21:56
@ChadKillingsworth fwiw I'm quite aware of CrossModuleCodeMotion and have been working on it.
I was saying that it would never move code up the graph, only down.

**Comment by ChadKillingsworth** [comment] 2017-06-26 21:56
Sorry misunderstood - most people don't know of that one. I thought it was the reverse :)

Reopening ...

**Comment by brad4d** [comment] 2017-06-26 21:58
I still think this should be closed.
Looks like @dmitrysteblyuk got the answer he was looking for.

**Closed by brad4d** 2017-06-26 21:58 UTC
Labels: cannot reproduce

**Comment by dmitrysteblyuk** [comment] 2017-06-27 05:24
Thank you guys so much for the answers. They do work for me. But my case is quite simple so far and I'm sure if the number of sub modules grows, it would be quite difficult to track which sub modules depend on what and based on that add those common modules (let alone do it programmatically).

What I wanted to propose is support for duplicate input if they listed in different modules. Like this:
--allow-duplicates=true
./core.js
./core-dependency.js
--module=core:2

./a-sub-module.js
./ab-dependency.js
--module=a-sub:2:core

./b-sub-module.js
./ab-dependency.js
--module=b-sub:2:core

./c-sub-module.js
--module=c-sub:1:core

This topic is quite old actually. It was discussed before: https://groups.google.com/forum/#!topic/closure-compiler-discuss/cfmTuDuNGQk
