### ISSUE TITLE
Class template variables do not seem to apply to getters and setters.

### ISSUE THREAD

**Issue by justy123** [google/closure-compiler#3095] opened 2018-10-01 13:54 UTC
Example:

```
/** @template K */
class Foo {
  /** @param {!K} k */
  constructor(k) {
    this.k_ = k;
  }

  /** @return {!K} */
  get k() {
    return this.k_;
  }

  /** @param {!K} value */
  set k(value) {
    this.k_ = value;
  }

  /** @return {!K} */
  getKey() {
    return this.k_;
  }

  /** @param {!K} value */
  setKey(value) {
    this.k_ = value;
  }
};

```
Compiler gives the following warnings for the first two functions, but not the latter two.

```
WARNING - Bad type annotation. Unknown type K
  /** @return {!K} */
                ^

WARNING - Bad type annotation. Unknown type K
  /** @param {!K} value */
               ^
```

**Comment by lauraharker** [comment] 2018-10-01 21:53
@brad4d just submitted a change internally to move class transpilation after typechecking. I confirmed that it fixes this issue. There is a small change the change will be rolled back, though, because it affects some of the compiler optimizations. 

I'll update this issue once the change is available on GitHub.

**Comment by lauraharker** [comment] 2018-10-02 02:04
Fixed by https://github.com/google/closure-compiler/commit/a7c0bb5893068de7e3ac2f15506d2e53a5025bd3.

Not sure if it will make it into this month's release, but it will definitely be there next month.

Meanwhile, for anyone using the current release, templates on class getters/setters almost work... you get spurious "Bad type annotation" warnings like OP reported, but you also get accurate type warnings when calling the getter/setter.

``` javascript
/** @template K */
class Foo {
  /** @param {!K} k */
  constructor(k) {
    this.k_ = k;
  }

  /** @param {!K} value */
  set k(value) {
    this.k_ = value;
  }
}

const /** !Foo<string> */ foo = new Foo('some string');

foo.k = 34; // should be a type error
```
[produces](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540template%2520K%2520*%252F%250Aclass%2520Foo%2520%257B%250A%2520%2520%252F**%2520%2540param%2520%257B!K%257D%2520k%2520*%252F%250A%2520%2520constructor(k)%2520%257B%250A%2520%2520%2520%2520this.k_%2520%253D%2520k%253B%250A%2520%2520%257D%250A%250A%2520%2520%252F**%2520%2540param%2520%257B!K%257D%2520value%2520*%252F%250A%2520%2520set%2520k(value)%2520%257B%250A%2520%2520%2520%2520this.k_%2520%253D%2520value%253B%250A%2520%2520%257D%250A%257D%250A%250Aconst%2520%252F**%2520!Foo%253Cstring%253E%2520*%252F%2520foo%2520%253D%2520new%2520Foo('some%2520string')%253B%250A%250Afoo.k%2520%253D%252034%253B%2520%252F%252F%2520this%2520produces%2520a%2520valid%2520type%2520error%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)
```
input0:8: WARNING - Bad type annotation. Unknown type K
  /** @param {!K} value */
               ^

input0:16: WARNING - assignment to property k of Foo<string>
found   : number
required: string
foo.k = 34; // should be a type error
^^^^^^^^^^
```
But https://github.com/google/closure-compiler/commit/a7c0bb5893068de7e3ac2f15506d2e53a5025bd3 makes the "Bad type annotation" warning disappear.

**Closed by lauraharker** 2018-10-02 02:04 UTC
