### ISSUE TITLE
Unknown type warnings when using templates

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#168] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1224

**Comment by supersteves** [comment] 2015-10-07 16:20
Appears to be a dup of https://github.com/google/closure-compiler/issues/490

**Comment by Dominator008** [comment] 2016-05-10 00:55
Duplicate of #490, which is fixed in NTI.

**Closed by Dominator008** 2016-05-10 00:55 UTC
Labels: duplicate
