### ISSUE TITLE
google.map.mapTypes.set() wrong jsDoc in google_maps_api_v3_exp.js

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#296] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#861

**Comment by Dirklectisch** [comment] 2018-09-18 09:28
I failed to reproduce this problem. The problem is fixed in an update of the maps externs back in april.

https://github.com/google/closure-compiler/commit/4d9d7a4696760d0d4838a31a620b36d0e4910f43#diff-4d8422258754e450c304dd8ae2574e37R3389

**Closed** 2018-09-22 00:59 UTC
