### ISSUE TITLE
async polyfill does not support await rejected promise in try block with await in finally

### ISSUE THREAD

**Issue by mitchellwills** [google/closure-compiler#2504] opened 2017-05-21 17:33 UTC
If an awaited promise is rejected in an async function the function will be rejected with undefined instead of the value the promise was rejected with. In the example below stuff the compiled code will result in the promise being rejected with the value undefined, but executing the original source in chrome will result in it being rejected with the expected Error value. If the await statement in the finally block is removed the function evaluates as expected.

```
async function stuff() {
  try {
    await Promise.reject(new Error('xyz'));
    // this works: throw new Error('123');
    return 5;
  } finally {
    await Promise.resolve();
  }
}
stuff()
```

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language%2520ECMASCRIPT8%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aasync%2520function%2520stuff()%2520%257B%250A%2520%2520try%2520%257B%250A%2520%2520%2520%2520await%2520Promise.reject(new%2520Error('xyz'))%253B%250A%2520%2520%2520%2520%252F%252F%2520this%2520works%253A%2520throw%2520new%2520Error('123')%253B%250A%2520%2520%2520%2520return%25205%253B%250A%2520%2520%257D%2520finally%2520%257B%250A%2520%2520%2520%2520await%2520Promise.resolve()%253B%250A%2520%2520%257D%250A%257D%250Astuff()

**Comment by mitchellwills** [comment] 2017-05-21 17:43
This actually can cause the error to be dropped entirely when combined with https://github.com/google/closure-compiler/issues/2503. For example, the call to fn2 below will resolve successfully with a value of undefined.

```
async function fn1() {
  try {
    await Promise.reject(new Error('xyz'));
    return 5;
  } finally {
    await Promise.resolve();
  }
}

async function fn2() {
  await fn1();
}
fn2()
```

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language%2520ECMASCRIPT8%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aasync%2520function%2520fn1()%2520%257B%250A%2520%2520try%2520%257B%250A%2520%2520%2520%2520await%2520Promise.reject(new%2520Error('xyz'))%253B%250A%2520%2520%2520%2520return%25205%253B%250A%2520%2520%257D%2520finally%2520%257B%250A%2520%2520%2520%2520await%2520Promise.resolve()%253B%250A%2520%2520%257D%250A%257D%250A%250Aasync%2520function%2520fn2()%2520%257B%250A%2520%2520await%2520fn1()%253B%250A%257D%250Afn2()

**Comment by brad4d** [comment] 2017-05-22 18:39
As with #2503 I believe this is a problem with the underlying generator function transpilation.

**Comment by mitchellwills** [comment] 2017-08-11 20:36
Any progress on this. It looks like it wasn't resolved by the changes made for #2503

**Comment by brad4d** [comment] 2017-08-22 21:41
I'm creating a runtime test based on the second example posted May 21 to confirm that this is broken or document that it works.

**Comment by mitchellwills** [comment] 2017-09-08 22:39
Any luck with reproducing the issue? I'm still seeing it in my code

**Comment by brad4d** [comment] 2017-09-15 16:03
Added a repro test case to our runtime tests.
Working on a solution.

**Comment by brad4d** [comment] 2017-10-05 22:05
Core problem is with generator transpilation code.
repro test case (disabled) is here
https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/runtime_tests/generator_test.js#L995

**Comment by brad4d** [comment] 2017-11-14 19:49
Looking into this more today, I've realized that this code is also transpiled incorrectly.

```javascript
function *f() {
  let a = 1, b = 2;
  try {
    return a + b;
  } finally {
    a = 5;
  }
}
```

The returned expression `a  + b` should be calculated and the result saved before entering the finally block. Instead the statement `return a + b` is executed after the finally block ends.

The root cause is the same as this issue. We need to explicitly save the returned value or thrown exception when entering a finally block.

**Comment by mitchellwills** [comment] 2018-01-09 21:21
Any luck with a fix?

**Comment by brad4d** [comment] 2018-01-09 22:31
Had a meeting to discuss a fix for this today.
A fix is planned for Q1.

**Comment by brad4d** [comment] 2018-03-16 15:13
This was fixed by the recent generators transpilation rewrite.
It'll be in the next open source release.

**Closed by brad4d** 2018-03-16 15:13 UTC
