### ISSUE TITLE
INTERNAL COMPILER ERROR - InferJSDocInfo.attachJSDocInfoToNominalTypeOrShape

### ISSUE THREAD

**Issue by veselov** [google/closure-compiler#877] opened 2015-03-18 00:09 UTC
I haven't yet been able to reduce our humongous source to find SSCE for this. The compiler fails with:

    null
    Node(NAME undefined): externs.zip//es3.js:82:4
    var undefined;
    Parent(VAR): externs.zip//es3.js:82:0
    var undefined;

	at com.google.javascript.jscomp.InferJSDocInfo.attachJSDocInfoToNominalTypeOrShape(InferJSDocInfo.java:227)
	at com.google.javascript.jscomp.InferJSDocInfo.visit(InferJSDocInfo.java:144)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:576)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:570)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:528)
	at com.google.javascript.jscomp.InferJSDocInfo.process(InferJSDocInfo.java:76)
	at com.google.javascript.jscomp.TypeCheck.check(TypeCheck.java:429)
	at com.google.javascript.jscomp.TypeCheck.process(TypeCheck.java:396)
	at com.google.javascript.jscomp.DefaultPassConfig$48$1.process(DefaultPassConfig.java:1470)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:844)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:757)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NullPointerException
  	... 24 more

The `objType` in `attachJSDocInfoToNominalTypeOrShape()` method is com.google.javascript.rhino.jstype.NoType, it returns `hasReferenceName()` -- true, but `getReferenceName()` returns null.

I've "fixed" this by adding additional check for `getReferenceName() == null`, but I don't know what I'm doing.

**Comment by dimvar** [comment] 2015-06-18 22:20
Closing because we can't reproduce. If you find a code sample to reproduce this, leave a comment.

**Closed by dimvar** 2015-06-18 22:20 UTC
