### ISSUE TITLE
JSCompiler_renameProperty not found with compilation_level ADVANCED in compiler distributed on NPM

### ISSUE THREAD

**Issue by rictic** [google/closure-compiler#3991] opened 2022-09-09 01:39 UTC
Consider code like:

```javascript
const o = {foo: 'bar'};
console.log(o);
console.log(JSCompiler_renameProperty('foo', o));
```

In advanced mode, the properties should be renamed, and the call to JSCompiler_renameProperty should be replaced with the renamed property name as a string literal. Internally with blaze this is the case, and it's the case in the compiler playground: https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconst%2520o%2520%253D%2520%257Bfoo%253A%2520'bar'%257D%253B%250Aconsole.log(o)%253B%250Aconsole.log(JSCompiler_renameProperty('foo'%252C%2520o))%253B

However, when compiling with the compiler distributed via npm compiling that code with --compilation_level=ADVANCED fails with:

```
main.js:3:12: ERROR - [JSC_UNDEFINED_VARIABLE] variable JSCompiler_renameProperty is undeclared
  3| console.log(JSCompiler_renameProperty('foo', o));
```

Even more surprising, compiling with `--compilation_level=SIMPLE` works properly, and the `JSCompiler_renameProperty` call is correctly replaced with the un-renamed property name.

I've tested with the latest version, `20220803.0.0`, but our earliest reports of this bug are a couple years old.

Stand alone repro at https://github.com/rictic/jscompiler_renameProperty-const-repro

**Comment by concavelenz** [comment] 2022-09-16 22:56
JSCompiler has always been built around the idea that the code it is provide should be functional *before* it is compiled.  It expects that some definition of "JSCompiler_renameProperty" is provided, either in the externs or as part of the code.  So this is working as expected.

If you are using Closure Library, `goog.reflect.object` and `goog.reflect.objectProperty` may suit your needs.

**Comment by concavelenz** [comment] 2022-09-16 22:58
Closing as working as intended

**Closed by concavelenz** 2022-09-16 22:58 UTC
