### ISSUE TITLE
Conditional CommonJS export doesn't respect logic

### ISSUE THREAD

**Issue by nichtverstehen** [google/closure-compiler#2945] opened 2018-05-25 11:18 UTC
This program:
```
const Timing = true;
if (!Timing) {
  console.warn("Boo.");
  module.exports = {};
} else {
  console.warn("Yay.");
}
```
should print `Yay`.

But JSCompiler with `--process_common_js_modules` produces:
```
console.warn("Boo.");
```

If `module.exports = {}` line is removed, the output is as expected:
```
console.warn("Yay.");
```

For an example of this in the wild see [JSTimers.js](https://github.com/facebook/react-native/blob/master/Libraries/Core/Timers/JSTimers.js#L486).

**Comment by ChadKillingsworth** [comment] 2018-05-25 12:07
Pretty sure this is a duplicate of #2841

**Closed by ChadKillingsworth** 2018-05-25 12:07 UTC
