### ISSUE TITLE
new type inference thinks HTMLCanvasElement is not an EventTarget

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#832] opened 2015-02-18 16:59 UTC
Using new type inference compile option --new_type_inf produces this incorrect warning:

```
src/lab/app/SimController.js:255: WARNING - Invalid type for parameter 1 of function goog.events.listen.
expected : EventTarget|goog.events.Listenable|null
found    : HTMLCanvasElement

  this.mouseDownKey_ = goog.events.listen(labCanvas.getCanvas(),
                                          ^
```

HTMLCanvasElement is an Element, which is an EventTarget, so this warning is wrong.

Here is the definition of the `getCanvas` method:

```javascript
/**
* @return {!HTMLCanvasElement}
*/
LabCanvas.prototype.getCanvas = function() {
  return this.canvas_;
};
```

compiler version:
```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150126-82-g85da5b6
Built on: 2015/02/11 20:55
```

**Comment by dimvar** [comment] 2015-05-06 20:19
duplicate of #865

**Closed by dimvar** 2015-05-06 20:19 UTC
Labels: bug, duplicate, NTI

**Comment by myphysicslab** [comment] 2015-05-23 04:35
confirmed fixed in Version: v20150505-58-g39bb337
