### ISSUE TITLE
NullPointerException when adding prototypical properties on a record in an extern

### ISSUE THREAD

**Issue by azakus** [google/closure-compiler#2556] opened 2017-07-01 00:04 UTC
# Summary
In this [commit](https://github.com/Polymer/polymer/commit/10f286b442049bcb2782ce5889a396af82b33726) to Polymer, I tried adding some instance properties of a mixin class onto the corresponding record and hit a 100% repro NullPointerException when compiling.

# Setup
> This requires Node and NPM
- Check out https://github.com/Polymer/polymer/tree/compiler-error
- Run `npm run reproduce`

Output will look something like this:
```
[16:59:03] gulp-google-closure-compiler: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.javascript.jscomp.GlobalTypeInfo.checkSuperProperty(GlobalTypeInfo.java:784)
	at com.google.javascript.jscomp.GlobalTypeInfo.checkAndFreezeNominalType(GlobalTypeInfo.java:647)
	at com.google.javascript.jscomp.GlobalTypeInfo.process(GlobalTypeInfo.java:484)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:305)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:231)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1110)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:910)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:101)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:844)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:841)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by azakus** [comment] 2017-07-01 00:05
@ChadKillingsworth @MatrixFrog

**Comment by MatrixFrog** [comment] 2017-07-01 01:40
Looks like the line that's failing (after some recent refactorings) is now at https://github.com/google/closure-compiler/blob/511e40b813cfdf56151382a42f26c31fb8e4d983/src/com/google/javascript/jscomp/GlobalTypeInfoCollector.java#L690

**Comment by MatrixFrog** [comment] 2017-07-01 02:18
Added more information to the failure message, and it shows that the call that's failing: `getPropDefFromClass(DataTemplate, __dataCompoundStorage) returned null`. I'm not sure where the type `DataTemplate` comes from.

**Comment by azakus** [comment] 2017-07-05 17:30
@MatrixFrog here's the DataTemplate class definition: https://github.com/Polymer/polymer/blob/compiler-error/lib/utils/templatize.html#L40

**Comment by ChadKillingsworth** [comment] 2017-07-07 02:49
@MatrixFrog Do you need more info on this one? It's a blocker for landing the Polymer PRs.

**Comment by MatrixFrog** [comment] 2017-07-07 20:07
Actually I'm going to kick this over to @dimvar I think, since it's in NTI :)

**Comment by dimvar** [comment] 2017-07-11 19:48
@azakus Can you provide a way to reproduce this by just calling the compiler? When doing `npm run reproduce`, I'm not even sure how to edit the compiler sources to debug this. If you can provide a repro and file a bug internally, even better.

**Comment by ChadKillingsworth** [comment] 2017-07-11 19:53
@dimvar I can get you that here in just a few minutes.

**Comment by dimvar** [comment] 2017-07-11 19:58
great, thanks.

**Comment by ChadKillingsworth** [comment] 2017-07-11 20:37
Repo files: [closure.zip](https://github.com/google/closure-compiler/files/1140158/closure.zip)

External Command Line Runner Args:
```
java -jar ../node_modules/google-closure-compiler/compiler.jar
    -O=ADVANCED -W=VERBOSE --language_in=ES6_STRICT
    --language_out=ES5_STRICT --isolation_mode=IIFE
    --assume_function_wrapper --rewrite_polyfills=false
    --new_type_inf --js="./**.js"
```

I used a compiler built from master this morning.

**Comment by dimvar** [comment] 2017-07-11 23:09
I reproduced this and I'm in the process of debugging. I haven't gotten to a small repro yet.

**Comment by dimvar** [comment] 2017-07-12 18:49
I sent a fix for this internally for review. Hopefully it will be pushed externally tomorrow.

**Closed** 2017-07-13 23:00 UTC
