### ISSUE TITLE
JSC_TYPE_MISMATCH default parameter treated as undefined within a closure

### ISSUE THREAD

**Issue by l1bbcsg** [google/closure-compiler#3452] opened 2019-08-14 12:00 UTC
Sample code: 

```js
/**
 * @param {Object=} param
 */
const foo = (param = {}) => {
	/**
	 * @type {Object}
	 */
	const bar = param; // no warning

	const closure = () => {
		/**
		 * @type {Object}
		 */
		const bar = param; // JSC_TYPE_MISMATCH
	};
};
```

Here, the outer function `foo` accepts an optional parameter that has a default value. Within the main body of `foo` compiler correctly deduces than `param` cannot be undefined and raises no warning on line 8. But within a closure on line 14 it thinks `param` could be undefined and raises:

```
WARNING - [JSC_TYPE_MISMATCH] initializing variable
found   : (Object|null|undefined)
required: (Object|null)
		const bar = param;
		            ^^^^^
```

Compiler version: `v20190729`, java binary.

**Comment by lauraharker** [comment] 2019-08-14 18:41
Closing as a duplicate of https://github.com/google/closure-compiler/issues/3327.

**Closed by lauraharker** 2019-08-14 18:42 UTC
