### ISSUE TITLE
Strange behavior with inheritDoc in externs

### ISSUE THREAD

**Issue by divergence082** [google/closure-compiler#1086] opened 2015-08-18 12:47 UTC
externs:
```js
/**
 * @interface
 */
thrift.protocol.IProtocol = function() {};

/**
 * @return {thrift.protocol.Type}
 */
thrift.protocol.IProtocol.prototype.getType = function() {};

...

/**
 * @param {!thrift.ISchema} idl
 *
 * @constructor
 * @implements {thrift.protocol.IProtocol}
 */
thrift.protocol.Json = function(idl) {};

/**
 * @inheritDoc
 */
thrift.protocol.Json.prototype.getType = function() {};
```

error:
```
node_modules/node-thrift/externs/index.js:1030: ERROR - mismatch of the getType property type and the type of the property it overrides from interface thrift.protocol.IProtocol
original: function (this:thrift.protocol.IProtocol): thrift.protocol.Type.<number>
override: function (this:thrift.protocol.Json): undefined
thrift.protocol.Json.prototype.getType = function() {};

```

what's wrong? 

used flags:
--warning_level=VERBOSE
--language_in=ECMASCRIPT5_STRICT
--jscomp_off=externsValidation
--jscomp_error=checkTypes

if i remove --jscomp_error=checkTypes - error disappears

**Comment by dimvar** [comment] 2015-08-18 17:43
I can't reproduce this on the debugger.
http://closure-compiler-debugger.appspot.com/home#input0%26input1%26conformanceConfig%26externs%3D%252F**%2520%2540interface%2520*%252F%250Afunction%2520High()%2520%257B%257D%250A%250A%252F**%2520%2540return%2520%257Bnumber%257D%2520*%252F%250AHigh.prototype.f%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540constructor%2520%2540implements%2520%257BHigh%257D%2520*%252F%250Afunction%2520Low()%2520%257B%257D%250A%250A%252F**%2520%2540inheritDoc%2520*%252F%250ALow.prototype.f%2520%253D%2520function()%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1

Can you provide an example of the bug happening in the debugger, or other exact steps to reproduce?

**Comment by concavelenz** [comment] 2015-08-26 00:39
maybe a old version of the compiler?

**Comment by Dominator008** [comment] 2016-04-29 08:29
Cannot reproduce, closing.

**Closed by Dominator008** 2016-04-29 08:29 UTC
