### ISSUE TITLE
Exporting API in separate file does not work

### ISSUE THREAD

**Issue by kranich** [google/closure-compiler#1587] opened 2016-02-25 17:43 UTC
As a minimum failing example, please consider

Test.js
```javascript
var Test = {};
Test.test = function () {
    return 42;
};
```

API.js
```javascript
window["Test"] = Test;
window["Test"]["test"] = Test.test;
```

If I invoke Closure Compiler v20160208 as `java -jar compiler.jar --language_in ECMASCRIPT6_STRICT --language_out ECMASCRIPT5_STRICT --compilation_level ADVANCED --dependency_mode LOOSE --warning_level VERBOSE --js API.js Test.js`, I obtain the non-sensical

```javascript
'use strict';window.Test=a;window.Test.test=a.test;var a={test:function(){return 42}};
```

instead of the expected

```javascript
'use strict';var a={test:function(){return 42}};window.Test=a;window.Test.test=a.test;
```

Interchanging the order of `API.js` and `Test.js` is a workaround for this minimum example, but does not work in my larger codebase. Somehow, `--dependency_mode LOOSE` fails to determine the correct order.

**Comment by Dominator008** [comment] 2016-02-25 18:37
This is working as intended. Since `API.js` references a variable declared in `Test.js`, `Test.js` needs to come first. `--dependency_mode LOOSE` couldn't determine the correct order in this case because the files didn't expose any dependency directives like `goog.require` or `goog.provide`.

Note that due to https://github.com/google/closure-compiler/issues/1548, you might want to specify separate `--js` flags for each file. That bug has been fixed in `master`

**Closed by Dominator008** 2016-02-25 18:37 UTC

**Comment by kranich** [comment] 2016-02-25 18:43
Just in case others face similar problems, I would like to add that the following changes solve the issue:

Test.js
```javascript
var Test = {};
Test.test = function () {
    return 42;
};
export default Test;
```

API.js

```javascript
import Test from "API";
window["Test"] = Test;
window["Test"]["test"] = Test.test;
```

**Comment by Dominator008** [comment] 2016-02-25 19:01
@kranich Exacly. By turning them into ES6 modules, the compiler now knows about the dependency.
