### ISSUE TITLE
Side effect calculator doesn't work well with functional extern methods

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2128] opened 2016-11-05 01:51 UTC
A number of built-in methods take functions, such as `Array.from`, `Array.prototype.map`, and others. These externs cannot be marked as `@nosideeffects` because the built-in function does in fact call the passed-in function.  But there's no way to tell the compiler that that is the *only* side effect, so if the passed-in function is pure (or missing, in case of `Array.from`) then the built-in call also has no side effects.

This could be solved in one of three ways:
1. adding a way to tell externs to inherit their purity from one (or more) of their arguments;
2. assuming a `@nosideeffects` extern function that takes a function parameter has the possible side effect of calling that function, and so cannot be removed unless the passed-in function is itself pure; or
3. providing a sample implementation (e.g. the polyfill) that the compiler can use to infer the side effects, though this will run into the problem that it's very difficult to even write `Array.from` without the compiler thinking there's side effects even without the mapping function, since it requires array property assignment, and the compiler doesn't know how to prove that the array is not leaked from global state.

**Comment by ChadKillingsworth** [comment] 2016-11-05 12:06
Duplicate of #2093

**Closed by ChadKillingsworth** 2016-11-05 12:06 UTC
