### ISSUE TITLE
ERROR - variable goog is undeclared

### ISSUE THREAD

**Issue by bitbay** [google/closure-compiler#1816] opened 2016-05-26 11:31 UTC
Trying to compile 
```javascript
class A {
    constructor(){
    }
    
    /** @export */
    c(){ }
}

class B extends A {
    constructor(){
        super();
    }
}

let test = new B();
```

with the following command
```
$ java -jar compiler.jar ^
--js index.js ^
--js_output_file compiled.js ^
--language_in=ECMASCRIPT6_STRICT ^
--language_out=ECMASCRIPT5 ^
--generate_exports ^
--export_local_property_definitions ^
--compilation_level ADVANCED ^
--formatting PRETTY_PRINT ^
--warning_level VERBOSE
```

but getting the following output:
```
index.js:8: ERROR - variable goog is undeclared
    c(){ }
    ^

1 error(s), 0 warning(s), 91,5% typed
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable goog
  Node(NAME goog): src/index3.js:8:4
    c(){ }
  Parent(GETPROP): src/index3.js:8:4
    c(){ }

        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:201)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:623)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:316)
        at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:143)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1984)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:717)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:659)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:656)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.IllegalStateException: Unexpected variable goog
        ... 22 more
```

Console output made me _report this problem_...

**Comment by MatrixFrog** [comment] 2016-05-26 15:43
--generate_exports tells the compiler to output calls to goog.exportSymbol() when you use the `@export` annotation in your code. If you want to use that then you need the Closure Library (or at least base.js)

We should make this fail fast though instead of crashing.

**Comment by Dominator008** [comment] 2016-05-27 00:08
Duplicate of https://github.com/google/closure-compiler/issues/1393.

**Closed by Dominator008** 2016-05-27 00:08 UTC
Labels: duplicate
