### ISSUE TITLE
Cannot call symbol-indexed ES6 computed property methods

### ISSUE THREAD

**Issue by ochafik** [google/closure-compiler#1720] opened 2016-04-11 13:12 UTC
Symbols are treated as regular values, which causes warnings when calling on a `@struct` (including ES6 classes) and prevents method inlining: 
```js
let method = Symbol('method');

class Foo {
  [method]() { return 1 }
}

// JSC_ILLEGAL_PROPERTY_ACCESS: Cannot do '[]' access on a struct at line 7 character 22
console.log(new Foo()[method]());
//                    ^
```
(see in [online console](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Alet%2520method%2520%253D%2520Symbol('method')%253B%250A%250Aclass%2520Foo%2520%257B%250A%2520%2520%255Bmethod%255D()%2520%257B%2520return%25201%2520%257D%250A%257D%250A%250Aconsole.log(new%2520Foo()%255Bmethod%255D())%253B))

Maybe symbols could be treated as some sort of namespace instead? (using their defining file + name as unique key)

**Comment by ChadKillingsworth** [comment] 2016-10-29 15:37
Duplicate of #1737

**Closed by ChadKillingsworth** 2016-10-29 15:37 UTC
