### ISSUE TITLE
Add warnings for misuse of abstract classes.

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#385] opened 2014-04-29 20:29 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#95

**Comment by Dominator008** [comment] 2016-08-01 16:46
Duplicate of #104.

**Closed by Dominator008** 2016-08-01 16:46 UTC
Labels: duplicate, enhancement, Work In Progress
