### ISSUE TITLE
Compiler produces code with syntax error

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#195] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1161

**Comment by Dominator008** [comment] 2016-01-23 16:26
Can't reproduce with given code:
```javascript
function x_42() {
}
while (typeof function x_61() {
}) {
}
new undefined(x_42);
```
, closing.

**Closed by Dominator008** 2016-01-23 16:26 UTC

**Comment by jkavalik** [comment] 2016-10-17 08:04
@Dominator008 I was able to reproduce it for the `new undefined();` example from the linked issue with  `Version: v20150315`
