### ISSUE TITLE
Compiler doesn't understand NodeJS glob patterns

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#1698] opened 2016-03-30 12:52 UTC
The globbing pattern for the compiler is currently `/path/to/**.js` however NodeJS globbing patterns are of the form `/path/to/**/*.js`. Is there any way to make the compiler understand the NodeJS globbing syntax - and if not throw a warning or error for an invalid globbing pattern?

See chadkillingsworth/closure-compiler-npm#6 and chadkillingsworth/closure-compiler-npm#16.

**Comment by Dominator008** [comment] 2016-03-30 15:28
I thought those were fixed in v20160208. See this test case: https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/CommandLineRunnerTest.java#L1221-L1222

**Comment by Dominator008** [comment] 2016-03-30 15:58
NodeJS glob patterns seem to work as intended, see https://github.com/ChadKillingsworth/closure-compiler-npm/issues/16#issuecomment-203501213. I think the bug is in the Gulp plugin.

**Closed by Dominator008** 2016-03-30 15:58 UTC
