### ISSUE TITLE
Safevalues library is not working with Closure Compiler

### ISSUE THREAD

**Issue by opozo** [google/closure-compiler#4073] opened 2023-03-21 21:32 UTC
[Safevalues](https://github.com/google/safevalues) library is not working with Closure Compiler, I'm using `NODE` module resolution and including the `node_modules` source with (e.g. `--js node_modules/safevalues/**.js`), still getting:

```
ERROR - [JSC_DOES_NOT_HAVE_EXPORT] Requested module does not have an export "safeDocument".
  1| import {safeDocument} from 'safevalues/dom';
```

**Comment by mhausner** [comment] 2023-03-22 16:18
Can you provide an actual code sample and command line that reproduces the error?

**Comment by opozo** [comment] 2023-03-22 17:55
Install [Safevalues](https://github.com/google/safevalues) library through npm: `npm install safevalues`

frontend/inject/min/js/inject.js:

```
import {safeDocument} from 'safevalues/dom';

export function inject() {
    console.log('testing safeDocument: ', safeDocument);
}
inject();
```

inject-closure-compiler.conf:

```
--compilation_level=SIMPLE_OPTIMIZATIONS
--language_out=ES5
--js_output_file=frontend/inject/min/bundle.min.js
--warning_level=QUIET
--dependency_mode=PRUNE
--module_resolution=NODE
--process_common_js_modules=true

--js node_modules/safevalues/**.js
--js frontend/inject/min/js/**.js

--entry_point=frontend/inject/min/js/inject
```

command:

```
java -jar node_modules/google-closure-compiler-java/compiler.jar --flagfile inject-closure-compiler.conf
frontend/inject/min/js/inject.js:1:0: ERROR - [JSC_DOES_NOT_HAVE_EXPORT] Requested module does not have an export "safeDocument".
  1| import { safeDocument } from 'safevalues/dom';
     ^

1 error(s), 0 warning(s)
```

**Comment by gunan** [comment] 2023-06-27 17:01
Closing this issue as it seems to be a problem in the third party library.

**Closed by gunan** 2023-06-27 17:01 UTC
