### ISSUE TITLE
Functions on subclass prototype not type checked for parent class

### ISSUE THREAD

**Issue by pauldraper** [google/closure-compiler#1242] opened 2015-11-02 23:33 UTC
This compiles, though the wrong # of arguments are passed to the function.

```javascript
/**
 * @constructor
 */
function Foo() {}

/**
 * @constructor
 * @extends {Foo}
 */
function Bar() {}

/**
 * @param {string} a
 */
Bar.prototype.bar = function(a) {};

window['keep'] = new Foo().bar();
```

A less fabricated example:

```javascript
document.createElement('canvas').getContext(function anythingIsOkay() {});
```
Since 98% of the time, HTML elements have parent type, this makes the `getContext` extern on `HTMLCanvasElement` (and other element-specific functions) almost worthless for static checks.

**Comment by dimvar** [comment] 2015-11-02 23:46
The issue is that the current type checker is loose about missing properties. The correct warning here would be that bar doesn't exist on Foo. For any class that you annotate with @struct, you will get the [warning](http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540struct%250A%2520*%252F%250Afunction%2520Foo()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257BFoo%257D%250A%2520*%252F%250Afunction%2520Bar()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520a%250A%2520*%252F%250ABar.prototype.bar%2520%253D%2520function(a)%2520%257B%257D%253B%250A%250Anew%2520Foo().bar()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1).

You can also try out --new_type_inf, which is stricter about missing properties and catches this.

**Comment by dimvar** [comment] 2015-11-02 23:50
Duplicate of #265

**Closed by dimvar** 2015-11-02 23:50 UTC

**Comment by pauldraper** [comment] 2015-11-02 23:58
@dimvar, I think I may have used a bad example. I meant to create a self-contained example that had the same problem as `HTMLCanvasElement.prototype.getContext`. I didn't mean to illustrate the missing property issue.

```javascript
/**
 * @constructor
 */
function Foo() {}

/**
 * @constructor
 * @extends {Foo}
 */
function Bar() {}

/**
 * @param {string} a
 */
Bar.prototype.bar = function(a) {};

/**
 * @type {Foo}
 */
var foo = new Bar;

window['keep'] = foo.bar();
```

This compiles. But if you modify `@type {Foo}` to be `@type {Bar}`, you get the expected `JSC_WRONG_ARGUMENT_COUNT`.

**Comment by dimvar** [comment] 2015-11-03 00:03
The problem is that there is no property bar on a Foo. (And when a variable x is annotated as Foo, that's all a type checker can assume about it, because the type checker can't know whether x holds a subtype.) If you call the method and the receiver is a bar, you'll see the wrong-argument-count issue.

**Comment by dimvar** [comment] 2015-11-03 00:04
So, your example is fine, it's just that you shouldn't expect type checking on property accesses that shouldn't have been allowed in the first place.

**Comment by pauldraper** [comment] 2015-11-03 00:09
Right. I was thinking that you would grant leniency as long at it *could* be correct.

I tried the new type inference.

I see that it now requires downcasting, which is a reasonable thing.

So the `HTMLCanvasElement.prototype.getContext` example is required by new type inference to be

```javascript
/** @type {HTMLCanvasElement} */(document.createElement('canvas')).getContext('foo')
```
