### ISSUE TITLE
Code Printer prints code with syntax error

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#193] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1167

**Comment by Dominator008** [comment] 2016-01-23 16:35
Cannot reproduce with given code:
```javascript
for (var x_52 = /Precise Badger/ in {}) {}
```
. Parse error was correctly given. Closing.

**Closed by Dominator008** 2016-01-23 16:35 UTC
Labels: bug, P2
