### ISSUE TITLE
Add type checking in async functions

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2191] opened 2016-12-09 07:35 UTC
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language%2520ECMASCRIPT8%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520hello()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520let%2520s%2520%253D%25201%253B%2520%252F%252F%2520WARNING%250A%257D%250A%250Aasync%2520function%2520hello_async()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520let%2520s%2520%253D%25201%253B%2520%252F%252F%2520IGNORE%250A%257D%250A%250A%250A

**Comment by brad4d** [comment] 2016-12-12 19:09
@ikabirov thanks for the bug report.
@dimvar it's not clear to me why this code would fail to give a warning. Any immediate thoughts?

```javascript
async function hello_async() {
  /** @type {string} */
  let s = 1; // IGNORED type error
}
```

**Comment by brad4d** [comment] 2016-12-12 19:14
I think this is a bug related to generators transpilation.

I notice that the type information on `s` is getting lost. The relevant transpiled code looks like this.

```javascript
function hello_async() {
  /**
 @suppress {uselessCode}
 */
function $jscomp$async$generator() {
    function $jscomp$generator$impl($jscomp$generator$next$arg, $jscomp$generator$throw$arg) {
      for (;1;) {
        switch($jscomp$generator$state) {
          case 0:
            s = 1;
            $jscomp$generator$state = -1;
          default:
            return {value:undefined, done:true};
        }
      }
    }
    var $jscomp$generator$state = 0;
    var s;
    var iterator = {next:function(arg) {
      return $jscomp$generator$impl(arg, undefined);
    }, throw:function(arg) {
      return $jscomp$generator$impl(undefined, arg);
    }, return:function(arg) {
      throw Error("Not yet implemented");
    }};
    $jscomp.initSymbolIterator();
    /**
 @this {!Generator<?>}
 */
iterator[Symbol.iterator] = function() {
      return this;
    };
    return iterator;
  }
  return $jscomp.executeAsyncGenerator($jscomp$async$generator());
}
```

https://closure-compiler-debugger.appspot.com/#input0%3Dasync%2520function%2520hello_async()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520let%2520s%2520%253D%25201%253B%2520%252F%252F%2520IGNORE%250A%257D%250A%250A%250Afunction%2520hello()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520let%2520s%2520%253D%25201%253B%2520%252F%252F%2520WARNING%250A%257D%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by brad4d** [comment] 2016-12-14 17:16
Yep, this code also fails to get a warning.

```javascript
function *hello() {
  /** @type {string} */
  let s = 1;
}
```

**Comment by MatrixFrog** [comment] 2016-12-14 18:00
Probably we're just failing to copy over the JSDocInfo at a couple of spots.

**Comment by ikabirov** [comment] 2018-03-10 13:49
Any news on this ?

**Comment by brad4d** [comment] 2018-03-11 17:49
Looks like this was fixed by the recent rewrite of the generators transpilation pass.
I confirmed that our current internal release issues warnings for both functions in the original example.
The next opensource release will include the fix.

**Comment by ikabirov** [comment] 2018-03-12 06:58
awesome! thanks

**Closed** 2018-03-23 18:24 UTC
