### ISSUE TITLE
NTI, goog.module and reportUnknownTypes do not work well together

### ISSUE THREAD

**Issue by hochhaus** [google/closure-compiler#2187] opened 2016-12-07 20:37 UTC
NTI may not be able to infer the correct type of `goog.required` symbols inside a `goog.module` file.

For example, the following program compiles fine with OTI but has errors with NTI.

```
ahochhaus@ahochhaus-pc:~/bug$ cat example.js 
goog.module('example');

const json = goog.require('goog.json');

exports = function() {
  console.log(json.parse('[]'));
};
ahochhaus@ahochhaus-pc:~/bug$ java -jar closure-compiler-v20161201.jar --js closure-library-20161201/closure/goog/base.js --js closure-library-20161201/closure/goog/json/json.js --js example.js --compilation_level=ADVANCED --jscomp_error=* --jscomp_error=reportUnknownTypes --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --dependency_mode=LOOSE --entry_point goog:example --hide_warnings_for=closure-library-20161201 --new_type_inf
example.js:6: ERROR - This CALL expression has the unknown type.
  console.log(json.parse('[]'));
              ^^^^^^^^^^^^^^^^

example.js:6: ERROR - This GETPROP expression has the unknown type.
  console.log(json.parse('[]'));
              ^^^^^^^^^^

2 error(s), 0 warning(s)
ahochhaus@ahochhaus-pc:~/bug$ java -jar closure-compiler-v20161201.jar --js closure-library-20161201/closure/goog/base.js --js closure-library-20161201/closure/goog/json/json.js --js example.js --compilation_level=ADVANCED --jscomp_error=* --jscomp_error=reportUnknownTypes --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --dependency_mode=LOOSE --entry_point goog:example --hide_warnings_for=closure-library-20161201 > /dev/null ; echo $?
0
```

See this [rules_closure post](https://groups.google.com/forum/#!topic/closure-rules-discuss/aTzPyNZ7-pc) for more context.

**Comment by dimvar** [comment] 2016-12-21 23:28
I cannot reproduce this in the debugger. See [here](https://jscomp-debug.googleplex.com/#input0%3Dgoog.provide('goog.json')%253B%250A%250A%252F**%2520%2540type%2520%257BFunction%257D%2520*%252F%250Agoog.json%2520%253D%2520function()%2520%257B%257D%253B%26input1%3Dgoog.module('example')%253B%250A%250Aconst%2520json%2520%253D%2520goog.require('goog.json')%253B%250A%250Aexports%2520%253D%2520function()%2520%257B%250A%2520%2520var%2520%252F**%2520null%2520*%252F%2520n%2520%253D%2520json%253B%250A%2520%2520console.log(json.parse('456'))%253B%250A%257D%253B%26conformanceConfig%26externs%3Dvar%2520goog%2520%253D%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1), `json` is typed correctly so we get a warning when assigning to `null`.

Can you check that `goog` and `goog.json` are defined in your sources?

**Comment by dimvar** [comment] 2016-12-21 23:38
Nevermind, I see the issue. I reproduced in the debugger [here](https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide('goog.json')%253B%250A%250A%252F**%2520%2540type%2520%257BFunction%257D%2520*%252F%250Agoog.json%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%250A%2520*%2520%2540param%2520%257B*%257D%2520s%2520The%2520JSON%2520string%2520to%2520parse.%250A%2520*%2520%2540throws%2520Error%2520if%2520s%2520is%2520invalid%2520JSON.%250A%2520*%2520%2540return%2520%257BObject%257D%250A%2520*%252F%250Agoog.json.parse%2520%253D%2520(1%253C2)%2520%253F%250A%2520%2520function(s)%2520%257B%2520return%2520%257B%257D%253B%2520%257D%2520%253A%2520function(s)%2520%257B%2520return%2520%257B%257D%253B%2520%257D%253B%26input1%3Dgoog.module('example')%253B%250A%250Aconst%2520json%2520%253D%2520goog.require('goog.json')%253B%250A%250Aexports%2520%253D%2520function()%2520%257B%250A%2520%2520var%2520%252F**%2520null%2520*%252F%2520n%2520%253D%2520json%253B%250A%2520%2520n%2520%253D%2520json.parse%253B%250A%2520%2520console.log(json.parse('456'))%253B%250A%257D%253B%26conformanceConfig%26externs%3Dvar%2520goog%2520%253D%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1).

The problem is that goog.json.parse is initialized in a weird way, so NTI does not recognize the function declaration.

**Closed** 2016-12-22 18:14 UTC
Labels: NTI
