### ISSUE TITLE
Add externs for DOM4's remove

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#284] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#896

**Comment by Dominator008** [comment] 2016-04-22 02:03
Duplicate of https://github.com/google/closure-compiler/issues/914

**Closed by Dominator008** 2016-04-22 02:03 UTC
Labels: Externs
