### ISSUE TITLE
Some errors on my 'ugly' project

### ISSUE THREAD

**Issue by schmitch** [google/closure-compiler#1077] opened 2015-08-13 16:20 UTC
Hello, I run a project which is quite large (and ugly) and got the following error while running the closure-compiler:

```
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

INTERNAL COMPILER ERROR.
Please report this problem.

Invalid attempt to remove node: NAME workflowFactory 129 [originalname: workflowFactory] [source_file: src/app/workflow-create-route/workflow-create-route.es6.js] of IMPORT 129 [source_file: src/app/workflow-create-route/workflow-create-route.es6.js]
  Node(NAME workflowFactory): src/app/workflow-create-route/workflow-create-route.es6.js:129:7
import workflowFactory from '../workflow-factory/workflow-factory.es6.js'
  Parent(IMPORT): src/app/workflow-create-route/workflow-create-route.es6.js:129:0
import workflowFactory from '../workflow-factory/workflow-factory.es6.js'

    at com.google.javascript.jscomp.NodeUtil.removeChild(NodeUtil.java:2220)
    at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.removeNode(UnreachableCodeElimination.java:261)
    at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.removeDeadExprStatementSafely(UnreachableCodeElimination.java:251)
    at com.google.javascript.jscomp.UnreachableCodeElimination$EliminationPass.visit(UnreachableCodeElimination.java:104)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:577)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:571)
    at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
    at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:528)
    at com.google.javascript.jscomp.UnreachableCodeElimination$1.visit(UnreachableCodeElimination.java:81)
    at com.google.javascript.jscomp.NodeTraversal$1.shouldTraverse(NodeTraversal.java:515)
    at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:558)
    at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:289)
    at com.google.javascript.jscomp.NodeTraversal.traverseChangedFunctions(NodeTraversal.java:520)
    at com.google.javascript.jscomp.UnreachableCodeElimination.process(UnreachableCodeElimination.java:66)
    at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
    at com.google.javascript.jscomp.PhaseOptimizer$Loop.process(PhaseOptimizer.java:458)
    at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
    at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1979)
    at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:765)
    at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:94)
    at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
    at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
    at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:701)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Invalid attempt to remove node: NAME workflowFactory 129 [originalname: workflowFactory] [source_file: src/app/workflow-create-route/workflow-create-route.es6.js] of IMPORT 129 [source_file: src/app/workflow-create-route/workflow-create-route.es6.js]
  Node(NAME workflowFactory): src/app/workflow-create-route/workflow-create-route.es6.js:129:7
import workflowFactory from '../workflow-factory/workflow-factory.es6.js'
  Parent(IMPORT): src/app/workflow-create-route/workflow-create-route.es6.js:129:0
import workflowFactory from '../workflow-factory/workflow-factory.es6.js'

    ... 29 more
Caused by: java.lang.IllegalStateException: Invalid attempt to remove node: NAME workflowFactory 129 [originalname: workflowFactory] [source_file: src/app/workflow-create-route/workflow-create-route.es6.js] of IMPORT 129 [source_file: src/app/w
```

**Comment by dimvar** [comment] 2015-08-13 16:31
Tyler, is there enough information in this bug report for you to debug this? I just came here to close this because there is no source code or instructions on how to reproduce, but I see you seem to know the cause of the bug?

**Comment by schmitch** [comment] 2015-08-13 16:32
I could also provide some source, code and I'm currently looking into it. (oh and at the moment we mix imports with goog.require / goog.provide (but in a simple demo that didn't make too much problems)

**Comment by MatrixFrog** [comment] 2015-08-13 16:45
I don't know but I think we've seen similar reports before so I'll try to at least dig those up and link to them here before closing this.

**Comment by schmitch** [comment] 2015-08-13 16:50
Currently this is a angular site and i get the following warnings:
```
./app/workflow-create-route/workflow-create-route.es6.js:14: WARNING - unreachable code
import workflowFactory from '../workflow-factory/workflow-factory.es6.js'
       ^

./app/workflow-create-route/workflow-create-route.es6.js:15: WARNING - unreachable code
import offer from '../offer/offer.js'
       ^

./app/workflow-create-route/workflow-create-route.es6.js:16: WARNING - unreachable code
import offerService from '../offer/offer-service.js'
       ^

./app/workflow-create-route/workflow-create-route.es6.js:128: WARNING - unreachable code
export default angular.module('ev.workflowCreateRoute', [
```

I think they are related

**Comment by MatrixFrog** [comment] 2015-10-01 21:05
Sorry for the delay in getting back to this. What --language_out flag are you using? If it's ES6 try switching to --language_out=ES3 and see if that makes the crash go away.

**Comment by Dominator008** [comment] 2016-09-29 23:20
@schmitch Could you see if this crash still exists?

**Comment by ChadKillingsworth** [comment] 2017-01-28 01:33
Closing this for lack of activity.

**Closed by ChadKillingsworth** 2017-01-28 01:33 UTC
Labels: bug, ES6
