### ISSUE TITLE
Generic types for es6 classes and getters

### ISSUE THREAD

**Issue by joscha** [google/closure-compiler#2168] opened 2016-11-24 04:49 UTC
I am trying to annotate a getter on an es6 class with a generic type, but I can't seem to get it working.
A simplified example of the problem is:

```js
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// @language_out ES5
// ==/ClosureCompiler==

/** @template T */
class X {
  
  /** @param {T} x */
  constructor(x) {
    this.x = x;
  }

  /** @return {T} */
  get foo() {
    return this.x;
  }
}
```
Produces:
```
JSC_TYPE_PARSE_ERROR: Bad type annotation. Unknown type T at line 9 character 15
  /** @return {T} */
```

which is the annotation on the `foo` getter (the constructor seems to work fine)

(Checked with https://closure-compiler.appspot.com)

**Comment by joscha** [comment] 2016-11-30 14:10
I am happy to look into it if anyone has a couple of pointers where a good place to start would be.

**Comment by MatrixFrog** [comment] 2016-12-01 19:10
I think I promised someone I would fix this a while back, and then it turned out to be harder than I thought. I believe the `@template` annotation on the class gets copied as you'd expect, but the problem is that the getter lives outside of the class in the transpiled output:

```
/** @constructor @template T */
function X() {}

Object.defineProperties(X.prototype, {
  foo: {
    /** @return {T} */    // <- The compiler doesn't know what you mean by "T" here.
    get: function() { return this.x; }
  }
});
```

I suspect this will ultimately be fixed by having the typechecker understand ES6 classes (including getters and setters) directly instead of typechecking the output of the 6-to-5 conversion :(

**Comment by b-strauss** [comment] 2017-08-24 12:55
I just stumbled upon this while converting my library to ES2015. What's the status of this? Is the typechecker still checking the ES5 output?

**Comment by brad4d** [comment] 2017-08-24 15:24
@b-strauss 
The short answer is "yes, the type checker still only sees ES5 code".
Efforts are underway to change this.
Many optimization passes have now been updated to understand ES6 code, and it is now possible to request ES6 output from the compiler.
However, the type checker is one of the hardest parts to change and we're part way through switching from OTI (old type inference) to NTI (new type inference), which complicates things.

**Comment by lauraharker** [comment] 2018-12-04 18:18
This is fixed now

**Closed by lauraharker** 2018-12-04 18:18 UTC
Labels: ES6, Types
