### ISSUE TITLE
Missing extern `Array.from`

### ISSUE THREAD

**Issue by ambar** [google/closure-compiler#1296] opened 2015-12-13 02:45 UTC

**Comment by Dominator008** [comment] 2015-12-13 03:00
Care to send a PR?
Should be similar to https://github.com/google/closure-compiler/commit/6f7901cea15d96d3651ec1b190da18ccd1c50968

**Comment by ambar** [comment] 2015-12-13 04:02
#1297

**Comment by Dominator008** [comment] 2015-12-14 02:11
Updated in #1298

**Comment by Dominator008** [comment] 2015-12-18 01:00
What about the two optional parameters? Some issues with them?

**Comment by MatrixFrog** [comment] 2015-12-18 01:52
The issue is that I completely forgot about them. Sorry about that! The hard part was landing this in a way that doesn't break several Google projects. Now that that's done it should be easy to add those.

**Comment by Dominator008** [comment] 2015-12-18 02:14
Sounds good :) I have them in #1298

**Comment by Dominator008** [comment] 2016-01-13 13:21
Reworked in #1377, closing.

**Closed by Dominator008** 2016-01-13 13:21 UTC
