### ISSUE TITLE
v20160208 is not available nor on MavenCentral nor on bintray

### ISSUE THREAD

**Issue by xtracoder** [google/closure-compiler#1595] opened 2016-02-27 19:26 UTC
According to https://github.com/google/closure-compiler/wiki/Releases version `v20160208` was released 20 days ago, but i do not see it deployed to neither of

http://mvnrepository.com/artifact/com.google.javascript/closure-compiler
https://bintray.com/bintray/jcenter/com.google.javascript%3Aclosure-compiler/view

Is there something wrong with deployment?

**Comment by Dominator008** [comment] 2016-02-27 20:52
Duplicate of #1485.

**Closed by Dominator008** 2016-02-27 20:52 UTC
