### ISSUE TITLE
Const names result in final classes in goog.module

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1834] opened 2016-06-08 18:28 UTC
```js
goog.module('base');

/** @constructor */
const Base = function() { };

/** @constructor @extends {Base} */
const Derived = function() { };
```

>ERROR - module$blah_Derived is not allowed to extend final class module$blah_Base.  
>const Derived = function(){};

This only happens in a goog.module, and only with const, not let.

http://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('base')%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%250Aconst%2520Base%2520%253D%2520function()%2520%257B%2520%257D%253B%250A%250A%252F**%2520%2540constructor%2520%2540extends%2520%257BBase%257D%2520*%252F%250Aconst%2520Derived%2520%253D%2520function()%2520%257B%2520%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_VISIBILITY%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by MatrixFrog** [comment] 2016-06-08 18:30
duplicate of https://github.com/google/closure-compiler/issues/1492 I think.

**Closed by MatrixFrog** 2016-06-08 18:30 UTC
