### ISSUE TITLE
Inverted question mark string incorrectly translated by Closure Compiler

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#311] opened 2014-04-29 20:28 UTC
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#780

**Comment by Dominator008** [comment] 2016-04-22 00:30
Cannot reproduce, closing.

**Closed by Dominator008** 2016-04-22 00:30 UTC
