### ISSUE TITLE
Support dead code elimination for ES6 getters and setters

### ISSUE THREAD

**Issue by DavidSouther** [google/closure-compiler#1923] opened 2016-07-29 17:32 UTC
Currently, getters and setters desugar to `Object.defineProperties`, which doesn't allow for shaking, inlining, and other analysis. With ES6 adoption, users will want to have these behave as they expect other methods to behave in regards to their minified output.

**Comment by ChadKillingsworth** [comment] 2016-07-29 21:39
This is probably a long ways out.

**Comment by Dominator008** [comment] 2016-09-30 03:07
Duplicate of #1157.

**Closed by Dominator008** 2016-09-30 03:07 UTC
Labels: duplicate, enhancement, ES6
