### ISSUE TITLE
JSC_INSTANTIATE_ABSTRACT_CLASS error on the constructor function

### ISSUE THREAD

**Issue by karikera** [google/closure-compiler#3892] opened 2021-11-26 06:49 UTC
**Search terms:**
JSC_INSTANTIATE_ABSTRACT_CLASS new constructor

 ** Summary **
JSC_INSTANTIATE_ABSTRACT_CLASS error on the constructor function

 **Example**
```js

/**
 * @abstract
 */
class Foobar {
}


/**
 * @param {function(new:Foobar)} ctor
 */
function a(ctor) {
	new ctor; // WARNING - [JSC_INSTANTIATE_ABSTRACT_CLASS] cannot instantiate abstract class
}

```

**Comment by rishipal** [comment] 2021-12-01 00:50
This is a duplicate of internal bug http://b/187853548 which was fixed. It does not reproduce on the internal jscompiler.

But it still reproduces externally - https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%252F**%250A%2520*%2520%2540abstract%250A%2520*%252F%250Aclass%2520Foobar%2520%257B%250A%257D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bfunction(new%253AFoobar)%257D%2520ctor%250A%2520*%252F%250Afunction%2520a(ctor)%2520%257B%250A%2509new%2520ctor%253B%2520%252F%252F%2520WARNING%2520-%2520%255BJSC_INSTANTIATE_ABSTRACT_CLASS%255D%2520cannot%2520instantiate%2520abstract%2520class%250A%257D

**Comment by rishipal** [comment] 2021-12-01 00:52
Also duplicate - https://github.com/google/closure-compiler/issues/2630

**Closed** 2021-12-04 05:34 UTC
Labels: triage-done
