### ISSUE TITLE
Initializing and Exporting Properties 

### ISSUE THREAD

**Issue by yishayw** [google/closure-compiler#2758] opened 2017-12-12 06:23 UTC
I think I stumbled upon a bug when trying to export an object property which is initialized and declared on the same line.

In the below example [1], where the property is not initialized the output is

function a(){}var b=["components","MyComp"],c=this;b[0]in c||!c.execScript||c.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)b.length||void 0===a?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=a;var e=new a;e.myProp=!0;alert(e.myProp);

So the alert box shows true (correct behavior).

But when it is initialized [2] the output is

function a(){}var b=["components","MyComp"],c=this;b[0]in c||!c.execScript||c.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)b.length||void 0===a?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=a;a.prototype.a=!1;a.prototype.myProp=a.prototype.a;alert(!1);

So the alert box shows false (which is incorrect).

[1] https://paste.apache.org/EJwJ
[2] https://paste.apache.org/YeQ7

**Comment by lauraharker** [comment] 2017-12-12 19:40
Simpler debugger reproduction: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520MyComp%2520%253D%2520function()%2520%257B%257D%253B%250A%2520%250AMyComp.prototype.myProp%2520%253D%2520false%253B%250A%2520%250A%2520%250Avar%2520myComp%2520%253D%2520new%2520MyComp()%253B%250A%252F%252F%2520this%2520is%2520converted%2520to%2520myComp.myProp%2520%253D%2520true%253B%2520%250A%252F%252F%2520but%2520only%2520after%2520other%2520optimizations%2520have%2520already%2520run.%250AmyComp%255B%2522myProp%2522%255D%2520%253D%2520true%253B%250Aalert(myComp.myProp)%253B%2520%252F%252F%2520should%2520be%2520alert(true)%253B%26input1%26conformanceConfig%26externs%3Dfunction%2520alert(s)%2520%257B%257D%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26INLINE_PROPERTIES%3Dtrue%26CONVERT_TO_DOTTED_PROPERTIES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

The examples you linked use both dot-syntax and quoted strings to access `components.MyComp.prototype.myProp`/`myComp["myProp"]`. This violates a compiler assumption in advanced optimizations that you either always use dot-syntax or always use quoted strings to refer to a given property - see https://developers.google.com/closure/compiler/docs/api-tutorial3#propnames.

In case [1], the compiled code happens to work anyway, but still violates the compiler's assumptions.

Marking as works as intended.

**Closed by lauraharker** 2017-12-12 19:40 UTC
