### ISSUE TITLE
this refers to window in compiled static methods

### ISSUE THREAD

**Issue by rahbari** [google/closure-compiler#2558] opened 2017-07-06 05:03 UTC
Compile this class:
```
class Test {
	static $test() {
		console.log(this);
	}
}
Test.$test();
```

Compiled code:
```
(function() {
  console.log(this);
})();
```

this refers to window instead of class constructor!

**Comment by ChadKillingsworth** [comment] 2017-07-06 13:54
Duplicate of #2397

**Closed by ChadKillingsworth** 2017-07-06 13:54 UTC
